### ISSUE TITLE
0800Callback

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#10]
Ao testar a url
http://sip.hilario.net.br/mbilling/index.php/call0800Web?user=12500 com a versao 6.0.3
o softphone toca e quando a outra chamada e feita o softphone toca novamente na segunda linha e n liga para o numero desejado. eu tentei ligar para 553132098888 e meu eyebean tocou 2 vez mas, o destino não tocou.

**Comment by magnussolution** [comment]
LOG. Sem log não tem como testar.

**Comment by hilariovoip** [comment]
vou mandar um log agora

**Comment by hilariovoip** [comment]
Quando eu solicito a chamada via  http://sip.hilario.net.br/mbilling/index.php/call0800Web?user=12500 para o numero 553132098888 meu celular toca no eyebeam atendo e escuto,  " a pessoa no ramal 12500 nao esta disponivel deixa sua mensagem na caixa postal" não chama no numero digitado no site.
segue o log:

![erro3](https://user-images.githubusercontent.com/30841526/29138610-afa4b96c-7d1a-11e7-9036-3218949676fc.PNG)
