### ISSUE TITLE
Remoção de crédito

### ISSUE THREAD

**Issue by dracohellgate** [magnussolution/magnusbilling#100]
Na hora que adiciona crédito negativo para ajustar algum erro ele da rollback, e não retira o crédito do cliente.. versão atualizada hoje a 5 minutos.. 6.0.4

**Comment by hiperphone** [comment]
Realizei este teste no MB6 e a conta do cliente fica negativa sem erro..  Basca colocar o sinal negativo antes do numero.

**Comment by dracohellgate** [comment]
Ja fiz
Ele fica,por alguns segundos depoiz da rollback
Caso,queira ver no teamviewer eu mosteo
Instalacao nova e Limpa



Em 19 de out de 2017 6:44 PM, "hiperphone" <notifications@github.com>
escreveu:

**Comment by dracohellgate** [comment]
Só para completar, segui o manual de instalação nova no centos 7, funciona tudo menos os que alertei. estou voltando hoje para versao anterior para nao ter prejuizos nesse mes, quando estiver mais correto volto a utilizar a MB6

**Comment by hiperphone** [comment]
Desculpe, só comentei porque estou testando o MB6 exaustivamente antes de colocar em produção e esta falha nao ocorreu aqui.

**Comment by dracohellgate** [comment]
Achei que ja estava stable, coloquei a 4 dias em produção, e tive essas surpresinhas...

**Comment by magnussolution** [comment]
nao adianta abrir ISSUE com este tipo de descrição. Seja técnico com o relato de problema.

leia https://github.com/magnussolution/magnusbilling6/issues/56

Se nao puder encontrar o problema ocorrido pode contratar suporte comercial para te ajudar.
