### ISSUE TITLE
contexto nas contas voip

### ISSUE THREAD

**Issue by dracohellgate** [magnussolution/magnusbilling#101]
Fiquei 3 dias praticamente sem tarifar para meus clientes pois o sistema adicionou as contas voip sem contexto (billing) estava em branco, consequentemente clientes estavam utilizando sem custo.

**Comment by hiperphone** [comment]
Tenho varias conta no MB5 e em teste no MB6 com o contexto vazio e tarifa certo conforme tabela.

**Comment by dracohellgate** [comment]
tenho um MB5 que funciona perfeito, esse me deixou na mao, desconfiei que nao estava tarifando tirei o relatorio e confirmei, naõ sei se só a falta de contexto, porem não tarifou, no final do dia hoje as 19:30 vou tirar novametne o relatorio para ver se apos adicionar o contexto voltou a tarifar normlamente...

**Comment by dracohellgate** [comment]
No relatório bilheta normal, mais o crédito do cliente não baixa, ou baixa muito pouco...

**Comment by hiperphone** [comment]
Passa os prints de tela para o Magnus.. Para ele consegui ver... Sem os prints fica dificil ele localizar o problema

**Comment by dracohellgate** [comment]
Vou tirar print do credito inserido, do credito atual e do relatório extraído pelo sistema, vai dar para ver a discrepância, um exemplo, primeiro cliente credito de 2286 - atual 2105 - gasto no relatório 457
vou tentar tirar os print..

**Comment by magnussolution** [comment]
o contexto nao tem problema, mesmo sem contexto pega o contexto default do sip.conf que é billing.

Este nao é o lugar para discutir. é exclusivo para publicar problemas ja encontrados e com detalhes suficiente para ser replicado com facilidade. LEIA:
https://github.com/magnussolution/magnusbilling6/issues/56
