### ISSUE TITLE
Criar conta Via URL

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#105]
Criar conta via URL

http://199.241.187.158/mbilling/index.php/signup/add

Apliquei o comando informado

chown -R asterisk:asterisk /var/www/html/mbilling/assets

Mas apresenta erro: 

Internal Server Error

CAssetManager.basePath "/var/www/html/mbilling/assets" é inválido. Por favor, tanha certeza que o diretório existe e que o servidor Web possa escrever nele.

An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you.

2017-10-20 19:41:44

**Comment by magnussolution** [comment]
mkdir /var/www/html/mbilling/assets
chown -R asterisk:asterisk /var/www/html/mbilling/assets
