### ISSUE TITLE
Barra de Rolagem de da agenda em Campanha de torpedo de voz

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#106]
A barra de rolagem no item agenda da campanha em torpedo de voz não rolando para todas as agendas

![image](https://user-images.githubusercontent.com/30813258/31914492-a0d91190-b829-11e7-9050-cc4912d57c3f.png)

**Comment by magnussolution** [comment]
resolvido, 2 horas de trabalho
