### ISSUE TITLE
Listagem de Enquete resposta nao disponivel para o Usuario.

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#107]
O resultado do enquete resposta nao esta ficando disponivel para o usuario apenas para o master.

Segui print painel master
![image](https://user-images.githubusercontent.com/30813258/31916473-a419efde-b831-11e7-91ea-2206ed05496b.png)

Print painel usuario
![image](https://user-images.githubusercontent.com/30813258/31916485-b0e534d0-b831-11e7-86a1-641e9d6b0117.png)

**Comment by magnussolution** [comment]
resolvido. 30 minutos de trabalho
