### ISSUE TITLE
Filtro Lista de DIDs

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#109]
Não esta disponivel as funções de filtro dos numeros como na Versão MB 5

Sem possibilidade de filtrar os numeros de um DDD, filtrar apenas Ativos ou Inativas, Reservados ou não.

![image](https://user-images.githubusercontent.com/30813258/31969322-f6a16220-b8f2-11e7-8890-c59acbd230f2.png)

**Comment by magnussolution** [comment]
Resolvido + 1 hora de trabalho
