### ISSUE TITLE
URA

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#11]
Usando a versão 6.03 navegador chrome não consigo criar URA a pagina fica só rodando e não salva as configurações O teste foi feito em 3 computadores e redes diferentes e em nenhum deles salvou..

sip.hilario.net.br usuário e senha padrão.

**Comment by magnussolution** [comment]
https://cl.ly/1a3z0p261Q1m

nao consigue simular em minha instalação com a versão mais recente
