### ISSUE TITLE
Cancelamento de Serviço

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#110]
Criei um servidor e o mesmo foi ativado pelo usuario.
Tentei realizar o cancelamento do mesmo utilizando a conta do usuario e pelo adm. 
E o mesmo nao cancelou.

![image](https://user-images.githubusercontent.com/30813258/31970060-90311f46-b8f5-11e7-98f8-b022639b1c0e.png)
![image](https://user-images.githubusercontent.com/30813258/31970070-97bcb752-b8f5-11e7-9c5b-42597b912e92.png)

**Comment by magnussolution** [comment]
nao foi possível reproduzir o problema. Funciona perfeitamente em meu servidor com a ultima atualizacao
