### ISSUE TITLE
Ativar Gravação por compra de serviço

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#111]
Criei um serviço de gravação o mesmo foi ativado.
Em teste de ligação o mesmo nao gravou.
![image](https://user-images.githubusercontent.com/30813258/31970170-e7195760-b8f5-11e7-8192-d7d564630849.png)

[records_hiperphone.tar.gz](https://github.com/magnussolution/magnusbilling6/files/1412631/records_hiperphone.tar.gz)

**Comment by magnussolution** [comment]
Ao ativar o serviço com espaço em disco, a gravação nao é ativada automático, mas sim, abre p[ara o cliente a opção de ele mesmo ativar a gravação para as contas voip dele. Assim ele grava as que quiser.

Lembre-se sempre de atualizar, pois estou trabalhando bastante e fazendo umas 3 atualizações por dia
