### ISSUE TITLE
CallbackPro

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#112]
Fiz a ativação do CallbackPro, fiz a configuração como foi instruído no Webinar, quando logo no Putty e digito o verbose 25, apesar do sistema mostrar que está rodando o áudio, do outro lado fica mudo não se escuta nada, eu subi uns 10 tipos de áudio .GSM e nenhum deles sai som do outro lado, também testei vários codecs e nenhum deu para ouvir o tal áudio reproduzindo.

**Comment by magnussolution** [comment]
foi informado no webinar que o earlymedia nao funciona com qualquer numero. Tem que consultar com quem vc compra ver se esta ativo. Neste seu DID que vc testou provavelmente nao aceitam earlymedia
