### ISSUE TITLE
Criar Campanha pelo Painel do Usuario.

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#114]
Em tentativa de criar Campanha pelo Usuario. Apresenta mensagem que o ID do usuario nao pode ser vazio. 

![image](https://user-images.githubusercontent.com/30813258/32015138-f3d32400-b99e-11e7-882b-e3156bc1d414.png)

**Comment by magnussolution** [comment]
resolvido 1 hora de trabalho
