### ISSUE TITLE
Falha na Tarifação de Campanhas

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#115]
Boa tarde!

Magnus o envio de torpedo de voz esta com falha na tarifação.. Esta Tarifando de outra tabela diferente da setada cara a campanha e do usuario. A tabela que esta pegando não identifiquei qual é mas nao é a tabela setado no usuario muito menos a tabela setada para a campanha.

Nas ligações apresenta o tronco correto para a campanha.
![image](https://user-images.githubusercontent.com/30813258/32019255-59795854-b9ab-11e7-93ac-25db1c235a90.png)

Mas no extrato apresenta outro tronco com tarifa diferente da setada para a campanha
![image](https://user-images.githubusercontent.com/30813258/32019298-7f794bc2-b9ab-11e7-8bfa-e0433d220fec.png)

**Comment by magnussolution** [comment]
tinha problema com a seleção do plano, ele voltava para o plano do cliente ao editar a campanha, resolvi isso, atualize e teste para ver se continua.

**Comment by hiperphone** [comment]
No primeiro teste não alterei o Plano do cliente, mantive o Plano original do cliente. Esta pegando uma tabela que não foi selecionado para a campanha e nem pertence ao cliente.

Acabei de realizar atualização e realizei novo teste. O problema continua o mesmo.

**Comment by hiperphone** [comment]
Caso queira te dou acesso via TeamViewer a minha maquina e te mostro o que acontece... Ja identifiquei a tabela que esta pegando. Não tem nenhum vinculo com os usuarios que realizei o teste e não foi selecionada na campanha.

**Comment by everaldofw** [comment]
quando faz torpedos de voz o estado aparece zero e tarifa de outra tabela e ate o destino esta errado no torpedo de voz POIS PEGOU OUTRA TABELA, veja que o minha cidades é CURITIBANOS aparece corretamente em uma chamada normal e em torpedo de voz aparece com o nome de outra cidade tarifando e colocando o nome da outra tabela, totalmente errado, nem o prefixo existe na outra tabela.
![problema_01](https://user-images.githubusercontent.com/33166565/32127947-026df894-bb59-11e7-83e5-16fbd38ea7dd.jpg)
