### ISSUE TITLE
Falha em Campanha de SMS

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#116]
Criei um campanha de SMS e a mesma nao inicia o envio

Criei uma campanha de SMS para um usuario e a mesma nao se inciou. Realizei teste da campanha e me retornou como ok. Conforme imagem abaixo.
![image](https://user-images.githubusercontent.com/30813258/32021554-71de6608-b9b2-11e7-9cb0-f7ae2d07039f.png)

Se envio SMS unitario pela conta do Usuario e mesmo funciona.
![image](https://user-images.githubusercontent.com/30813258/32021633-a7daea74-b9b2-11e7-9995-0b12f5dabd64.png)

**Comment by magnussolution** [comment]
resolvido + 1 hora de trabalho
