### ISSUE TITLE
Aplicação de filtro na configuração de troncos

### ISSUE THREAD

**Issue by IvanMendes** [magnussolution/magnusbilling#117]
Ao aplicar um filtro para selecionar os troncos que quero alterar. Primeiro problema ocorre ao fazer uma alteração do tronco de backup. Com o filtro aplicado, na seleção dos troncos de backup, só aparecem os mesmos troncos do filtro. Deveria aparecer todos. Se for necessário escolher um tronco de backup que não esteja dentre os filtrados, tem que desaplicar o filtro.
Segundo problema ocorre ao selecionar um tronco de backup e tentar salvar a configuração, na primeira tentativa de salvar a aplicação do filtro se desfaz. Clicando novamente em salvar o novo tronco de backup é salvo, mas perde-se o filtro aplicado e o filtro pára de funcionar. Para voltar a funcionar tem que fechar os troncos e reabrir.
Cabe registrar que este meu magnusbilling 6.0.6 foi uma instalação nova na qual foi importada uma base de dados que estava em produção no MB 5. Toda a operação realizada com o suporte do Magnus.
Chrome 61.0.3163.100 (Versão oficial) 64 bits.

**Comment by magnussolution** [comment]
solucionado 30 min trabalho
