### ISSUE TITLE
Configuração de tronco de backup

### ISSUE THREAD

**Issue by IvanMendes** [magnussolution/magnusbilling#118]
Quando um tronco está configurado sem tronco de backup, ao tentar configurar um tronco de backup ele não aceita (não salva) e parece entrar em um loop. Somente fechando e reabrindo o painel de troncos, mas mesmo assim o tronco não é salvo. 
Cabe registrar que este meu magnusbilling 6.0.6 foi uma instalação nova na qual foi importada uma base de dados que estava em produção no MB 5. Toda a operação de instalação do MB6 e importação da base realizada com o suporte do Magnus.
Chrome 61.0.3163.100 (Versão oficial) 64 bits.

**Comment by magnussolution** [comment]
atualize e teste. Ja foi resolvido este problema
/var/www/html/mbilling/protected/command/update.sh
