### ISSUE TITLE
Cobrando em campanha do usuario que tem vinculo com a agenda, sendo que deveria cobrar do usuario que esta enviando a campanha.

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#119]
No MB 5 eu poderia ter uma agenda para o usuario 1515 e utilizar em uma campanha para o usuario 2020.

Já no MB 6 se eu preparar uma campanha pelo master para o usuario 2020 e utilizar uma agenda do usuario 1515 , o MB 6 esta cobrando pela campanha o usuario dono da agenda que este exemplo seria o 1515 , não do usuario dono da campanha como seria o certo, debitar do usuario 2020

**Comment by magnussolution** [comment]
provavelmente é a mesma questão do outro Issue, que acabou de ser resolvido
