### ISSUE TITLE
Numero não encontrado

### ISSUE THREAD

**Issue by jeanpassos** [magnussolution/magnusbilling#12]
Mesmo estando tudo certo na planos, tarifas e prefixo quando faz a ligação retorno da mensagem: não pode ser encontrado.

No console:

Conectado ao Asterisk 14.6.0 atualmente em execução em telefonia-backup (pid = 727) 
== Gerenciador 'magnus' logado a partir de 127.0.0.1 
== Gerenciador 'magnus' desconectado de 127.0.0.1 
== Gerenciador 'magnus' desconectado de 127.0.0.1 
== Manager 'magnus' logado a partir de 127.0.0.1 
== Usando SIP RTP CoS mark 5 
- Executando [32233098 @ faturamento: 1] AGI ("SIP / 1000-0000001d", "" / var / www / Html / m billing / agi.php "") na nova pilha 
- Lançado o script AGI /var/www/html/mbilling/agi.php 
> "/var/www/html/mbilling/agi.php": 
> "/ Var / www / html / mbilling / agi.php ": Inicie o MBING AGI 
>" /var/www/html/mbilling/agi.php ":AUTENTICAÇÃO POR ACCOUNTCODE: Jean 
"/var/www/html/mbilling/agi.php": 554832233098 
> "/var/www/html/mbilling/agi.php": USERNAME = Jean DESTINATION = 55483223309 8 PLAN = 1 CREDIT = 5.0000 
- "/var/www/html/mbilling/agi.php": o número 554832233098, não existe no plano 1 
- "/var/www/html/mbilling/agi.php": prepaid-dest-unreachable 
> 0x7fbba8fccf90 - Probação passada - configurando o endereço de origem RTP para 179. 223.144.103: 5921 
- <SIP / 1000-0000001d> Reproduzindo 'prepaid-dest-unreachable.gsm' (escape_digits = #) (sample_offset 0) (idioma 'Br ') 
- <SIP / 1000-0000001d> AGI Script /var/www/html/mbilling/agi.php completado, r eturning 4 
== Extensão Spawn (faturamento, 32233098, 1) saiu não-zero em' SIP / 1000-0000001 d '

**Comment by magnussolution** [comment]
#7 Resolvido. atualize seu mbilling 6 e logo edite ou adicione um prefixo novo

**Comment by hilariovoip** [comment]
A mensagem de numero nao encontrado sumiu agora mas a chamada esta sendo finalizada e um erro aparece no log em anexo.
![erro2](https://user-images.githubusercontent.com/30841526/29137648-6e103fd8-7d17-11e7-9840-6ad572323ee1.PNG)

**Comment by hilariovoip** [comment]
resolvido agora esta funcionando

**Comment by magnussolution** [comment]
por favor para manter ordenado somente um problema em cada pedido
