### ISSUE TITLE
No outbound Calls

### ISSUE THREAD

**Issue by ajtel** [magnussolution/magnusbilling#120]
Connected to Asterisk 14.6.2 currently running on camila (pid = 19298)
  == Using SIP RTP CoS mark 5
       > 0x7f58d4013970 -- Strict RTP learning after remote address set to: 1******5:8000
    -- Executing [52*******8@billing:1] AGI("SIP/A*********O-00000007", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php":
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
       > "/var/www/html/mbilling/agi.php":  get_agi_request_parameter = Line is ringing ; AJTELMEXICO ; SIP/AJTELMEXICO-00000007 ; 1509046962.14 ; AJT****ICO ; 5******8
       > "/var/www/html/mbilling/agi.php": checkIfIsDidCall 52********788
       > "/var/www/html/mbilling/agi.php": CALL TO PSTN
       > "/var/www/html/mbilling/agi.php": AuthenticateUser A*****CO
       > "/var/www/html/mbilling/agi.php": Try accountcode authentication AJ*****CO
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:A***CO
       > "/var/www/html/mbilling/agi.php": use_dnid:1 && len_dnid:(12 || len_exten:12 ) && (try_num:0)
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 52*8****
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 52*****8
       > "/var/www/html/mbilling/agi.php": Grab : Replacement:  Phone Before: 52*****88
       > "/var/www/html/mbilling/agi.php": Phone After translation: 52*****8
 "/var/www/html/mbilling/agi.php": 52*****88
       > "/var/www/html/mbilling/agi.php": USERNAME=AJ****O DESTINATION=525*****88 PLAN=2 CREDIT=2.0000
       > "/var/www/html/mbilling/agi.php": SELECT lcrtype, pkg_plan.id AS id_plan, pkg_prefix.prefix AS dialprefix,
       > "/var/www/html/mbilling/agi.php":                              pkg_plan.name, pkg_rate.id_prefix, pkg_rate.id AS id_rate, buyrate,  buyrateinitblock buyrateinitblock,
       > "/var/www/html/mbilling/agi.php":                              buyrateincrement, rateinitial, initblock, billingblock, connectcharge, disconnectcharge disconnectcharge,
       > "/var/www/html/mbilling/agi.php":                              pkg_rate.id_trunk AS id_trunk, pkg_trunk.trunkprefix AS rc_trunkprefix, pkg_trunk.directmedia AS rc_directmedia,
       > "/var/www/html/mbilling/agi.php":                              pkg_trunk.providertech AS rc_providertech ,pkg_trunk.providerip AS rc_providerip,
       > "/var/www/html/mbilling/agi.php":                              pkg_trunk.removeprefix AS rc_removeprefix, pkg_trunk.failover_trunk AS rt_failover_trunk,
       > "/var/www/html/mbilling/agi.php":                              pkg_trunk.addparameter AS rt_addparameter_trunk, pkg_trunk.status, pkg_trunk.inuse, pkg_trunk.maxuse,
       > "/var/www/html/mbilling/agi.php":                              pkg_trunk.allow_error,pkg_trunk.if_max_use, pkg_rate.additional_grace AS additional_grace, minimal_time_charge,
       > "/var/www/html/mbilling/agi.php":                              minimal_time_buy, pkg_trunk.link_sms, pkg_trunk.user user, pkg_trunk.secret, package_offer ,
       > "/var/www/html/mbilling/agi.php":                              pkg_trunk.id_provider, pkg_provider.credit_control, pkg_provider.credit
       > "/var/www/html/mbilling/agi.php":                              FROM pkg_plan
       > "/var/www/html/mbilling/agi.php":                              LEFT JOIN pkg_rate ON pkg_plan.id = pkg_rate.id_plan
       > "/var/www/html/mbilling/agi.php":                              LEFT JOIN pkg_trunk AS pkg_trunk ON pkg_trunk.id = pkg_rate.id_trunk
       > "/var/www/html/mbilling/agi.php":                              LEFT JOIN pkg_prefix ON pkg_rate.id_prefix = pkg_prefix.id
       > "/var/www/html/mbilling/agi.php":                              LEFT JOIN pkg_provider ON pkg_trunk.id_provider = pkg_provider.id
       > "/var/www/html/mbilling/agi.php":                              WHERE pkg_plan.id=2 AND pkg_rate.status = 1 AND ((prefix='5255***078' OR prefix='52**9*7' OR prefix='525559890' OR prefix='5255***9' OR prefix='5255598' OR prefix='525559' OR prefix='52555' OR prefix='5255' OR prefix='525' OR prefix='52' OR prefix='5' ) OR (prefix LIKE '&_%' ESCAPE '&' AND '52********8'
       > "/var/www/html/mbilling/agi.php":                          REGEXP REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT('^', prefix, '$'),
       > "/var/www/html/mbilling/agi.php":                          'X', '[0-9]'), 'Z', '[1-9]'), 'N', '[2-9]'), '.', '.+'), '_', '')))
       > "/var/www/html/mbilling/agi.php":                              ORDER BY LENGTH( prefix ) DESC
    -- "/var/www/html/mbilling/agi.php": The number 52555*****8, no exist in the plan 2
    -- "/var/www/html/mbilling/agi.php": Send Congestion prepaid-dest-unreachable
    -- AGI Script Executing Application: (congestion) Options: (Congestion)
    -- <SIP/A******O-00000007>AGI Script /var/www/html/mbilling/agi.php completed, returning 4
  == Spawn extension (billing, 52555989****, 1) exited non-zero on 'SIP/A*****O-00000007'
camila*CLI>

**Comment by magnussolution** [comment]
you are calling to number 528. Who is 528???? this number is not a SipAccount and you not have prefix to this destination.
