### ISSUE TITLE
Campanha Torpedo de Voz - Números nunca ficam Pendentes - Se não estiver ninguém em casa toca infinitamente até desativar a campanha.

### ISSUE THREAD

**Issue by everaldofw** [magnussolution/magnusbilling#123]
Em uma campanha de torpedos de voz, o sistema vai discando, mas caso algum número o telefone estiver ocupado, ou não atender por a pessoa não estar em casa, o status desse número nunca fica PENDENTE. Sempre fica ATIVO. 

Se estiver ocupado, ficando ATIVO quando desocupar  o sistema vai voltar a chamada nesse número pois no sistema consta como ATIVO, 

Se a pessoa não estiver em casa, estiver viajando, vai ficar tocando infinitamente, e usando processamento da máquina. a cada 30 ou 40 segundo ele volta no telefone, pois o mesmo fica sempre como ATIVO. 

Nos testes que fiz em nenhuma hipótese ficou como pendente. Ou fica ATIVO ou como ATENDIDO.

"NÃO NECESSITA DE IMAGEM ESSE POST."

**Comment by magnussolution** [comment]
resolvido + 1 hora de trabalho
