### ISSUE TITLE
Cobrando em campanha do usuario que tem vinculo com a agenda, sendo que deveria cobrar do usuario que esta enviando a campanha.

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#124]
Boa tarde!

Atualizei agora a pouco e retornei a testar campanhas de torpedo de voz.

Configurando uma campanha pelo MASTER onde o dono da campanha e dono da agenda é o mesmo usuario tarifa corretamente.

Mas se criar uma campanha e utilizar a agenda de outro usuario, esta campanha sera debitada do saldo do dono da agenda e nao do dono da campanha.

Esta utilizando como parâmetro para debitar a campanha de torpedo de voz o usuario na qual a agenda foi criada, nao no usuario para o qual a campanha foi criada como deveria ser.

**Comment by magnussolution** [comment]
resolvido
