### ISSUE TITLE
Configurar recebimentos via Mercado Pago - Mercado Livre

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#125]
boa tarde!

Consegui criar usuario e token no Mercado Livre para recebimentos de pagamento.
Realizei teste e funcionou tudo ok com relação ao pagamento.

Mas precisaria da URL de resposta para receber o aviso do Mercado Pago que o cliente finalizou o pagamento.

Qual URL devo cadastrar na tela abaixo
![image](https://user-images.githubusercontent.com/30813258/32139061-4b6935c0-bc1e-11e7-98e6-b88de8edfbfb.png)

Caso nao seja nesta tela que devo cadastrar poderia me passar em qual tela seria ?

**Comment by magnussolution** [comment]
http://ip/billing/index.php/mercadoPago
