### ISSUE TITLE
Padrao URL do SMS

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#126]
bom dia!

Magnus porque voce não retornar ao padrao da URL de SMS utilizado no MBilling 5 ?
Conversando com algumas pessoas que instalaram o MBilling 6 para teste, relataram que retornaram para o MBilling 5 porque precisariam alterar em todos os clientes que utilizam URL.

Retorna para o padrao MBilling 5 , pois acredito que alguns voltaram a migrar para o MBilling 6

http://sip3.hiperphone.com.br/hiperphone/index.php/smsSend/?username=xxxxxxxxx&password=xxxxxxxx&number=%number%&text=%texto%

Apenas sugestão.

**Comment by magnussolution** [comment]
impossível
