### ISSUE TITLE
expiration day

### ISSUE THREAD

**Issue by ajtel** [magnussolution/magnusbilling#127]
the expiration system does not work it always sasy plan expired in a record

**Comment by magnussolution** [comment]
Send more details

**Comment by ajtel** [comment]
If i activate Expiration, system response YOUR ACCOUNT has expired, INCLUIDIN if i put dec 31,2017

**Comment by magnussolution** [comment]
please read https://github.com/magnussolution/magnusbilling6/issues/57

**Comment by ajtel** [comment]
6.0.6 MBilling Version
16 Cores
16 Gb Ram
Centos 7

**Comment by magnussolution** [comment]
fix issue. thanks

We need help to continue support MagnusBilling in English. Please make your donate
https://www.magnusbilling.com/donate.php

Best regards

**Comment by ajtel** [comment]
i will donate now

**Comment by magnussolution** [comment]
thanks
