### ISSUE TITLE
Metodos de Pagamentos - Inserção automatica de crédito

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#128]
bom dia!

Apos a realização de compras de clientes o credito nao esta sendo inserido automaticamente. 
Houve alguma mudança no API ?

Paypal = http://199.241.187.158/hiperphone/index.php/paypal
PagSeguro  = http://199.241.187.158/hiperphone/index.php/pagSeguro
Ambos já eram utilizados na versão 5 sem nenhum problema..

Testei tambem o MercadoPago conforme API que voce envio.
 http://199.241.187.158/hiperphone/index.php/mercadoPago
Tambem não funcionou.

**Comment by magnussolution** [comment]
resolvido, teste por favor 1 hora de trabalho
