### ISSUE TITLE
PROVISIONAMENTO DE LYNKSYS NAO FUNCIONA

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#129]
Bom dia! O provisionamento não esta ocorrendo aplicando as configuração ensinadas ate em video, segue os passos a qual deveríamos seguir!

http://meuip/mbilling/index.php/ata?mac=$MAC  no campo rules

Se precisar posso colocar uma ata online para voce efetuar testes!

E uma dica poderia acrescentar mais provisionamento tais como grandstream, polycoom que sao equipamentos melhores e mais usados!

Obrigado!

**Comment by magnussolution** [comment]
aguardo um Linksys para poder fazer testes

**Comment by RodrigoRDC17** [comment]
vou te passar o mac e serial no whatsap e vc me passa o link para colocar no rules

**Comment by RodrigoRDC17** [comment]
Te enviei o mac e serial pelo zap

**Comment by magnussolution** [comment]
solucionado 2 horas de trabalho

**Comment by RodrigoRDC17** [comment]
Bom dia Adilson! funcionou usando a mesma linha de comando? ou criou outra?

Pode me passar um exemplo de linha de comando para o rules?

**Comment by RodrigoRDC17** [comment]
Digo pq pelo provisionamento ele nao pegou o ip para ocorrer o registro

**Comment by RodrigoRDC17** [comment]
Resolvido!
