### ISSUE TITLE
Tronco nao autentica

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#13]
Tronco não quer autenticar por usuário senha e IP, no log quando quando marco ativo da a mensagem abaixo:

![44444](https://user-images.githubusercontent.com/30841526/29235858-85b46eb6-7ed9-11e7-8e93-514b7df00e30.JPG)

dominio: hilario.net.br

**Comment by magnussolution** [comment]
mando o resultado de 

sip show registry

**Comment by hilariovoip** [comment]
Eu digo o tronco, o ramal autentica mas o tronco não quer autenticar.

**Comment by magnussolution** [comment]
Desculpe, mas nao entendo. Por favor, made LOG. 

relatos de BUG sem dados e LOGs serão desconsiderados 

mande o resultado do comando

sip show registry

**Comment by hilariovoip** [comment]
Era problemas com firewall após limpar a tabela aqui registrou
