### ISSUE TITLE
Não Gerar Arquivo .CSV em Revenda

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#130]
boa tarde!

Em teste na revenda tentei exportar para CSV o extrato de ligações e apresentou o seguinte erro.
Este erro ocorre apenas na REVENDA

![image](https://user-images.githubusercontent.com/30813258/32297673-0194b4c6-bf37-11e7-9603-89b9c722d7d3.png)

**Comment by magnussolution** [comment]
por favor testar. 2 horas de trabalho
