### ISSUE TITLE
Error CallShop

### ISSUE THREAD

**Issue by fernandoasv** [magnussolution/magnusbilling#131]
Buenas tardes,

Tengo un servidor con Centos 7.  En el módulo CallShop no se están tarificando todas llamadas, pero en el CDR si se visualizan todas las llamadas realizadas.  El conteo del tiempo de cada llamada está iniciando cuando la llamada inicia a timbrar o repicar, en versión 5 el tiempo iniciaba a contar desde que se contestaba la llamada, este error se puede observar tanto en el menú de CallShop como en el menú de llamadas online.

El error descrito anteriormente se está presentando tanto en una instalación nueva de MBilling 6 como en una actualización de MBilling 5 a MBilling 6.

Gracias.

**Comment by magnussolution** [comment]
una llamada solo se inicia el tiempo cuando Asteriskl recibe el Answer del troncal, verifique con tu provedor

**Comment by fernandoasv** [comment]
Con MBilling 5 funciona perfecto la tarificación con los mismos proveedores que tengo en pruebas en Mbilling 6.  En MBilling 5 tan pronto la llamada es contestada, se inicia la tarificación, en MBilling 6 se inicia la tarificación cuando la llamada empieza a repicar.

Gracias.
