### ISSUE TITLE
SMS não aparece no extrato do Usuario.

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#132]
SMS enviado por usuario nao aparece no extrato do mesmo

![image](https://user-images.githubusercontent.com/30813258/32326891-add38fe4-bfbb-11e7-8ad6-4ca5a040a6bb.png)

No extrato do Master aparece
![image](https://user-images.githubusercontent.com/30813258/32327044-422943f0-bfbc-11e7-9cd5-b501b85ee801.png)

Sendo que o usuario que envio o SMS no extrato MASTER aparece no campo CALLERID e no campo USUARIO aparece ROOT.... Talvez por isso nao aparece no extrato do USUARIO.

Esta tarifando corretamente... Apenas nao aparece no extrato

**Comment by magnussolution** [comment]
resolvido
