### ISSUE TITLE
Agents can't view Plans

### ISSUE THREAD

**Issue by gallysoft** [magnussolution/magnusbilling#134]
When a new agent go to Rates/Plans and create a new Plan, it does not appear in the list.
In Tariffs, instead, one line appears correctly for each prefix, as per plan applied to the reseller.

**Comment by gallysoft** [comment]
I also add that you can add two Plans with the same name but still do not appear in Rates/Plans (logging in as agent/reseller).

**Comment by magnussolution** [comment]
hello. Fixed this issue.

Remember, we need your support to continue work in this project https://www.magnusbilling.com/donate.php

best regards
