### ISSUE TITLE
Filtro em Destino de DIDs

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#135]
Verifiquei que em quase todo o sistema existe filtros para escolha seleção de  usuarios e outros itens, mas em Destino de DIDs ainda esta com  combobox. Foi esquecimento ou não haverá alteração ?

![image](https://user-images.githubusercontent.com/30813258/32399650-dfb3db6c-c0de-11e7-9b4a-88d84bc3ed2d.png)

**Comment by magnussolution** [comment]
nao tera alteraçao
