### ISSUE TITLE
PROVISIONAMENTO DE ATA

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#137]
Boa noite! Fizemos o teste no provisicionamento e o mesmo funcionou!

Porem o anti reset nao esta ativando no equipamento mesmo habilitando o mesmo!

é resetado facil com o comando 73738#1

**Comment by magnussolution** [comment]
resolvido, teste

**Comment by RodrigoRDC17** [comment]
ok funcionou, porem se o usuario for avançado consegue resetar a mesma!
