### ISSUE TITLE
Erro Jscript

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#138]
Ao logar no sistema com o Google Chrome debugando erros ele informa o seguinte erro:
ReferenceError: Help is not defined
 /mbilling/resources/help/help.js:1

**Comment by magnussolution** [comment]
algo em sua instalação pois o arquivo mbilling/resources/help/help.js existe no projeto.

https://github.com/magnussolution/magnusbilling6/blob/master/resources/help/help.js

verifique se ele esta no seu servidor

**Comment by rfminelli** [comment]
Sim o arquivo está no servidor. 
Pela msg parece variável não definida.
