### ISSUE TITLE
The number xxx, no exist in the plan 1

### ISSUE THREAD

**Issue by gallysoft** [magnussolution/magnusbilling#139]
Hi.
If a Reseller creates one Client, the Client can't call.
Doing AGI debug I see:

> <SIP/39041347439xxxx098xxxx-00000052>AGI Rx << VERBOSE "" 5
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "Start MBilling AGI" 5
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << CHANNEL STATUS SIP/39041098xxxx-00000052
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=4
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE " get_agi_request_parameter = Line is ringing ; 39041098xxxx ; SIP/39041098xxxx-00000052 ; 1509972089.163 ; 39041098xxxx ; 347439xxxx" 15
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << GET VARIABLE CIDCALLBACK
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << GET VARIABLE PHONENUMBER_ID
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << GET VARIABLE SPY
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << GET VARIABLE MEMBERNAME
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << GET VARIABLE QUEUEPOSITION
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "checkIfIsDidCall 347439xxxx" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << GET VARIABLE SECCALL
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "CALL TO PSTN" 15
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "AuthenticateUser 39041098xxxx" 15
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "Try accountcode authentication 39041098xxxx" 15
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "AUTHENTICATION BY ACCOUNTCODE:39041098xxxx" 6
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "Reseller id_Plan 4, user id_plan 1" 6
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << SET VARIABLE CHANNEL(language) "en"
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << CHANNEL STATUS SIP/39041098xxxx-00000052
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=4
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "use_dnid:1 && len_dnid:(10 || len_exten:10 ) && (try_num:0)" 15
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "USE_DNID DESTINATION -> 347439xxxx" 10
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "REMOVE INTERNACIONAL PREFIX -> 347439xxxx" 10
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "Phone After translation: 39347439xxxx" 10
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "39347439xxxx" 1
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "USERNAME=39041098xxxx DESTINATION=39347439xxxx PLAN=1 CREDIT=10.0000" 6
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "SELECT lcrtype, pkg_plan.id AS id_plan, pkg_prefix.prefix AS dialprefix," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_plan.name, pkg_rate.id_prefix, pkg_rate.id AS id_rate, buyrate,  buyrateinitblock buyrateinitblock," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                buyrateincrement, rateinitial, initblock, billingblock, connectcharge, disconnectcharge disconnectcharge," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_rate.id_trunk AS id_trunk, pkg_trunk.trunkprefix AS rc_trunkprefix, pkg_trunk.directmedia AS rc_directmedia," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_trunk.providertech AS rc_providertech ,pkg_trunk.providerip AS rc_providerip," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_trunk.removeprefix AS rc_removeprefix, pkg_trunk.failover_trunk AS rt_failover_trunk," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_trunk.addparameter AS rt_addparameter_trunk, pkg_trunk.status, pkg_trunk.inuse, pkg_trunk.maxuse," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_trunk.allow_error,pkg_trunk.if_max_use, pkg_rate.additional_grace AS additional_grace, minimal_time_charge," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                minimal_time_buy, pkg_trunk.link_sms, pkg_trunk.user user, pkg_trunk.secret, package_offer ," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                pkg_trunk.id_provider, pkg_provider.credit_control, pkg_provider.credit" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                FROM pkg_plan" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                LEFT JOIN pkg_rate ON pkg_plan.id = pkg_rate.id_plan" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                LEFT JOIN pkg_trunk AS pkg_trunk ON pkg_trunk.id = pkg_rate.id_trunk" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                LEFT JOIN pkg_prefix ON pkg_rate.id_prefix = pkg_prefix.id" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                LEFT JOIN pkg_provider ON pkg_trunk.id_provider = pkg_provider.id" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                WHERE pkg_plan.id=1 AND pkg_rate.status = 1 AND   (prefix LIKE '&_%' ESCAPE '&' AND '39347439xxxx'" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                        REGEXP REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT('^', prefix, '$')," 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                        'X', '[0-9]'), 'Z', '[1-9]'), 'N', '[2-9]'), '.', '.+'), '_', ''))" 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "                ORDER BY LENGTH( prefix ) DESC " 25
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "The number 39347439xxxx, no exist in the plan 1" 3
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << VERBOSE "prepaid-dest-unreachable" 3
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-00000052>AGI Rx << ANSWER
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << ANSWER
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-00000052>AGI Rx << STREAM FILE prepaid-dest-unreachable "#" 0
> <SIP/39041098xxxx-00000052>AGI Tx >> 200 result=-1 endpos=0

The Client (39041098xxxx in the example) correctly see in Rates/Tariff the tariff (see screenshot).

Thank you!

P.S.: I had only modified protected/components/AGI/Magnus.php in this mode:
`
    public function number_translation($agi, $destination)
    {
		if (substr($destination, 0, 2) == "00")
			$destination = substr($destination, 2);
		else 
			$destination = "39" .$destination;
    	 
    	
        $agi->verbose("Phone After translation: $destination", 10);
        $this->destination = Portabilidade::getDestination($destination, $this->id_plan);
    }
`

![schermata 2017-11-06 alle 13 45 56](https://user-images.githubusercontent.com/2563695/32441670-e7b4dc6e-c2f8-11e7-9a72-208e480e0126.png)

**Comment by magnussolution** [comment]
check if you have prefix 393 in prefix menu

**Comment by gallysoft** [comment]
Yes, it exists. 

![91c2445e-36ee-4ec1-b4ee-7f9985efcb8a](https://user-images.githubusercontent.com/2563695/32460075-d731594c-c331-11e7-8782-32c4436ce723.png)

**Comment by magnussolution** [comment]
try add another any prefix, to mbilling re generate the asterisk prefixes

**Comment by gallysoft** [comment]
The problem has disappeared by creating a new Plan.
