### ISSUE TITLE
Credito em Duplicidade

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#14]
boa noite!

Em teste em recarga, realizei uma recarga de R$ 300,00, mas na informação de pagamento coloquei como NAO. O credito foi liberado normalmente para o assinante.  Mas quando alterei a informação de pagamento de NAO para SIM o credito foi inserido outro vez para o assinante.

Estou usando no teste http://sip.hilario.net.br/mbilling/
usuario: root
senha: magnus

Acesso cedido por membr do grupo magnus no Whatsapp
Não tenho como verificar se houve problema na instalação

Hiperphone

**Comment by magnussolution** [comment]
Resolvido no commmit https://github.com/magnussolution/magnusbilling6/commit/eb426218fd96fc7bb95fe07964b570dbbe64e678
