### ISSUE TITLE
Cost calculation error between Agent and Client

### ISSUE THREAD

**Issue by gallysoft** [magnussolution/magnusbilling#140]
The case: Agent with Tariff Platinum, Client with Tariff Home.
The costs are:
![schermata 2017-11-06 alle 14 13 01](https://user-images.githubusercontent.com/2563695/32442714-a8abe6a8-c2fc-11e7-890d-b14e46c038af.png)

When client call, the Agent and Client credit is always reduced by the same amount.

This is AGI debug:

> <SIP/39041098xxxx-0000000b>AGI Rx << EXEC DIAL sip/TWT/0039347439xxxx,60,L(32006000:61000:30000)
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=-1
> <SIP/39041098xxxx-0000000b>AGI Rx << GET VARIABLE ANSWEREDTIME
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1 (61)
> <SIP/39041098xxxx-0000000b>AGI Rx << GET VARIABLE DIALSTATUS
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1 (ANSWER)
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "USED TARIFF=0" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "Update System" 6
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "CALCULCOST: K=0 - CALLDURATION:61 - freetimetocall_used=0" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "CALCULCOST: 1. COST: $cost = (61/60) * 0.0187 " 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "CALCULCOST: K=0 - BUYCOST:0.017283333333333 - SELLING COST:0.019012" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "$this->lastbuycost = 0.017283333333333" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "$this->lastcost = 0.019012" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "Sessiontime61" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "CALL: used tariff K=0 - (sessiontime=61 :: dialstatus=ANSWER)" 10
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "1 0.019012+0 = 0.019012" 25
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << GET VARIABLE IDPREFIX
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "$MAGNUS->id_agent2 39347439xxxx - 39347439xxxx - 61 - 0.019012" 1
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "NOT FOUND AGENT TARRIF, USE AGENT COST PRICE" 1
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "Sellratecost_customer: 0.019012" 15
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "Update credit Agent 3psystem.srl, 0.019012" 15
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "Update credit customer Agent 39041098xxxx, 0.019012" 6
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
> <SIP/39041098xxxx-0000000b>AGI Rx << GET VARIABLE IDCALLBACK
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=0
> <SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "Insert call on CDR" 1
> <SIP/39041098xxxx-0000000b>AGI Tx >> 200 result=1
>

**Comment by magnussolution** [comment]
<SIP/39041098xxxx-0000000b>AGI Rx << VERBOSE "NOT FOUND AGENT TARRIF, USE AGENT COST PRICE" 1

check if your agent create a plan and set in his customer.

**Comment by gallysoft** [comment]
I've done some tests. The calculation is correct if the plan is assigned from Reseller. If the admin associate a plan to a Client of a Reseller the calculation is not correct.

**Comment by magnussolution** [comment]
Admin not should not change agent customers.
