### ISSUE TITLE
Erro Fail2Ban - CentOS 7

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#141]
Bom dia Magnus, gostaria de relatar um erro na instalação do fail2ban.
O mesmo instala normalmente mas não é inicializado.
Só consegui corrigir o erro fazendo o seguinte procedimento.
No script de instalação antes das linhas:
     mkdir /var/run/fail2ban/
    asterisk -rx "module reload logger"
    systemctl enable fail2ban 
    systemctl restart fail2ban 
    iptables -L -v

tive de fazer o seguinte:
cp -Rf /tmp/fail2ban/build/fail2ban.service /usr/lib/systemd/system/fail2ban.service

e somente depois executar o comando
mkdir /var/run/fail2ban/
asterisk -rx "module reload logger"
systemctl enable fail2ban.service
systemctl restart fail2ban.service
 iptables -L -v

***Obs.: Repare que antes era:
     systemctl enable fail2ban 
     systemctl restart fail2ban

e passou a ser:
     systemctl enable fail2ban.service
     systemctl restart fail2ban.service

Após isso ficou td 100%.

Só para informação fiz o teste 8 vezes em VM com CENTOS 7, um membro não apoiador também me relatou esse erro em privado.

**Comment by magnussolution** [comment]
proponha a modificação aqui no GitHub mesmo

https://github.com/magnussolution/magnusbilling6/blob/master/script/install.sh

leia https://www.magnusbilling.com/forum/mbilling/portugues/como-contribuir-com-o-projeto-mbilling-no-github-2223.html
