### ISSUE TITLE
Modulo Backup

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#142]
Modulo Backup não ativo por padrão.
Configurações do BD na tabela pkg_module id, text, module, icon_cls, id_module.
Configurações das permissões do Administrador, Agent e Client.
Após adicionado aparece no menu, pode-se Criar, Importar e Download.

**Opção Criar:**
Mas ao tentar criar ele informa as mensagens em inglês (mesmo estando setado para Pt-BR), faz o procedimento como se estive-se criando mas o mesmo não cria o arquivo de backup em /usr/local/src/magnus/backup .
Já se eu der o comando pelo console:
php /var/www/html/mbilling/cron.php Backup
o arquivo é criado normalmente.
Acredito que talvez seja problema se permissão.
Segue Log
tail -f protected/runtime/cron.log
[error] [php] fopen(/var/run/magnus/backupPid.php): failed to open stream: Permission denied (/var/www/html/mbilling/protected/components/Process.php:48)
Stack trace:
#0 /var/www/html/mbilling/protected/components/ConsoleCommand.php(45): isActive()
#1 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(66): BackupCommand->init()
#2 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run()
#3 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#4 /var/www/html/mbilling/cron.php(31): CConsoleApplication->run()

**Opção Importar:**
Se crio o backup manualmente ou o sistema pelo cron, mesmo selecionando o arquivo e clicando em importar o mesmo não importa os dados para o BD.

**Opção Download:**
Funcionando corretamente.

Permissão:
ll /usr/local/src/magnus/
drwxr-xr-x. 2 asterisk asterisk 6 Nov  6 14:25 backup
drwxr-xr-x. 2 asterisk asterisk 6 Nov  6 09:54 monitor
drwxr-xr-x. 2 asterisk asterisk 6 Nov  6 09:54 sounds

ll /var/run/magnus/
-rw-r--r-- 1 root root 21 Nov  6 14:39 backupPid.php
-rw-r--r-- 1 root root 21 Nov  6 15:14 callchartPid.php
-rw-r--r-- 1 root root 21 Nov  6 15:14 massivecallPid.php
-rw-r--r-- 1 root root 21 Nov  6 15:01 notifyclientPid.php
-rw-r--r-- 1 root root 21 Nov  6 15:14 smsPid.php

Lembrando que eu já tinha o modulo Backup comprado no Magnus Billing v5.

**Comment by magnussolution** [comment]
abandonei este modulo por falta de apoio ao projeto. Por isso que nao foi adicionado.

**Comment by rfminelli** [comment]
Erro de permissão corrigido no commit Import Backup
https://github.com/magnussolution/magnusbilling6/commit/35c03b84942ed727ec2d523df57f0e004d4d1544
