### ISSUE TITLE
Atualização em lotes de tarifas não abre aba ao lado.

### ISSUE THREAD

**Issue by andreljp** [magnussolution/magnusbilling#143]
![tarifas](https://user-images.githubusercontent.com/22567802/32467716-6aeb50b4-c32a-11e7-9fb9-0f31cbc6b6c7.png)
Ao tentar atualizar tarifas em lote, não abre aba ao lado.

**Comment by andreljp** [comment]
O erro só acontece no tema antigo, mudei o tema para NEPTUNE e deu certo.

**Comment by magnussolution** [comment]
ola, nos meus testes funcionou com todos os temas

![screen shot 2017-11-07 at 09 31 53](https://user-images.githubusercontent.com/17835020/32491641-912d1fa4-c39e-11e7-9c19-5d5bd43b701c.png)
