### ISSUE TITLE
Criar Usuário

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#145]
Ao criar um novo usuário o mesmo é criado sem problema. Ao ver a conta voip criada automaticamente pelo sistema com os dados do usuário, a mesma é criada sem o contexto "billing".

**Comment by magnussolution** [comment]
Solucionado.

**Comment by rfminelli** [comment]
Após atualizar o Mv6 com o seguinte comando:
/var/www/html/mbilling/protected/commands/update.sh

Agora ao criar o usuário ele não está criando a conta voip.
Vi que no commit vc adicionou na linha 265:
$modelSip->videosupport = 'billing';
O correto seia 
$modelSip->context = 'billing';
Após eu efetuar a alteração manualmente no sistema o MB voltou a criar a conta voip.
