### ISSUE TITLE
Destino DID

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#146]
No Menu Destino DID ao editar um DID eu remove a URA atual e qd seleciono a nova URA e mando salvar o mesmo parece salvar mas não salva. Mesmo fechando a aba ou dando reload e abrindo para conferir continua a URA que estava antes da alteração.
Mas seu eu excluir a URA antiga selecionar outra opção tipo SIP e depois voltar a selecionar URA e por a nova URA ai ele salva corretamente.

**Comment by magnussolution** [comment]
por favor teste o ultimo commit

**Comment by rfminelli** [comment]
Testei 4 vezes, quando o MB não duplica o registro da ura ele da o seguinte erro
"NetworkError: 500 Internal Server Error - http://x.x.x.x/mbilling/index.php/diddestination/save?_dc=1510164809358"

**Comment by magnussolution** [comment]
grave um video, pois nao consigo simular o problema

**Comment by rfminelli** [comment]
Só para documentação, o video foi enviado diretamente para o Magnus devido aos dados que aparecem no mesmo.

**Comment by magnussolution** [comment]
nao recebi o video
