### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gallysoft** [magnussolution/magnusbilling#147]
I have translated locale EN to Italian.
Is it possible to apply?

Translated files are available on my Fork in resources/locale.

**Comment by magnussolution** [comment]
hello.

Send us the it.js

and you need translate php file

https://github.com/magnussolution/magnusbilling6/blob/master/resources/locale/php/pt_BR/yii.php

**Comment by gallysoft** [comment]
Hi.
https://github.com/gallysoft/magnusbilling6/blob/master/resources/locale/it.js
https://github.com/gallysoft/magnusbilling6/blob/master/resources/locale/php/it/yii.php

**Comment by magnussolution** [comment]
language added in commit https://github.com/magnussolution/magnusbilling6/commit/7ea8cf4ac44ded3053297588a4d276d24112307b
