### ISSUE TITLE
Codec g729

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#148]
Ao criar conta um novo usuário, a conta voip é criada automaticamente com o codec g729 selecionado, seria bom que isso não ocorre-se uma vez que o MB não vem com o codec instalado por padrão.

**Comment by magnussolution** [comment]
Boa tarde. Obrigado por colaborar com o projeto, mas nao podemos retirar o G729 como default, geraria muito problemas para muitos usuários ja que 90% pelo menos usa G729.

Nao posso deixar instalado a versao non-comercial do codec, justamente porque nao é comercial.
