### ISSUE TITLE
Permissão de Conta Voip - Alterar só funciona em conjunto com Criar

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#152]
Liberei para m grupo de usuario a opção de Atualizar em na ABA "CONTAS VOIP"

Quando tenta salvar alguma alteração retornar o erro,:
Access denied to canCreate in module: sip

Se liberar a opção Criar ai funcionar sem erro.

Se o intuito é dar a opção de alterar alguma informação como senha não faria sentido ter que dar a opção criar, pois liberando criar o usuario poderá criar varias contas voips.

**Comment by magnussolution** [comment]
resolvido. 2 horas de trabalho
