### ISSUE TITLE
Extrato não muda a pagina

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#154]
Testando passar as paginas de um extrato a mesma nao alterna....
O numero da pagina muda mas o conteudo da pagina continua o mesmo...

Pagina 01 
![image](https://user-images.githubusercontent.com/30813258/32748018-ef8c2510-c8a1-11e7-8cf6-f67b59fa3880.png)

Pagina 02
![image](https://user-images.githubusercontent.com/30813258/32747989-d861d2c2-c8a1-11e7-986d-6182925a1913.png)

Voce verá que o numero da pagina muda mas o extrato continua o mesmo da pagina 01.
ou seja apenas altera o numero da pagina

**Comment by magnussolution** [comment]
fiz varios testes e funcionou perfeitamente. Atualize sempre sua versao

**Comment by hiperphone** [comment]
Esqueci de mencionar que acontece quando logado como usuário..
Pelo Master funciona perfeito.

 

Atenciosamente

 

Rubem Junior
Hiperphone

Business Phone: +55 (11) 3522 4670

Business Phone: +55 (11) 3509 2219

Business Phone: +55 (61) 3246 0230 

Business Phone: +55 0800 880 1020

Mobile Phone: +55 (77) 9 9968 4670 - Vivo
Mobile Phone: +55 (77) 9 9191 4670 - TIM

e-mail:  <mailto:suporte@hiperphone.com.br> comercial@hiperphone.com.br

website: www.hiperphone.com.br


Hipervoip : 10

Skype: rubem.hiperphone

 

 <http://200.184.77.144/programas/webcallback/wcbnosite.php?web_origem=rubem11> 

 

De: magnussolution [mailto:notifications@github.com] 
Enviada em: terça-feira, 14 de novembro de 2017 17:21
Para: magnussolution/magnusbilling6 <magnusbilling6@noreply.github.com>
Cc: hiperphone <comercial@hiperphone.com.br>; Author <author@noreply.github.com>
Assunto: Re: [magnussolution/magnusbilling6] Extrato não muda a pagina (#154)

 

fiz varios testes e funcionou perfeitamente. Atualize sempre sua versao

**Comment by hiperphone** [comment]
O teste que nao muda o conteudo da pagina aconteceu logando como usuario... A numeração de pagina altera mas o conteudo nao.
Testando via Master o conteudo das paginas alteram conforme a pagina.

**Comment by magnussolution** [comment]
resolvido 1 hora de trabalho
