### ISSUE TITLE
Campanha Rapida nao funciona e conflita com outros ambientes do Callcenter

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#155]
Segue o video para melhor entendimento!

[Campanha Rapida.zip](https://github.com/magnussolution/magnusbilling6/files/1470829/Campanha.Rapida.zip)

**Comment by RodrigoRDC17** [comment]
Para melhor entendimento é Quick Campaign! E analise a possibilidade de incluir o sipcapture!

**Comment by magnussolution** [comment]
o menu Campanha rapida é para ser usando somente como administrador

**Comment by magnussolution** [comment]
coloquei um alert informant sobre o uso exclusivo para cliente. 1 hora de trabalho
