### ISSUE TITLE
Quick campaing não funciona 

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#158]
Atualizado o sistema após resposta e o mesmo continua conflitando com outras partes do sistema menu callcenter.

**Comment by magnussolution** [comment]
o quick campaign nah é para enviar 1 SMS, use o menu SMS para enviar 1 sms. O quick campaign é para o usuario poder criar uma campanha de forma rápida. A questão do plano ja foi solucionado
