### ISSUE TITLE
deletar todos tarifas logado como agente

### ISSUE THREAD

**Issue by Digitalvox92se** [magnussolution/magnusbilling#161]
nao consigo excluir tarifas de agente selecionado um plnao e deleter todos

**Comment by Digitalvox92se** [comment]
mas eu posso deletar o plano e ai deleta as tarifa automaticamente. Ai so criar o plano novamente

**Comment by Digitalvox92se** [comment]
nao conseguia deletar porque o plano estava selecionado em um cliente

**Comment by magnussolution** [comment]
resolvido 1 hora de trabalho
