### ISSUE TITLE
INCOMPATIBILIDADE COM CHROME

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#165]
Bom dia!

Adilson fiz varios testes e encontrei incompatibilidade com googlhe chrome; alguns botoes travam e nao funcionam. No firefox funcionam normalmente!

Um exemplo! 

Quando edito uma conta e tento salva o editado na vai ai vou no firefox e tente a mesma coisa e funciona!

**Comment by magnussolution** [comment]
nao consegui simular a incompatibilidade informada

https://www.dropbox.com/s/6w3yp9wrjmqij4z/issue165.mov?dl=0

Por favor use o developer tools para mostrar o erro que acontece no momento da suposta incompatibilidade.

**Comment by RodrigoRDC17** [comment]
Boa tarde! mais a noite vou criar um video te mostrando os erros! principamente na are trunk e contas voip!
