### ISSUE TITLE
Erro no formulário de registro

### ISSUE THREAD

**Issue by betaniojr** [magnussolution/magnusbilling#166]
Boa tarde!
Versão do MBilling - 6.0.7
Linux - CentOs 7
Item com erro verificado - Formulário de registro
O formulário de registro mesmo com todos os campos preenchidos, não avança para a próxima página, não envia o e-mail e não realiza o cadastro com os dados preenchidos no formulário.
Gostaria ainda de deixar registrado que, a primeira vista, cheguei a me perguntar que código seria aquele. A recomendação seria colocar o texto: Digite o código abaixo ou possibilitar usar recaptcha. Caso seja possível tenho interesse em financiar a melhoria do formulário (deixar responsivo, possibilitar colocar o logo....)

**Comment by magnussolution** [comment]
foi resolvido em suporte
