### ISSUE TITLE
DESTINO DID COM ERRO SETADO CHAMADA SIP E INDO PARA CALLING CARD

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#169]
<SIP/DID-EMPRESA-00000005>AGI Rx << VERBOSE "prepaid-invalid-digits" 3
    -- "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000005>AGI Rx << ANSWER
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000005>AGI Rx << STREAM FILE prepaid-invalid-digits "#" 0
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=-1 endpos=0
<SIP/DID-EMPRESA-00000005>AGI Rx << GET DATA prepaid-enter-pin-number 6000 6
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=-1
<SIP/DID-EMPRESA-00000005>AGI Rx << VERBOSE "PIN callingcard -1" 20
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000005>AGI Rx << VERBOSE "prepaid-invalid-digits" 6
       > "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000005>AGI Rx << VERBOSE "Send Congestion prepaid-auth-fail" 3
    -- "/var/www/html/mbilling/agi.php": Send Congestion prepaid-auth-fail
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000005>AGI Rx << EXEC congestion Congestion
    -- AGI Script Executing Application: (congestion) Options: (Congestion)
       > 0x7f491001bb60 -- Strict RTP learning complete - Locking on source address 162.254.147.152:14088
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=-1
<SIP/DID-EMPRESA-00000005>AGI Rx << VERBOSE "Hangup Call  Username " 6
       > "/var/www/html/mbilling/agi.php": Hangup Call  Username 
<SIP/DID-EMPRESA-00000005>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000005>AGI Rx << HANGUP
<SIP/DID-EMPRESA-00000005>AGI Tx >> 511 Command Not Permitted on a dead channel or intercept routine
    -- <SIP/DID-EMPRESA-00000005>AGI Script /var/www/html/mbilling/agi.php completed, returning -1
  == Using SIP RTP CoS mark 5
       > 0x7f491001f390 -- Strict RTP learning after remote address set to: 162.254.147.152:19000
    -- Executing [08005800402@billing:1] AGI("SIP/DID-EMPRESA-00000006", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_request: /var/www/html/mbilling/agi.php
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_channel: SIP/DID-EMPRESA-00000006
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_language: br
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_type: SIP
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_uniqueid: 1512353086.11
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_version: 13.18.3
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_callerid: 553136683391
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_calleridname: unknown
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_callingpres: 0
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_callingani2: 0
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_callington: 0
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_callingtns: 0
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_dnid: 08005800402
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_rdnis: unknown
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_context: billing
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_extension: 08005800402
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_priority: 1
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_enhanced: 0.0
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_accountcode: 
<SIP/DID-EMPRESA-00000006>AGI Tx >> agi_threadid: 139954447996672
<SIP/DID-EMPRESA-00000006>AGI Tx >> 
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "" 5
       > "/var/www/html/mbilling/agi.php": 
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "Start MBilling AGI" 5
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << CHANNEL STATUS SIP/DID-EMPRESA-00000006
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=4
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE " get_agi_request_parameter = Line is ringing ; 553136683391 ; SIP/DID-EMPRESA-00000006 ; 1512353086.11 ;  ; 08005800402" 15
       > "/var/www/html/mbilling/agi.php":  get_agi_request_parameter = Line is ringing ; 553136683391 ; SIP/DID-EMPRESA-00000006 ; 1512353086.11 ;  ; 08005800402
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE CIDCALLBACK
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE MEMBERNAME
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE QUEUEPOSITION
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE PHONENUMBER_ID
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE SPY
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "checkIfIsDidCall 08005800402" 25
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE SECCALL
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "CALL TO PSTN" 15
       > "/var/www/html/mbilling/agi.php": CALL TO PSTN
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "AuthenticateUser " 15
       > "/var/www/html/mbilling/agi.php": AuthenticateUser 
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << GET VARIABLE SIP_HEADER(X-AUTH-IP)
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "try callingcard" 6
       > "/var/www/html/mbilling/agi.php": try callingcard
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << ANSWER
       > 0x7f491001f390 -- Strict RTP switching to RTP target address 162.254.147.152:19000 as source
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET DATA prepaid-enter-pin-number 6000 6
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=-1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "PIN callingcard -1" 20
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "" 6
       > "/var/www/html/mbilling/agi.php": 
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << ANSWER
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "prepaid-invalid-digits" 3
    -- "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << ANSWER
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << STREAM FILE prepaid-invalid-digits "#" 0
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=-1 endpos=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET DATA prepaid-enter-pin-number 6000 6
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=-1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "PIN callingcard -1" 20
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "prepaid-invalid-digits" 6
       > "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << ANSWER
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "prepaid-invalid-digits" 3
    -- "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << ANSWER
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=0
<SIP/DID-EMPRESA-00000006>AGI Rx << STREAM FILE prepaid-invalid-digits "#" 0
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=-1 endpos=0
<SIP/DID-EMPRESA-00000006>AGI Rx << GET DATA prepaid-enter-pin-number 6000 6
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=-1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "PIN callingcard -1" 20
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "prepaid-invalid-digits" 6
       > "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "Send Congestion prepaid-auth-fail" 3
    -- "/var/www/html/mbilling/agi.php": Send Congestion prepaid-auth-fail
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << EXEC congestion Congestion
    -- AGI Script Executing Application: (congestion) Options: (Congestion)
       > 0x7f491001f390 -- Strict RTP learning complete - Locking on source address 162.254.147.152:19000
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=-1
<SIP/DID-EMPRESA-00000006>AGI Rx << VERBOSE "Hangup Call  Username " 6
       > "/var/www/html/mbilling/agi.php": Hangup Call  Username 
<SIP/DID-EMPRESA-00000006>AGI Tx >> 200 result=1
<SIP/DID-EMPRESA-00000006>AGI Rx << HANGUP
<SIP/DID-EMPRESA-00000006>AGI Tx >> 511 Command Not Permitted on a dead channel or intercept routine
    -- <SIP/DID-EMPRESA-00000006>AGI Script /var/www/html/mbilling/agi.php completed, returning -1
usloft5160*CLI>

**Comment by magnussolution** [comment]
VERBOSE "checkIfIsDidCall 8005800727" 25

vc tem o DID 8005800727 criado? sera que nao colocou como 08005800727?
