### ISSUE TITLE
Destino DID com ERRO! Veja o Video para voce entender!

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#171]
Segue video!

https://www.dropbox.com/s/s83thbz3tm3uywe/Destino%20DID%20com%20ERRO.mp4?dl=0

Obrigado!

**Comment by betaniojr** [comment]
Constatei isso hoje. Para resolver temporariamente, tive de criar dois DID's para o mesmo número. Um com 0800numero e outro com 800numero, ambos com o mesmo destino, assim todas as chamadas que eu fiz chamaram.
Vale ressaltar que a forma como o número chega na plataforma é sempre a mesma. Fiquei tentando entender se o tronco de origem está ok, meso sem o did cadastrado ele deveria solicitar o número do pin, mas até eu fazer isso (criar dois DID's para mesmo número) ele ficou oscilando o tempo todo entre chega e não chega na plataforma.
O provedor confirmou que todas as ligações bateram no meu IP.

**Comment by RodrigoRDC17** [comment]
Bom dia!

Porem quando voce cadastra desta forma voce nao terá a gravacao do CDR, E fiz o teste cadastrando a DID sem o 55 esta passando! Porem por regra do sistema o 55 é necessario para ativaçao o relatorio de CDR!

**Comment by RodrigoRDC17** [comment]
Magnus reparou!
