### ISSUE TITLE
Usuario Filtrar Agenda

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#175]
Em teste verifiquei que se logar como usuario nao é possivel na ABA numeros filtrar por agenda. Se logar como ADM filtrar normalmente.

Testei em FILTRO = Iniciado com , Termina com . Contem , Igual a ....

Tinha uns 10 dias que nao atualizava, atualizei ontem e parou. 
Ja tinha ate aberto um Issues sobre isso o qual foi solucionado mas algum ajuste deve ter afetado esta função.

**Comment by magnussolution** [comment]
resolvido, por favor testar e nos enviar feedback, e fechar o issue.

**Comment by hiperphone** [comment]
Tudo ok...
