### ISSUE TITLE
Problemas na Interface

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#178]
Segue o video com problemas na Interface, instalação feita do zero.
Apos clicar no CDR por dia ou por mes ele trava toda a interface.

[ERROINTMB6.zip](https://github.com/magnussolution/magnusbilling6/files/1570498/ERROINTMB6.zip)

**Comment by magnussolution** [comment]
provavelmente vc nao limpou a cache no navegar, teste em outro navegador, onde ainda nao tinha aberto
