### ISSUE TITLE
Problemas na Interface

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#179]
Mesmo problema, chamado fechado e nao solucionado.
Vide  Issues #178

**Comment by yurikurka** [comment]
Perfeito Magnus limpei o cache após a correção  e funcionou! Obrigado.

**Comment by RodrigoRDC17** [comment]
Feche este tópico Yuri!

**Comment by yurikurka** [comment]
Ok

Em 20 de dez de 2017 9:24 PM, "RodrigoRDC17" <notifications@github.com>
escreveu:
