### ISSUE TITLE
String de registro - Troncos

### ISSUE THREAD

**Issue by betaniojr** [magnussolution/magnusbilling#18]
1 - A nova dinâmica de registro do tronco usando a string de registro só é atualizada manualmente, logo, ontem eu precisei mudar a senha para tentar conectar um tronco. Mudei a senha na parte superior e não atentei para a string, que não muda, exceto quando feito manualmente. Ela também impede (logicamente) que eu selecione a opção de registrar tronco sem senha.
2 - Não logrei êxito em registrar um tronco no MBilling 6. Quando fiz por IP e usuário a informação até chegou no outro servidor, mas após poucos segundos, ele aparece como não registrado, o que me impediu de receber chamadas de números DID, por exemplo.

**Comment by magnussolution** [comment]
1 - Isso nao é um BUG. A campo REGISTER é um field igual como outro. Ao selecionar Registrar SIM, nos ja facilitamos a vida de quem esta cadastrando, ja copiando os dados e colocando ali, para evitar que seja feito em formato errado. Mas se vc quiser editar a senha, user ou ip, tera que editar manualmente o field do registro. Se desativar a opção REGISTER, o registro sera retirado do asterisk.

2 - Realizei varias provas com vários troncos e servidores, o registro é executado e registrado corretamente. Se seu registro caiu após ser registrado, ai provavelmente é alguma questão relacionado a RED. Lembrando que o MagnusBilling somente é o responsável por disponibilizar os dados nos arquivos de configuração do Asterisk. Não é o MagnusBilling que registra a conta, quem registra a conta é o Asterisk.
