### ISSUE TITLE
Integração com MercadoPago

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#180]
Em teste pagamento via mercadopago, apenas confirmação de pagamento o credito nao inseri automaticamente.

Fazendo a verificação na URL -  Que nós envia a notificação de pagamento do Mercado Pago
https://www.mercadopago.com.br/ipn-notifications/save
Retorna a mensagem: O URL digitado não responde a um status HTTP correto. Você deve responder 200 ou 201. 

URL utilizada http://MEU IP/hiperphone/index.php/mercadoPago

**Comment by magnussolution** [comment]
nao esta claro sua descrição. Por favor ler  https://github.com/magnussolution/magnusbilling6/issues/56
