### ISSUE TITLE
Exportação e impressão de extrato de ligações

### ISSUE THREAD

**Issue by betaniojr** [magnussolution/magnusbilling#181]
Boa tarde Magnus,

Na exportação do extrato de ligações para csv: 

- Os filtros são desconsiderados, mesmo com o filtro, o arquivo é gerado com todo o histórico de ligações.
- As ligações das últimas 48 horas não vieram
- Gerei um relatório as 14:42 do dia 21/12/2017, mas a ligação mais recente gerada no extrato foi do dia 19/12//2017 ás 10:32.
- Na maioria das ligações, o valor de compra exibido no reletório está ok, mas o valor de venda, onde deveria ser 0,054 por exemplo, é exibido 54. Apenas em algumas linhas os valores de compra e venda estão ok. Procurei uma relação entre as linhas que estão ok e as linhas que não estão ok e não encontrei.

Usando a opção "imprimir":

Quando pressionado o botão sem nenhum filtro, ele gera o relatório normalmente, com qualquer filtro habilitado, ele apresenta o seguinte erro no navegador:
`Internal Server Error

O active record "Call" está tentando selecionar uma coluna inválida "(SELECT destination FROM pkg_prefix WHERE pkg_prefix.id = t.id_prefix) id". Note, a coluna deve existir na tabela ou ser uma expressão de alias (apelido)

An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you`

**Comment by magnussolution** [comment]
por favor atualizar e testar

**Comment by magnussolution** [comment]
por favor, abra um ISSUE para cada problema. 

por favor teste tudo e caso encontrar algum problema que nao foi solucionado, abra um novo issue.
