### ISSUE TITLE
issu with callshop

### ISSUE THREAD

**Issue by llamabara** [magnussolution/magnusbilling#182]
I created an account to callshop, and i created two sip account. So when i log in that account, i cann`t see cabins account. Please i need your help with that issue.

**Comment by magnussolution** [comment]
Do you active CallShop option on the customer?

**Comment by llamabara** [comment]
do you mean to idGroup = Callshop      ?


that option it's activate

2017-12-21 15:23 GMT-06:00 magnussolution <notifications@github.com>:

**Comment by llamabara** [comment]
Oh, thanks Mr. Adilson Magnus. Your're right

i didn't have that option activated.

into aditional information it's that option, that you mean

sorry!!!

2017-12-21 15:40 GMT-06:00 Eliu Miranda Albores <llamabara@gmail.com>:

**Comment by magnussolution** [comment]
close this issue
