### ISSUE TITLE
Mbilling does not find rate

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#183]
Hi. 

I have mbilling 5 database migrated to version 6 and then calls are not processed. Below is the log of a call.

  > "/var/www/html/mbilling/agi.php": 

       > "/var/www/html/mbilling/agi.php": Start MBilling AGI

       > "/var/www/html/mbilling/agi.php": Check If Is Did 35372030

       > "/var/www/html/mbilling/agi.php": CALL TO PSTN

       > "/var/www/html/mbilling/agi.php": AuthenticateUser 559101001

       > "/var/www/html/mbilling/agi.php": Try accountcode authentication 559101001

       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:559101001

       > "/var/www/html/mbilling/agi.php": use_dnid:1 && len_dnid:(8 || len_exten:8 ) && (try_num:0)

       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 35372030

       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 35372030

       > "/var/www/html/mbilling/agi.php": Grab :0 Replacement: 55 Phone Before: 35372030

       > "/var/www/html/mbilling/agi.php": Grab :* Replacement: 5555 Phone Before: 35372030

       > "/var/www/html/mbilling/agi.php": Grab :* Replacement: 5555 Phone Before: 555535372030

       > "/var/www/html/mbilling/agi.php": Phone After translation: 555535372030

       > "/var/www/html/mbilling/agi.php": USERNAME=559101001 DESTINATION=555535372030 PLAN=36 CREDIT=8923.1436

       > "/var/www/html/mbilling/agi.php": SELECT lcrtype, pkg_plan.id AS id_plan, pkg_prefix.prefix AS dialprefix,

       > "/var/www/html/mbilling/agi.php":                 pkg_plan.name, pkg_rate.id_prefix, pkg_rate.id AS id_rate, buyrate,  buyrateinitblock buyrateinitblock,

       > "/var/www/html/mbilling/agi.php":                 buyrateincrement, rateinitial, initblock, billingblock, connectcharge, disconnectcharge disconnectcharge,

       > "/var/www/html/mbilling/agi.php":                 pkg_rate.id_trunk AS id_trunk, pkg_trunk.trunkprefix AS rc_trunkprefix, pkg_trunk.directmedia AS rc_directmedia,

       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.providertech AS rc_providertech ,pkg_trunk.providerip AS rc_providerip,

       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.removeprefix AS rc_removeprefix, pkg_trunk.failover_trunk AS rt_failover_trunk,

       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.addparameter AS rt_addparameter_trunk, pkg_trunk.status, pkg_trunk.inuse, pkg_trunk.maxuse,

       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.allow_error,pkg_trunk.if_max_use, pkg_rate.additional_grace AS additional_grace, minimal_time_charge,

       > "/var/www/html/mbilling/agi.php":                 minimal_time_buy, pkg_trunk.link_sms, pkg_trunk.user user, pkg_trunk.secret, package_offer ,

       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.id_provider, pkg_provider.credit_control, pkg_provider.credit

       > "/var/www/html/mbilling/agi.php":                 FROM pkg_plan

       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_rate ON pkg_plan.id = pkg_rate.id_plan

       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_trunk AS pkg_trunk ON pkg_trunk.id = pkg_rate.id_trunk

       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_prefix ON pkg_rate.id_prefix = pkg_prefix.id

       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_provider ON pkg_trunk.id_provider = pkg_provider.id

       > "/var/www/html/mbilling/agi.php":                 WHERE pkg_plan.id=36 AND pkg_rate.status = 1 AND   (prefix LIKE '&_%' ESCAPE '&' AND '555535372030'

       > "/var/www/html/mbilling/agi.php":                         REGEXP REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT('^', prefix, '$'),

       > "/var/www/html/mbilling/agi.php":                         'X', '[0-9]'), 'Z', '[1-9]'), 'N', '[2-9]'), '.', '.+'), '_', ''))

       > "/var/www/html/mbilling/agi.php":                 ORDER BY LENGTH( prefix ) DESC 

    -- "/var/www/html/mbilling/agi.php": The number 555535372030, no exist in the plan 36

    -- "/var/www/html/mbilling/agi.php": Send Congestion prepaid-dest-unreachable

**Comment by magnussolution** [comment]
Git Hub is exclusive to BUG report, to discussion and help use the forum
