### ISSUE TITLE
Maximo de chamadas completadas - nao funciona

### ISSUE THREAD

**Issue by everaldofw** [magnussolution/magnusbilling#188]
quando coloco um numero tipo 10.000 para baixar no Maximo de chamadas completadas na campanha e quando zerar vai parar as chamadas pelo tempo do audio, não esta baixando a quantidade.

![image](https://user-images.githubusercontent.com/33166565/34538165-80f249de-f0b2-11e7-8caa-6f8cc9abcddc.png)

**Comment by magnussolution** [comment]
nao entendi. Desculpe

**Comment by everaldofw** [comment]
campanha nesse momento ja atendeu 500 chamdas de 28 segundos

![image](https://user-images.githubusercontent.com/33166565/34540231-f37accf8-f0ba-11e7-8406-90447368a23b.png)

![image](https://user-images.githubusercontent.com/33166565/34540263-0c435516-f0bb-11e7-9381-06d594a21da5.png)

Maximo de chamadas completadas esta ainda em 14000 sendo que ja esta para estar em 13500.
Não esta baixando, quando chegar a zero tem que parar as chamadas.

**Comment by magnussolution** [comment]
por favor atualize e teste.

**Comment by everaldofw** [comment]
Testado, funcionou. Obrigado. Vou testar hoje a  noite com 1500 chamadas se vai parar ao zerar.
Obrigado.

**Comment by everaldofw** [comment]
Testado todas as funções, parou também ao zerar. ok 100% funcionando...
