### ISSUE TITLE
 refill agent  is confusing

### ISSUE THREAD

**Issue by williamfjm** [magnussolution/magnusbilling#189]
hello, thanks for improving this project

This time I write because when an agent performs a refill and there are no errors, there is no feedback, this causes the agent to send the refill several times. when the refill does it an admin there is a message of success ,but like agent not

magnusbilling 6.0.8 tested (asterisk 13) centos 7 64 bits
magnusbilling 6.0.6 tested (asterisk 14) centos 7 64 bits
magnusbilling 5.3.1 tested (asterisk 11) ubuntu 14 64 bits
in all three the same thing happens

Is it possible to improve this feature?

![refill](https://user-images.githubusercontent.com/35005185/34548340-767aecc6-f0f9-11e7-9e8d-c48ad214fd0d.png)

it's confusing
thanks for any answer

**Comment by williamfjm** [comment]
Hi, I've been looking at your solution, and I do not think I explain it well, I do not know if I have to write the comments here, but I try it here first before creating another issue.

Here is a video that shows the error
https://www.youtube.com/watch?v=E4WEgDWpdQs

thanks

**Comment by magnussolution** [comment]
try again

**Comment by williamfjm** [comment]
hello I reinstall the system, but the problem continues, I do not know if the problem exists by some configuration of the agent. This is possible??

**Comment by magnussolution** [comment]
check again

**Comment by williamfjm** [comment]
hello magnussolution ,many thanks ,for you help ,the problem was solved
