### ISSUE TITLE
Relatório de ligações quando tem consulta da portabilidade

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#190]
Boa tarde.

Na nova versão do Mbilling ao tirar um relatório de chamadas / falhadas, números que faz a consulta da portabilidade aparecem com o prefixo da portabilidade.

É possível manter como está na versão 5? Segue abaixo exemplo:

A ligação de 2017 está correto, a de 2018 , ambas usando rota GSM com portabilidade, mostra no modelo novo.

![captura de tela 2018-01-04 as 15 14 39](https://user-images.githubusercontent.com/6199400/34575685-cd4b7764-f162-11e7-89db-1a278d8678d5.png)

**Comment by magnussolution** [comment]
ola, nao consegui simular. Voce pode verificar se acontece com outros números?

**Comment by willianmazzardo** [comment]
Bom dia.

Migrei o Mbilling 5 para o 6. Editei um prefixo e salvei para funcionar a saída das ligações.
No plano, ativei a consulta da portabilidade, porém sem a tabela da portabilidade instalada, somente pra testes. Aí aconteceu assim.

Vou tentar com a base da portabilidade instalada e vamos ver se funciona certo. Aviso quando fizer.

**Comment by willianmazzardo** [comment]
Boa noite.

Fiz o teste agora consultando a base de portabilidade numérica e ele mostra o número discado igual com o código do retorno da portabilidade: 1111320+Numero Discado.

![captura de tela 2018-01-08 as 22 09 10](https://user-images.githubusercontent.com/6199400/34698924-d22b3e10-f4c1-11e7-9108-0bd77389cda5.png)

**Comment by magnussolution** [comment]
Resolvido. Por favor atualize e teste. Me informe se ficou 100%

**Comment by willianmazzardo** [comment]
Não sei se foi coincidência, mas após a atualização os relatórios estão muito lentos. Vou testar a noite e aviso.

Obrigado

**Comment by magnussolution** [comment]
nao tem relação, pois a alteração foi na hora de salvar no banco retirar o 1111RN1. Confirme por favor que ficou ok. Assim fechamos o ISSUE.

**Comment by willianmazzardo** [comment]
Funcionou. Obrigado.
