### ISSUE TITLE
Tronco não aparece no Extrato - SMS

### ISSUE THREAD

**Issue by everaldofw** [magnussolution/magnusbilling#192]
Olá.
Gostaria de saber se na versão 6 e assim mesmo e não aparece o tronco que foi enviando o SMS, se aparecer seria melhor, pois dessa forma não temos como saber por qual tronco foi enviado.  E a coluna destino fica em branco mesmo?

![image](https://user-images.githubusercontent.com/33166565/34722152-cdb41abc-f52c-11e7-97cc-505c2f924d1d.png)

**Comment by magnussolution** [comment]
provavelmente vc deletou o tronco que saiu o SMS.

**Comment by everaldofw** [comment]
Não entendi: "Tire a pena ou deixe o SMS com SMS."
