### ISSUE TITLE
Não gera Estatistica - Várias campanhas filtradas e selecionadas - extrato da ligacoes

### ISSUE THREAD

**Issue by everaldofw** [magnussolution/magnusbilling#194]
Ao tentar gerar a estatística de de duas ou mais campanhas selecionadas no extrato, dá o seguinte erro:

![erro 01-estatistica](https://user-images.githubusercontent.com/33166565/35153248-d5cbb6c8-fd0c-11e7-95be-f90f6ec35ec5.jpg)

Ao clicar em IMPRIMIR:

![erro 02-estatistica](https://user-images.githubusercontent.com/33166565/35153283-05faa9da-fd0d-11e7-85a5-b1d909bbd350.jpg)

Se filtrar por data e se for uma unica campanha, funciona perfeitamente.

**Comment by magnussolution** [comment]
foi desenvolvido para somente 1 campanha, Se precisar alterar, entre em contato para orçamento
