### ISSUE TITLE
Trunk Remove prefix doesnt work properly

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#195]
Hi.

Migrating my mbilling from 5 to 6, everything works fine except the trunk who have to cut the 2 first digits like 55 (Brazil). The system cut 55 + DDD if they are the same, like here in RS where the DDD is 55.

![captura de tela 2018-01-21 as 02 22 55](https://user-images.githubusercontent.com/6199400/35190812-09de0d6c-fe52-11e7-8dab-109844462ef9.png)

In some tests, the first trunk dial incorrectly, but when it goes to backup trunk, it dials correctly.

Lets see the log:

    -- Executing [05599641XXXX@billing:1] AGI("SIP/559101001-00000033", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
       > "/var/www/html/mbilling/agi.php": Check If Is Did 5599641XXXX
       > "/var/www/html/mbilling/agi.php": CALL TO PSTN
       > "/var/www/html/mbilling/agi.php": AuthenticateUser 559101001
       > "/var/www/html/mbilling/agi.php": Try accountcode authentication 559101001
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:559101001
       > "/var/www/html/mbilling/agi.php": use_dnid:1 && len_dnid:(12 || len_exten:12 ) && (try_num:0)
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 05599641XXXX
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 05599641XXXX
       > "/var/www/html/mbilling/agi.php": Grab :0 Replacement: 55 Phone Before: 05599641XXXX
       > "/var/www/html/mbilling/agi.php": Grab :* Replacement: 5511 Phone Before: 555599641XXXX
       > "/var/www/html/mbilling/agi.php": Grab :* Replacement: 5511 Phone Before: 555599641XXXX
       > "/var/www/html/mbilling/agi.php": Phone After translation: 555599641XXXX
       > "/var/www/html/mbilling/agi.php": consulta portabilidade numero 555599641XXXX
       > "/var/www/html/mbilling/agi.php": USERNAME=559101001 DESTINATION=555599641XXXX PLAN=252 CREDIT=8921.2525
       > "/var/www/html/mbilling/agi.php": SELECT lcrtype, pkg_plan.id AS id_plan, pkg_prefix.prefix AS dialprefix,
       > "/var/www/html/mbilling/agi.php":                 pkg_plan.name, pkg_rate.id_prefix, pkg_rate.id AS id_rate, buyrate,  buyrateinitblock buyrateinitblock,
       > "/var/www/html/mbilling/agi.php":                 buyrateincrement, rateinitial, initblock, billingblock, connectcharge, disconnectcharge disconnectcharge,
       > "/var/www/html/mbilling/agi.php":                 pkg_rate.id_trunk AS id_trunk, pkg_trunk.trunkprefix AS rc_trunkprefix, pkg_trunk.directmedia AS rc_directmedia,
       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.providertech AS rc_providertech ,pkg_trunk.providerip AS rc_providerip,
       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.removeprefix AS rc_removeprefix, pkg_trunk.failover_trunk AS rt_failover_trunk,
       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.addparameter AS rt_addparameter_trunk, pkg_trunk.status, pkg_trunk.inuse, pkg_trunk.maxuse,
       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.allow_error,pkg_trunk.if_max_use, pkg_rate.additional_grace AS additional_grace, minimal_time_charge,
       > "/var/www/html/mbilling/agi.php":                 minimal_time_buy, pkg_trunk.link_sms, pkg_trunk.user user, pkg_trunk.secret, package_offer ,
       > "/var/www/html/mbilling/agi.php":                 pkg_trunk.id_provider, pkg_provider.credit_control, pkg_provider.credit
       > "/var/www/html/mbilling/agi.php":                 FROM pkg_plan
       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_rate ON pkg_plan.id = pkg_rate.id_plan
       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_trunk AS pkg_trunk ON pkg_trunk.id = pkg_rate.id_trunk
       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_prefix ON pkg_rate.id_prefix = pkg_prefix.id
       > "/var/www/html/mbilling/agi.php":                 LEFT JOIN pkg_provider ON pkg_trunk.id_provider = pkg_provider.id
       > "/var/www/html/mbilling/agi.php":                 WHERE pkg_plan.id=252 AND pkg_rate.status = 1 AND ((prefix='55559964' OR prefix='5555996' OR prefix='555599' OR prefix='55559' OR prefix='5555' OR prefix='555' OR prefix='55' OR prefix='5' ) OR (prefix LIKE '&_%' ESCAPE '&' AND '555599641XXXX'
       > "/var/www/html/mbilling/agi.php":                 REGEXP REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT('^', prefix, '$'),
       > "/var/www/html/mbilling/agi.php":                 'X', '[0-9]'), 'Z', '[1-9]'), 'N', '[2-9]'), '.', '.+'), '_', '')))
       > "/var/www/html/mbilling/agi.php":                 ORDER BY LENGTH( prefix ) DESC 
       > "/var/www/html/mbilling/agi.php": NUMBER TRUNK FOUND1
       > "/var/www/html/mbilling/agi.php": NUMBER TARIFF FOUND -> 1
       > "/var/www/html/mbilling/agi.php": Credit 8921.2525
       > "/var/www/html/mbilling/agi.php": timeout ->> 2548926
       > "/var/www/html/mbilling/agi.php": TIMEOUT->2548926 : minutes=42482 - seconds=6
       > "/var/www/html/mbilling/agi.php": DIRECT MEDIA ACTIVE
    -- AGI Script Executing Application: (DIAL) Options: (sip/YYYYYY/099641XXXXX,50)
  == Using SIP RTP CoS mark 5
    -- Called sip/YYYYYY/099641XXXX
    -- SIP/YYYYYY-00000034 redirecting info has changed, passing it to SIP/559101001-00000033
    -- SIP/YYYYYY-00000034 is busy
  == Everyone is busy/congested at this time (1:1/0/0)
       > "/var/www/html/mbilling/agi.php": K=0 -> ANSWEREDTIME=0-DIALSTATUS=CONGESTION
       > "/var/www/html/mbilling/agi.php": DIRECT MEDIA ACTIVE
    -- AGI Script Executing Application: (DIAL) Options: (sip/OOOOOOO/05599641XXXXX,50)
  == Using SIP RTP CoS mark 5
    -- Called sip/OOOOOOOO/05599641XXXX

As I said, when the calls goes to backup trunk it dials correctly.

Thanks

**Comment by magnussolution** [comment]
please test.

**Comment by willianmazzardo** [comment]
It worked. Thanks
