### ISSUE TITLE
voicemail function

### ISSUE THREAD

**Issue by williamfjm** [magnussolution/magnusbilling#196]
hello I'm not sure this is a problem. But one of the reasons why update magnusbilling was this function, I understand that this function can disable messages in case of error. Only tones would be heard.

  If I misinterpret it, is it possible to deactivate the answered call message and only listen to the recording without having a false payment?

Thank you

**Comment by magnussolution** [comment]
Desculpe, mas não entendi o que vc escreveu.

Voce é brasileiro, esqueceria em português.

**Comment by williamfjm** [comment]
im not ,i speak spanish..i write in spanish?
![voicemail](https://user-images.githubusercontent.com/35005185/35298310-ad5b0796-0079-11e8-8b0d-7815ebe18c27.png)

**Comment by magnussolution** [comment]
si, puedes escribir en español

saludos

**Comment by williamfjm** [comment]
hola ,la cuestion es la siguiente .cuando una llamada pasa por todas las posibles troncales y no se puedo enrutar con exito ,magnus reproduce un audio diciendo "el numero no esta disponible" o "el numero esta actualmente ocupado" ,lo cual quiere decir que hubo un error no especificado y que no se pudo llamar. por ejemplo si se marca un numero incompleto ocurre esto.
El problema con esta funcion e sque genera una señal de cobro "200" genera cobros cortos de 2 a 5 seg ,lo cual me genera algunos inconvenientes a pesar que como tal la llamada no se cobra por tiempo inicial de cobro que es de 8 seg,es posible cambiar la señal de llamada contestada y solo reproducir el audio sin señal de cobro?
gracias por la atencion

**Comment by magnussolution** [comment]
hola, este no es el lugar adecuado para dudas, es exclusivo para reportar BUGs, y con logs para facilitar la solución. 

Esto que escribiste no tiene nada que ver con voicemail. Y aparte esto que quieres ya existe desde mucho tiempo, solo tienes que saber configurar. 

Use el foro o el grupo e WHATSAPP apra pedir ayuda.
saludos
