### ISSUE TITLE
IAX does not save modifications

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#197]
Here is the stack trace when I change some configuration in IAX peer and click in save button.

2018/01/22 17:43:04 [error] [php] Undefined index: allow (/replica/www/html/mbilling/protected/controllers/IaxController.php:66)
Stack trace:
#0 /replica/www/html/mbilling/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#1 /replica/www/html/mbilling/yii/framework/web/CController.php(286): IaxController->runAction()
#2 /replica/www/html/mbilling/yii/framework/web/CController.php(265): IaxController->runActionWithFilters()
#3 /replica/www/html/mbilling/yii/framework/web/CWebApplication.php(282): IaxController->run()
#4 /replica/www/html/mbilling/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#5 /replica/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#6 /replica/www/html/mbilling/index.php(11): CWebApplication->run()
REQUEST_URI=/index.php/iax/save?_dc=1516650184714

**Comment by magnussolution** [comment]
upgrade your magnusbilling. I not see this issue on the last version

**Comment by magnussolution** [comment]
i found the problem and fix, try again

**Comment by willianmazzardo** [comment]
Não resolveu.
