### ISSUE TITLE
 "Cabins" menu blocks the web interface

### ISSUE THREAD

**Issue by fernandoasv** [magnussolution/magnusbilling#198]
Hi,

When clicking on the menu cabins, the Magnus Billing web interface is blocked. This happens in a new installation of version 6.0.9 and in an update from 5.3.6 to 6.0.9.

Thank you.

**Comment by magnussolution** [comment]
hi, i need LOG. In my installation not happen that

**Comment by fernandoasv** [comment]
Hi,

How can I see the log ?.

Thank you.
