### ISSUE TITLE
Nao registra o Pagamento no paghiper

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#199]
Estou fazendo testes com o paghiper e o mesmo após fazer a geracao do boleto, ele não é demonstrado no financeiro-Recargas do usuario! O status fica em branco como se o usuário nâo tivesse efetuado a geração de boletos!

Existe alguma porta especifica de retorno no MB6?

Outra duvida que eu tenho esse gateway paghiper tem api após para dar baixa no boleto ele libera o saldo sozinho?

Obrigado.

**Comment by magnussolution** [comment]
so é gerado a recarga quando o cliente pagar o boleto e o PagHiper mandar a confirmação de pagamento. Funciona parcido com o Pagseguro. tem baixa automática do credito

**Comment by yurikurka** [comment]
Mas é normal em Recargas mesmo apos a geracao do boleto nao aparecer nada?
No gerencianet apresenta que o boleto foi gerado e nao  foi efetuado o pagamento!
É normal isso nao demonstrar nada?

Obrigado.

**Comment by magnussolution** [comment]
o gerencianet precisa para poder liberar a recarga depois de pagar, o PagHiper não precisa.

**Comment by yurikurka** [comment]
Valeu Magnus obrigado. Vou efetuar o pagamento e verificar.
