### ISSUE TITLE
Cadastro de revendedor

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#20]
Olá, instalei o MagnusBilling 6 na versão 6.0.3, nos testes, eu 
cadastrei um revendedor, 
setei o grupo clientes e 
o plano depois salvei, 
ao logar na conta criada do Agente
 criei um plano e  um usuário, 
faço o processo normal porém ele não salva o usuário criado, 
estou testando no hilario.net.br

não tem log porque o problema é não salvar o cadastro

**Comment by magnussolution** [comment]
Ola, nao consegui reproduzir o problema. Atualize o MagnusBilling e teste novamente. caso acontecer, use o DeveloperTools do Chrome, ou FireBug do FireFox para enviar detalhes do erro que acontece.

**Comment by hilariovoip** [comment]
este e o log do chrome fica assim e nao salva

![22](https://user-images.githubusercontent.com/30841526/29991482-1fe6a122-8f5e-11e7-9cc8-154866054653.JPG)

ao sair perde a informação, não salva.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

http://201.73.146.153/mbilling/index.php/groupUser/read?_dc=1504359529322&page=1&start=0

**Comment by magnussolution** [comment]
Atualize e teste
