### ISSUE TITLE
CDR Export not getting all data

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#200]
Hello.

Im trying to export CDR report and its not export all data to CSV.

If I filter by period and username, like 2018-01-12 and 2018-01-21, in my CSV not show calls between 15 and 17.

I dont know if its a bug or something related to my DB.

**Comment by magnussolution** [comment]
isso nao acontece com a instalação que tenho de teste. Eu não consegui simular.

**Comment by willianmazzardo** [comment]
Eu migrei o Mbilling 5 pro 6. Pode ser isso?

**Comment by RodrigoRDC17** [comment]
Este erro acontece no Mb6 mesmo sendo instalado do zero testei no meu e tambem na exportaçao ele nao carrega dar mensagem que nao consegue atender solicitaçao no momento!

http://meu-ip/mbilling/index.php/call/csv/?columns=[{%22header%22:%22Data%22,%22dataIndex%22:%22starttime%22},{%22header%22:%22Callerid%22,%22dataIndex%22:%22src%22},{%22header%22:%22N\u00famero%22,%22dataIndex%22:%22calledstation%22},{%22header%22:%22Destino%22,%22dataIndex%22:%22idPrefixdestination%22},{%22header%22:%22Dura\u00e7\u00e3o%22,%22dataIndex%22:%22sessiontime%22},{%22header%22:%22Usu\u00e1rio%22,%22dataIndex%22:%22idUserusername%22},{%22header%22:%22Troncos%22,%22dataIndex%22:%22id_trunk%22},{%22header%22:%22Estado%22,%22dataIndex%22:%22terminatecauseid%22},{%22header%22:%22Tipo%22,%22dataIndex%22:%22sipiax%22},{%22header%22:%22Compra%22,%22dataIndex%22:%22buycost%22},{%22header%22:%22Venda%22,%22dataIndex%22:%22sessionbill%22}]&filter=[]&sort=[]&group=

**Comment by magnussolution** [comment]
ola. Isso nao é um problema do MagnusBilling. Isso é configuração de seu servidor.

para facilitar encontrar erros de PHP, como este, devido a falta de memorai, eu adicionei um script para se vc usar no final da URL a variável &display_errors mostrar para vc o erro.

Neste seu problema ai, vai mostrar este ERRO:


Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4 bytes) in /var/www/html/mbilling/yii/framework/db/CDbCommand.php on line 516

ou seja, seu PHP.ini não tem memorai suficiente para gerar um SELECT com tantos dados. Provavelmente vc tem muitas chamadas no CDR.

**Comment by willianmazzardo** [comment]
Olá ... o php.ini do mbilling 5 estava em 512mb e funcionava normalmente ... aumentei pra 2048mb e não exporta todos os dados.

Qual é o valor indicado nessa situação?

**Comment by magnussolution** [comment]
a quantidade de memoria liberada para o PHP depende do seu servidor.

um bom numero é 30 a 50% da memorai total

att. Magnus
