### ISSUE TITLE
Impressão de extrato de ligação

### ISSUE THREAD

**Issue by betaniojr** [magnussolution/magnusbilling#201]
O botão imprimir nos extratos de ligações não funciona. Com filtros ou sem filtros, em modo retrato ou paisagem, ao clicar em imprimir é exibida a seguinte mensagem:

> Internal Server Error
> O active record "Call" está tentando selecionar uma coluna inválida "(SELECT destination FROM pkg_prefix WHERE pkg_prefix.id = t.id_prefix) id". Note, a coluna deve existir na tabela ou ser uma expressão de alias (apelido)
> An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.
> 
> Thank you.

**Comment by magnussolution** [comment]
veja isso https://github.com/magnussolution/magnusbilling6/issues/200

leia a ultima resposta

**Comment by betaniojr** [comment]
Olá Magnus,

Eu vi a outra resposta antes de postar o issue, contudo, o erro aqui ocorre mesmo em um servidor instalado do zero, com 3 ligações no extrato, ou seja, não pode ser relacionado a quantidade de informações no extrato.

**Comment by magnussolution** [comment]
nao consegui simular isso aqui em um servidor de teste. Mas se puder, mande o seu ip e um acesso e eu vejo no seu servidor.
