### ISSUE TITLE
Problemas na Interface Grafica ao desabilitar codecs no Tronco

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#203]
Bom dia

Ao tentar desabilitar os codecs no tronco os mesmos dizem que foram  desabilitados no ckeckbox correspondentes, porem continuam a estar habilitados no menu, como se não tivesse efetuado nada nos comandos

Versao instalada do zero 6.1.0

Veja o video.

[Interface Problema.zip](https://github.com/magnussolution/magnusbilling6/files/1670797/Interface.Problema.zip)

**Comment by yurikurka** [comment]
Versao 6.1.0

**Comment by magnussolution** [comment]
resolvido
