### ISSUE TITLE
Problemas na Gravacao

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#204]
Bom dia.

Ao selecionar a Gravacao no menu usuario e usuario voip o sistema não efetua a gravacao nos sistema, provavelmente as configuracoes efetuadas na interface não estão efetivando o comando!

Segue o Log

mb6-6-0-9*CLI> core set verbose 25
Console verbose was OFF and is now 25.
  == Using SIP RTP CoS mark 5
       > 0x7ff07c020d60 -- Strict RTP learning after remote address set to: 200.162.143.100:18518
    -- Executing [55112730600@billing:1] AGI("SIP/PROVEDOR-DID-TRUNK-00000047", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_request: /var/www/html/mbilling/agi.php
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_channel: SIP/PROVEDOR-DID-TRUNK-00000047
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_language: br
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_type: SIP
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_uniqueid: 1517112929.91
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_version: 13.19.0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_callerid: 1143410000
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_calleridname: unknown
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_callingpres: 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_callingani2: 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_callington: 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_callingtns: 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_dnid: 55112730600
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_rdnis: unknown
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_context: billing
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_extension: 55112730600
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_priority: 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_enhanced: 0.0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_accountcode: 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> agi_threadid: 140671487661824
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "" 5
       > "/var/www/html/mbilling/agi.php": 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Start MBilling AGI" 5
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << GET VARIABLE IDCALLBACK
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << GET VARIABLE CIDCALLBACK
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << GET VARIABLE MEMBERNAME
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << GET VARIABLE QUEUEPOSITION
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << GET VARIABLE PHONENUMBER_ID
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << GET VARIABLE SPY
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Check If Is Did 55112730600" 10
       > "/var/www/html/mbilling/agi.php": Check If Is Did 55112730600
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Is a DID call" 5
       > "/var/www/html/mbilling/agi.php": Is a DID call
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Did have destination" 15
       > "/var/www/html/mbilling/agi.php": Did have destination
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "didCallCost" 10
       > "/var/www/html/mbilling/agi.php": didCallCost
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Array" 25
       > "/var/www/html/mbilling/agi.php": Array
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "(" 25
       > "/var/www/html/mbilling/agi.php": (
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id] => 2" 25
       > "/var/www/html/mbilling/agi.php":     [id] => 2
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_user] => 2" 25
       > "/var/www/html/mbilling/agi.php":     [id_user] => 2
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_ivr] => 0" 25
       > "/var/www/html/mbilling/agi.php":     [id_ivr] => 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_sip] => 1" 25
       > "/var/www/html/mbilling/agi.php":     [id_sip] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_queue] => 0" 25
       > "/var/www/html/mbilling/agi.php":     [id_queue] => 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_did] => 1" 25
       > "/var/www/html/mbilling/agi.php":     [id_did] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [destination] => " 25
       > "/var/www/html/mbilling/agi.php":     [destination] => 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [priority] => 1" 25
       > "/var/www/html/mbilling/agi.php":     [priority] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [creationdate] => 2018-01-28 00:24:44" 25
       > "/var/www/html/mbilling/agi.php":     [creationdate] => 2018-01-28 00:24:44
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [activated] => 1" 25
       > "/var/www/html/mbilling/agi.php":     [activated] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [secondusedreal] => 0" 25
       > "/var/www/html/mbilling/agi.php":     [secondusedreal] => 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [voip_call] => 1" 25
       > "/var/www/html/mbilling/agi.php":     [voip_call] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE ")" 25
       > "/var/www/html/mbilling/agi.php": )
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "" 25
       > "/var/www/html/mbilling/agi.php": 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "CallerID Match regular expression 2 1143410000" 10
       > "/var/www/html/mbilling/agi.php": CallerID Match regular expression 2 1143410000
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "DID 55112730600" 5
       > "/var/www/html/mbilling/agi.php": DID 55112730600
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "try blocked" 5
       > "/var/www/html/mbilling/agi.php": try blocked
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "voip_call 1" 5
       > "/var/www/html/mbilling/agi.php": voip_call 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Mode = did" 5
       > "/var/www/html/mbilling/agi.php": Mode = did
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "DID CALL - CallerID=1143410000 -> DID=55112730600" 6
       > "/var/www/html/mbilling/agi.php": DID CALL - CallerID=1143410000 -> DID=55112730600
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Array" 10
       > "/var/www/html/mbilling/agi.php": Array
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "(" 10
       > "/var/www/html/mbilling/agi.php": (
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id] => 2" 10
       > "/var/www/html/mbilling/agi.php":     [id] => 2
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_user] => 2" 10
       > "/var/www/html/mbilling/agi.php":     [id_user] => 2
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_ivr] => 0" 10
       > "/var/www/html/mbilling/agi.php":     [id_ivr] => 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_sip] => 1" 10
       > "/var/www/html/mbilling/agi.php":     [id_sip] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_queue] => 0" 10
       > "/var/www/html/mbilling/agi.php":     [id_queue] => 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [id_did] => 1" 10
       > "/var/www/html/mbilling/agi.php":     [id_did] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [destination] => " 10
       > "/var/www/html/mbilling/agi.php":     [destination] => 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [priority] => 1" 10
       > "/var/www/html/mbilling/agi.php":     [priority] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [creationdate] => 2018-01-28 00:24:44" 10
       > "/var/www/html/mbilling/agi.php":     [creationdate] => 2018-01-28 00:24:44
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [activated] => 1" 10
       > "/var/www/html/mbilling/agi.php":     [activated] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [secondusedreal] => 0" 10
       > "/var/www/html/mbilling/agi.php":     [secondusedreal] => 0
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "    [voip_call] => 1" 10
       > "/var/www/html/mbilling/agi.php":     [voip_call] => 1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE ")" 10
       > "/var/www/html/mbilling/agi.php": )
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "" 10
       > "/var/www/html/mbilling/agi.php": 
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "[Magnus] DID call friend: FOLLOWME=1 (username:24990" 10
       > "/var/www/html/mbilling/agi.php": [Magnus] DID call friend: FOLLOWME=1 (username:24990
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "                    | destination type:1| id_plan:1)" 10
       > "/var/www/html/mbilling/agi.php":                     | destination type:1| id_plan:1)
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "AuthenticateUser 24990" 15
       > "/var/www/html/mbilling/agi.php": AuthenticateUser 24990
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "Try accountcode authentication 24990" 15
       > "/var/www/html/mbilling/agi.php": Try accountcode authentication 24990
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "AUTHENTICATION BY ACCOUNTCODE:24990" 6
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:24990
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << SET VARIABLE CHANNEL(language) "br"
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << VERBOSE "DID call friend: IS LOCAL !!!" 10
       > "/var/www/html/mbilling/agi.php": DID call friend: IS LOCAL !!!
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Tx >> 200 result=1
<SIP/PROVEDOR-DID-TRUNK-00000047>AGI Rx << EXEC DIAL SIP/24990,45,TtiL(3600000:61000:30000)
    -- AGI Script Executing Application: (DIAL) Options: (SIP/24990,45,TtiL(3600000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 3600000 ms (3600.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    = 
       > warning_sound  = timeleft
       > end_sound      = 
  == Using SIP RTP CoS mark 5
    -- Called SIP/24990
    -- SIP/24990-00000048 is ringing
       > 0x7ff08c00ae50 -- Strict RTP learning after remote address set to: 186.215.148.111:52506
    -- SIP/24990-00000048 answered SIP/PROVEDOR-DID-TRUNK-00000047
    -- Channel SIP/24990-00000048 joined 'simple_bridge' basic-bridge <8959d762-57ad-42fc-b17f-41abce4cb8f2>
    -- Channel SIP/PROVEDOR-DID-TRUNK-00000047 joined 'simple_bridge' basic-bridge <8959d762-57ad-42fc-b17f-41abce4cb8f2>
       > 0x7ff08c00ae50 -- Strict RTP switching to RTP target address 186.215.148.111:52506 as source
       > 0x7ff07c020d60 -- Strict RTP switching to RTP target address 200.162.143.100:18518 as source
       > 0x7ff07c020d60 -- Strict RTP learning complete - Locking on source address 200.162.143.100:18518
       > 0x7ff08c00ae50 -- Strict RTP qualifying stream type: audio
       > 0x7ff08c00ae50 -- Strict RTP switching source address to 186.215.148.111:1027
       > 0x7ff08c00ae50 -- Strict RTP learning complete - Locking on source address 186.215.148.111:1027

**Comment by yurikurka** [comment]
Segue o Video. Versao 6.1.0

[Gravacao.zip](https://github.com/magnussolution/magnusbilling6/files/1670803/Gravacao.zip)

**Comment by magnussolution** [comment]
verifique que o dono do DID tenha a opção de gravar chamada no usuário. este LOG é um DID. grava somente se o dono do DID tiver gravação

**Comment by yurikurka** [comment]
Dono did vc quer dizer a onde? No fornecedor voip?
Foi habilitado no usuario e na conta voip no mb6 /p gravação!

**Comment by magnussolution** [comment]
va no arquivo protected/components/AGI/DidAgi.php linha 81 e adicione isso

$agi->verbose(print_r($this->modelDestination[0]->idDid->idUser,true));

ai deixa o verbose em 1, liga e manda o log deste print

**Comment by yurikurka** [comment]
Boa noite segue os LOGS 

[LOGS-AUDIO-MAGNUS.txt](https://github.com/magnussolution/magnusbilling6/files/1675105/LOGS-AUDIO-MAGNUS.txt)

**Comment by yurikurka** [comment]
[gravacao2.zip](https://github.com/magnussolution/magnusbilling6/files/1675112/gravacao2.zip)

**Comment by magnussolution** [comment]
altere para 

$agi->verbose(print_r($this->modelDestination[0]->idDid->idUser->getAttributes(),true));

coloque o verbose para 1

**Comment by magnussolution** [comment]
estou aguardando o LOG

**Comment by yurikurka** [comment]
Mandei o log para você com a alteração na linha 81. Se não for esse tipo de
log por favor me informe.

Em 30 de jan de 2018 14:38, "magnussolution" <notifications@github.com>
escreveu:

**Comment by magnussolution** [comment]
problema resolvido
