### ISSUE TITLE
Problema no Redirecionamento da Chamada

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#206]
Bom dia!

Nessa nova versao 6.1.0 não esta efetuado o direcionamento da chamada para um outro numero cadastrado!

Apos colocar o numero no reenviar atua como se não nao tivesse a função!

Versao instalada do zero 6.1.0

obrigado.

**Comment by magnussolution** [comment]
nao entendi

**Comment by yurikurka** [comment]
Ao tentar redirecionar a chamada caso o usuário não esteja registrado.

Em 29 de jan de 2018 6:51 PM, "magnussolution" <notifications@github.com>
escreveu:

**Comment by magnussolution** [comment]
acabei de testar em uma instalaçao novo. Ja que eu não conseguia simular em minha instalação de desenvolvimento, me dei o trabalho de contratar um cloud so para tirar a prova.

Criei duas contas voip, loguei 1 no softphone liguei para a outra que não estava registrada, e tinha na opção forward a outra coisa voip, funcionou perfeitamente.

Tambem testei reenviando para um numero FIXO
![screen shot 2018-01-30 at 4 36 28 pm](https://user-images.githubusercontent.com/17835020/35587176-c33bda42-05db-11e8-96fb-879e80f3dde4.png)

**Comment by yurikurka** [comment]
Vou fazer o update e testar aqui, é na opção reenvio! Utilizei todos dial
plan e não ia, esse encaminhamento utiliza o mesmo dial plan da conta
principal?

Obrigado.

Em 30 de jan de 2018 17:36, "magnussolution" <notifications@github.com>
escreveu:

**Comment by yurikurka** [comment]
Voce deve ter ligado para a conta e nao para o DID associado a ela! Com DID nao funciona!
