### ISSUE TITLE
Queue Magnus

### ISSUE THREAD

**Issue by joaolima2013** [magnussolution/magnusbilling#208]
Boa tarde

Estou começando a trabalhar com o Magnus Billing e ao criar filas não encontrei algumas estrategias da ligação. 

**roundrobin**: take turns ringing each available interface (depreciated in 1.4, use rrmemory)
**fewestcalls**: ring the one with fewest completed calls from this queue
**linear**: Rings interfaces in the order they are listed in the configuration file. Dynamic members will be rung in the order in which they were added. (new in 1.6)
**wrandom**: Rings a random interface, but uses the agent's penalty as a weight (new in 1.6)

Essa estrategias entraram na próxima versão???

**Comment by magnussolution** [comment]
ola, nao foi adicionado ainda.

Opçoes:
1 - Apoiar o crescimento do projeto e financiar o desenvolvido informado. Em 1 hora de desenvolvimento adicionamos isso, custo da hora 152 reais.
2- Aguardar futuras atualizações ser adicionado isso, normalmente so é adicionado funções requisitas por muitas pessoas, ou paga ou alguém para adicionar. 

Att.
