### ISSUE TITLE
Metodos de Pagamento

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#21]
Problemas ao selecionar Metodo de pagamento.
[error.zip](https://github.com/magnussolution/magnusbilling6/files/1273228/error.zip)

**Comment by magnussolution** [comment]
ola, nao consegui simular, em minha instalação nova funciona perfeitamente.

**Comment by yurikurka** [comment]
Ele simplesmente nao esta abrindo automaticamente as opcoes a direita sendo necessário um clique na aba de expansão.

**Comment by magnussolution** [comment]
ja foi resolvido, veja a issue #25
