### ISSUE TITLE
PROBLEMA TARIFICADOR

### ISSUE THREAD

**Issue by Accytec** [magnussolution/magnusbilling#210]
Buenos dias, he instalado la version 6 sobre centos7 y me ha sucedido que no tarifica algunas llamadas, (la llamada es realizada con exito pero no queda en ningun registro del magnusbilling) este problema lo venia teniendo con la version5 y sigue sucediendo con la version6.Gracias

**Comment by magnussolution** [comment]
buen dia. Antes de abrir un ISSUE lea esto https://github.com/magnussolution/magnusbilling6/issues/57

Es imposible determinar el problema si no hay datos de como simular el supuesto problema. 

Este espacio no es para suporte.
