### ISSUE TITLE
Tronco nao Inativando

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#211]
Mesmo com a opção definida do tronco como INATIVO e exigindo autenticação, o tronco fica eternamente  ATIVO independente da opcao de inativar, na console do Asterisk fica como ativo!

Versao 6.1.4 a ultima!

**Comment by magnussolution** [comment]
ola, o que vc quer dizer com ativo? 

Registrado? Se sim, o status do tronco nao desativa a register, para retirar o register, desselecione a opção REGISTER

**Comment by yurikurka** [comment]
Enable e disable, na opção ativar e desativar o tronco

Em 22 de fev de 2018 8:31 AM, "magnussolution" <notifications@github.com>
escreveu:

**Comment by magnussolution** [comment]
a opçao Ativar e Desativar nos troncos, nao é para registrar ou nao o tronco.

Se vc desativar o tronco, e a opçao Registrar estiver Ativo o tronco vai continuar registrado, so nao vai mas fazer chamadas, mas receber vai.

**Comment by yurikurka** [comment]
Ok magnus obrigado.

Em 27 de mar de 2018 5:45 PM, "magnussolution" <notifications@github.com>
escreveu:

**Comment by magnussolution** [comment]
se quer desativar o tronco completamente, coloque também registar NO

att
