### ISSUE TITLE
Exportação para csv

### ISSUE THREAD

**Issue by betaniojr** [magnussolution/magnusbilling#214]
Boa tarde Magnus, 

Após o update para a versão 6.1.9 ao clicar no botão de importar para csv, o resultado é um arquivo com o seguinte conteúdo:

`<!DOCTYPE html PUBLIC
	"-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Internal Server Error</title>

<style type="text/css">
/*<![CDATA[*/
body {font-family:"Verdana";font-weight:normal;color:black;background-color:white;}
h1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
h2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
h3 {font-family:"Verdana";font-weight:bold;font-size:11pt}
p {font-family:"Verdana";font-weight:normal;color:black;font-size:9pt;margin-top: -5px}
.version {color: gray;font-size:8pt;border-top:1px solid #aaaaaa;}
/*]]>*/
</style>
</head>

<body>
<h1>Internal Server Error</h1>
<h2>readfile(/tmp/export1520365974.csv): failed to open stream: No such file or directory</h2>
<p>
An internal error occurred while the Web server was processing your request.
Please contact the webmaster to report this problem.
</p>
<p>
Thank you.
</p>
<div class="version">
2018-03-06 16:52:54 </div>
</body>
</html>`

**Comment by magnussolution** [comment]
chmod 777 /tmp

**Comment by betaniojr** [comment]
Mesmo após dar permissão 777 para a pasta tmp e subpastas, o resultado é o mesmo.
