### ISSUE TITLE
Formulário de recuperação de senha

### ISSUE THREAD

**Issue by betaniojr** [magnussolution/magnusbilling#215]
Boa tarde! 

O formulário de recuperação de senha não funciona em meu servidor. O botão de registro aparece e direciona corretamente, mas o botão de recuperação de senha fica da forma exibida no print que segue. Não aparece a caixa do recaptcha, e a janela aparece "desconfigurada" sem botão de fechar, por exemplo.

![image](https://user-images.githubusercontent.com/23484866/37224968-cfc9a21c-23b3-11e8-878d-f2412ee84194.png)

**Comment by magnussolution** [comment]
ola, isso nao é BUG isso é configuraçao. Por favor use o Forum ou o grupo de WhatsApp para solicitar ajuda. Este espaço é exclusivo para BUG e com LOG para poder simular o suposto problema.
