### ISSUE TITLE
Erro ao enviar SMS por API

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#216]
Olá,

Meus clientes estão com problemas ao enviar SMS via API do Mbilling:

2018/03/09 16:38:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "smsSend".' in /replica/www/html/mbilling/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /replica/www/html/mbilling/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('smsSend')
#1 /replica/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /replica/www/html/mbilling/index.php(11): CApplication->run()
#3 {main}

**Comment by magnussolution** [comment]
por favor, antes de abrir um BUG leia atentamente este topico 

https://github.com/magnussolution/magnusbilling6/issues/56

É fundamental dados corretos e detalhados para poder encontrar facilmente o suporto Issue. 

Este issue sera fechado, caso seja necessario, abra outro, passando mais detalhes.
