### ISSUE TITLE
Contas VOIP

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#218]
Ao tenta criar conta voip a mesma nao salva e seguindo o developer dar erro png!

Se precisar de testar pode me chamar no zap! 

MB6

Versao 6.2.3

**Comment by magnussolution** [comment]
este espaço nao e para solicitar ajuda ou suporte. 

Leia https://github.com/magnussolution/magnusbilling6/issues/56

att
