### ISSUE TITLE
Método de Pagamento

### ISSUE THREAD

**Issue by luabragioni** [magnussolution/magnusbilling#219]
Achei um erro aparentemente um BUG.

Fui deletar os métodos de pagamento, depois não consegui mais criar novos métodos de pagamento.

Estou na versão, 6.2.3

**Comment by magnussolution** [comment]
ola, no MBilling 6 os metodos de pagamentos foram adicionado uma combo dinamica usando o que esta no banco de dados, para facilitar ser adicionado novos metodos de pagamento.

Como vc deletou, a opçao deletada desaparece da combo para ser adicionada.

Solucao.

Coloque a opçao deletada no banco de dados manualmente.

aqui esta o banco de dados normal, veja se io metodo deletado é algum destes, e coloque no seu banco

INSERT INTO `pkg_method_pay` (`id`, `id_user`, `payment_method`, `show_name`, `country`, `active`, `active_agent`, `obs`, `url`, `username`, `pagseguro_TOKEN`, `fee`, `boleto_convenio`, `boleto_banco`, `boleto_agencia`, `boleto_conta_corrente`, `boleto_inicio_nosso_numeroa`, `boleto_carteira`, `boleto_taxa`, `boleto_instrucoes`, `boleto_nome_emp`, `boleto_end_emp`, `boleto_cidade_emp`, `boleto_estado_emp`, `boleto_cpf_emp`, `P2P_CustomerSiteID`, `P2P_KeyID`, `P2P_Passphrase`, `P2P_RecipientKeyID`, `P2P_tax_amount`, `client_id`, `client_secret`, `SLAppToken`, `SLAccessToken`, `SLSecret`, `SLIdProduto`, `SLvalidationtoken`, `min`, `max`, `showFields`) VALUES
(5, 1, 'Pagseguro', 'Pagseguro', 'Brasil', 0, 0, 'asd', '', 'info@magnussolution.com', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,username,pagseguro_TOKEN'),
(6, 1, 'BoletoBancario', 'BoletoBancario', 'Brasil', 0, 0, '', 'https://airtime.transferto.com/cgi-bin/shop/topup', '', '', 0, '', '', '', '', '0', '26', '0', 'Até vencimento pagável em qualquer banco e agência', '', '', '', 'Rio grande do sul', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,boleto_convenio,boleto_inicio_nosso_numeroa,boleto_banco,boleto_agencia,boleto_conta_corrente,boleto_carteira,boleto_taxa,boleto_instrucoes,boleto_nome_emp,boleto_end_emp,boleto_cidade_emp,boleto_estado_emp,boleto_cpf_emp'),
(7, 1, 'Moip', 'Moip', 'Brasil', 0, 0, '', 'https://www.moip.com.br/PagamentoMoIP.do', 'magnus', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,id_user,show_name,country,active,min,max,username,url'),
(8, 1, 'Paypal', 'Paypal', 'Global', 1, 0, '', 'https://www.paypal.com/cgi-bin/webscr', 'info@magnusbilling.com', '', 1, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,username,url,fee'),
(9, 1, 'CuentaDigital', 'PagoFacil o Rapipago', 'Argentina', 1, 0, '', 'http://www.cuentadigital.com/api.php', '6200', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,username,url'),
(10, 1, 'DineroMail', 'Tarjeta de crédito, DineroMail', 'Brasil', 0, 0, '', 'https://argentina.dineromail.com/Shop/Shop_Ingreso.asp', '0416248', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,min,max,username,url'),
(11, 1, 'MercadoPago', 'MercadoPago', 'Brasil', 0, 0, NULL, '', '', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,username,pagseguro_TOKEN'),
(12, 1, 'paghiper', 'Boleto Bancario  paghiper', 'Brasil', 1, 0, NULL, '', 'info@magnussolution.com', '', 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 500, 'payment_method,show_name,id_user,country,active,min,max,username,pagseguro_TOKEN');
