### ISSUE TITLE
Sistema solicitando pin em saida de chamadas

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#22]
Ola Adilson, acabei de atualizar a versao para correção do cadastro de revendedores, agora quando faço qualquer ligação o sistema fica solicitando numero pin e nao disca, segue-se o log

![erro](https://user-images.githubusercontent.com/30841526/30030727-02ae20a4-9165-11e7-95f9-c565685d8a56.JPG)

**Comment by magnussolution** [comment]
log com verbose 25 por favor

**Comment by hilariovoip** [comment]
![verbose](https://user-images.githubusercontent.com/30841526/30030876-85ee99f8-9165-11e7-8550-3c11bd992119.JPG)

**Comment by hilariovoip** [comment]
![verbose](https://user-images.githubusercontent.com/30841526/30030935-c3c48620-9165-11e7-8a89-8a81267953ad.JPG)
