### ISSUE TITLE
Numero no esta Disponible

### ISSUE THREAD

**Issue by condigital** [magnussolution/magnusbilling#223]
En una instalación nueva del Magnus Versão 6, en Centos 7 este erro aparece, despui de haber configurado todo bien, el audio dice que no encuentra el nuemero  aunque el prefijo ya esta creado y las tarifas existen..

investigou no código e encontrou o problema.

**El error está no arquivo
/var/www/html/mbilling/protected/components/Plan.php**
**en la linea 78**

`$ modelPrefixLength = PrefixLength :: model () -> localizar ('code =: key', array (': chave' => substr ($ destino, 0, 2)));
`
não está devuelve ningun valor

por lo cual não cumple la condition
`         if (count ($ modelPrefixLength)) {
`
y la variable $ prefixclause toma otro valor la cual hace imposible que se encuentre en la base de datos el precio de venta.

para resolverlo ele añadido un codigo sencillo para obrigar a que entre en la condition
simplemente comento estas dos lineas en la 79 y 80

```
         if (count ($ modelPrefixLength)) {
             $ max_len_prefix = $ modelPrefixLength-> length;
```

  y las cambio por estas

```
$ max_len_prefix = 8;
if ($ max_len_prefix) {
```

de esta forma oblíqua que se cumula a condição e forza que o indicativo pueda tener hasta 8 numeros

**Comment by magnussolution** [comment]
Proba editar, o agregar, un prefijo, en el menu Prefijos. Esto va reconfigurar la base de datos de los prefijos.
