### ISSUE TITLE
Erro ao salvar Tronco

### ISSUE THREAD

**Issue by nicolastanski** [magnussolution/magnusbilling#225]
Ao tentar criar um novo tronco ocorre um erro conforme a imagem.

![erro_salvar_tronco](https://user-images.githubusercontent.com/11888291/40624275-ffe310a2-6281-11e8-81f0-e010d3362d50.jpg)

**Comment by nicolastanski** [comment]
Também ocorre erro na conexão AGI.

 #tail -f /var/www/html/mbilling/protected/runtime/application.log

2018/05/28 14:32:16 [error] [exception.Exception] exception 'Exception' with message 'Failed to login' in /var/www/html/mbilling/protected/extensions/phpAGI/AGI_AsteriskManager.php:391
Stack trace:
#0 /var/www/html/mbilling/protected/components/AsteriskAccess.php(36): AGI_AsteriskManager->connect('localhost', 'magnus', 'magnussolution')
#1 /var/www/html/mbilling/protected/components/AsteriskAccess.php(20): AsteriskAccess->connectAsterisk('localhost', 'magnus', 'magnussolution')
#2 /var/www/html/mbilling/protected/controllers/TrunkController.php(137): AsteriskAccess::instance()
#3 /var/www/html/mbilling/protected/controllers/TrunkController.php(157): TrunkController->generateSipFile()
#4 /var/www/html/mbilling/protected/components/BaseController.php(554): TrunkController->afterSave(Object(Trunk), Array)
#5 /var/www/html/mbilling/yii/framework/web/actions/CInlineAction.php(49): BaseController->actionSave()
#6 /var/www/html/mbilling/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /var/www/html/mbilling/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#8 /var/www/html/mbilling/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 /var/www/html/mbilling/yii/framework/web/CWebApplication.php(282): CController->run('save')
#10 /var/www/html/mbilling/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('trunk/save')
#11 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#12 /var/www/html/mbilling/index.php(11): CApplication->run()
#13 {main}
REQUEST_URI=/mbilling/index.php/trunk/save?_dc=1527527620239
HTTP_REFERER=http://IP_SERVER/mbilling/

**Comment by magnussolution** [comment]
este error é que o MagnusBilling nao esta conseguindo conectar no Asterisk 

2018/05/28 14:32:16 [error] [exception.Exception] exception 'Exception' with message 'Failed to login' in /var/www/html/mbilling/protected/extensions/phpAGI/AGI_AsteriskManager.php:391


Voce pode ter alterado os dados de acesso no manager.conf, ou seu Asterisk nao esta iniciando.
Em qualquer uma das opçoes, nao é um BUG do codigo MagnusBilling. CAso precisar ajuda para mais detalhes sobre seu problema, use os Grupos ou Forum.
