### ISSUE TITLE
CallChart não funciona após update

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#226]
Olá.

Ao rodar o comando do CallChart do crontab, o mesmo não é gerado e dá esse erro:

2018/06/06 09:39:33 [error] [php] Undefined variable: module (/replica/www/html/mbilling/protected/controllers/CallOnlineChartController.php:29)
Stack trace:
#0 /replica/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#1 /replica/www/html/mbilling/index.php(11): CWebApplication->run()
REQUEST_URI=/index.php/CallOnlineChart/read?_dc=1528288771916&page=1&start=0&limit=25

**Comment by magnussolution** [comment]
este script nao é para ser executado no CRON. é uma controller do painel online

**Comment by willianmazzardo** [comment]
Nem mesmo no painel WEB funciona: 

2018/06/06 09:43:36 [error] [php] Undefined variable: module (/replica/www/html/mbilling/protected/controllers/CallOnlineChartController.php:29)
Stack trace:
#0 /replica/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#1 /replica/www/html/mbilling/index.php(11): CWebApplication->run()
REQUEST_URI=/index.php/CallOnlineChart/read?_dc=1528289014914&page=1&start=0&limit=25
