### ISSUE TITLE
Envio de SMS via Mbilling

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#227]
Bom dia.

Como ficou o envio de SMS na nova versão? A URL mudou?
Exemplo:

2018/06/06 10:00:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "smsSend".' in /replica/www/html/mbilling/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /replica/www/html/mbilling/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('smsSend')
#1 /replica/www/html/mbilling/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#2 /replica/www/html/mbilling/index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/smsSend/?username=XXXXX&password=XXXXXX&number=XXXXXXXX&text=MENSAGEM

**Comment by magnussolution** [comment]
este espaço é para informar BUG com dado, para solicitar ajuda, use o forum ou grupo de Whatsapp
