### ISSUE TITLE
Tarifa de venda de revenda não encontrado

### ISSUE THREAD

**Issue by willianmazzardo** [magnussolution/magnusbilling#228]
Olá.

Quando é encerrada uma ligação de cliente de revenda, dá essa mensagem:

 "/var/www/html/mbilling/resources/asterisk/mbilling.php": $MAGNUS->id_agent712 55833XXXXXX - 55833XXXXXX - 12 - 0.025
 "/var/www/html/mbilling/resources/asterisk/mbilling.php": NOT FOUND AGENT TARRIF, USE AGENT COST PRICE

**Comment by magnussolution** [comment]
atualize para a ultima versao e teste. Confirme que o agente tem tarifa para o numero discado
