### ISSUE TITLE
Exporta aquivo CSV de Lista de Enquete Resposta

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#229]
boa tarde!

Realizei um teste para exportar arquivo CSV da Lista de Enquete Reposta...
Foi realizo o filtro da enquete antes de exportar.

![image](https://user-images.githubusercontent.com/30813258/42288242-4bc3b186-7f90-11e8-838b-23ffc83df201.png)

**Comment by magnussolution** [comment]
foi testado e nao aconteceu este problema.
