### ISSUE TITLE
Solicitando pin em saida de chamadas

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#23]
Após atualização o sistema fica solicitando pin ao realizar qualquer chamada

![verbose](https://user-images.githubusercontent.com/30841526/30031015-145dbc28-9166-11e7-8bf1-adaa97521566.JPG)

**Comment by magnussolution** [comment]
vc tem certeza que vc tem um usuário com o numero 93223 criado em seu servidor?

**Comment by hilariovoip** [comment]
vou reinstalar do zero e ja reporto

**Comment by hilariovoip** [comment]
Resolvido, obrigado.
