### ISSUE TITLE
Nao Trafição de DID com a URA e Filla de espera

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#233]
**Bom dia Magnus, efetuei um cadastro de uma ura, essa ura esta associada a um DID pago por minuto, no momento em que entra a ligação no DID o mesmo não é tarifado durante a narrativa da ura, após essa chamada ser transferida para um fila de espera o did  é tarifado por minuto (como manda a regra),porem  é demonstrado no CDR a tarifação, mas não é descontado da conta principal do usuário!

Se voce associar o DID a uma chamada sip a tarifação funciona normalmente!

Temos dois problemas, 
A chamada não é tarifada após a URA atender!
A o preço da chamada é demonstrado no CDR porem não desconta da conta associado ao DID quando voce tem uma URA!

A chamada pode ser transferida ou para um número ou fila de espera mesmo o atendente atendendo não é descontado os valores da conta principal, mesmo mosntrado no CDR!**

Obrigado.

**Comment by yurikurka** [comment]
Usando a ultima versão do repositório aqui!

**Comment by magnussolution** [comment]
ola. Instala um magnusbilling novo, e teste por favor.

**Comment by yurikurka** [comment]
Vou fazer e reporto aqui.

**Comment by yurikurka** [comment]
Até o final de semana posto o resultado, ref a nova instalação!

**Comment by yurikurka** [comment]
Continua o problema.

**Comment by magnussolution** [comment]
Olá Yuri, tudo bem?

Qual a versão do Magnus Billing está usando?

Atenciosamente,

Júnior Santos - Magnus Solution

**Comment by yurikurka** [comment]
Veirifico hoje.

**Comment by magnussolution** [comment]
fiz um teste com a ultima versao, e funcioniu corretamente. Coloquei um DID com tarifa para uma URA.

desligando a chamada durante o audio da ura, tarifa ok
desligando a chamada apos ser trasnferida para uma conta voip, tarifa ok
