### ISSUE TITLE
Funcao de chamadas nas contas VOIP sumiu!

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#234]
A função Redirecionamento de chamadas nas contas VOIP  feito na campanha sumiu das opções do usuário.
Versao 6.3.2.

**Comment by magnussolution** [comment]
foi retirada, porque estamos melhorando a funcao, dando a possibilidade de enviar tabmem para URA e QUEUE, e logo sera criado uma campanha
