### ISSUE TITLE
Erro no baixar 1 gravaçao com somente um click e gravar

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#235]
A função da campanha Adicionar Ramal no CDR + baixar 1 gravaçao com somente um click não esta funcionando,  

A gravação é efetuada mas não é disponibilizado na web para baixar  com um click só click.

**Comment by magnussolution** [comment]
para aparecer a opçao de 1 clique tem que selecionar a coluna oculta

https://www.dropbox.com/s/5jsai51ciy2m60f/Screenshot%202018-08-14%2017.16.56.png?dl=0
