### ISSUE TITLE
Erro na Interface Web na Portabilidade

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#236]
Não está mais disponivel as opções ref ao serviço de portabilidade.

**Comment by magnussolution** [comment]
onde? pode me dar mais informaçao?

**Comment by yurikurka** [comment]
Olá Magnus não estou na máquina para relatar mais as opções que sumiram são
essas da foto de ativar portabilidade.

Em ter, 14 de ago de 2018 14:56, magnussolution <notifications@github.com>
escreveu:

**Comment by yurikurka** [comment]
[magnus .zip](https://github.com/magnussolution/magnusbilling6/files/2288173/magnus.zip)

**Comment by magnussolution** [comment]
nao foi retirado nao, vc colocou no menu configuraçoes o idioma em pt_BR, e deu F5?

**Comment by yurikurka** [comment]
Sim foi dado corretamente, inclusive outros problemas que abri são de
semelhança iguais, tanto a gravação quanto encaminhamento de mensagem.

Em ter, 14 de ago de 2018 16:44, magnussolution <notifications@github.com>
escreveu:

**Comment by yurikurka** [comment]
inclusive outros problemas que abri são de semelhança iguais, tanto na
disponibilização das gravações na interface web quanto no redirecionamento
de chamadas nenhuma das opções aparecem via web.

Em ter, 14 de ago de 2018 17:02, Yuri Kurkarewicz <yurikurka@gmail.com>
escreveu:

**Comment by magnussolution** [comment]
acabei de testar

https://www.dropbox.com/s/nl3s82daeevfyqj/Screenshot%202018-08-14%2017.14.52.png?dl=0

Tem que estar em configuracoes Idioma do MagnusBilling como a imagem abaixo
https://www.dropbox.com/s/asedav8wj9ov1t1/Screenshot%202018-08-14%2017.15.14.png?dl=0

**Comment by yurikurka** [comment]
Assim que chegar vou dar uma olhada.

Em ter, 14 de ago de 2018 17:15, magnussolution <notifications@github.com>
escreveu:
