### ISSUE TITLE
MB 6.3.4 Não tarifa ligações de terminação de outro mb

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#237]
Configurei 1 servidor A e 1 Servidor B com a versao 6.3.4 d MB
em ambos eu criei 1 ramal com numeros diferentes 
no servidor B eu configurei o ramal do servidor A como tronco e chamadas.
Quando faço uma ligação no servidor B a ligação e completa e é tarifada normalmente mas
no servidor A a ligação não é tarifada.
Resumindo... se você criar um ramal em um servidor mb6 e colocar ele como tronco em outro servidor ao realizar chamadas no servidor configurado como tronco a ligação não é tarifada no servidor 1

**Comment by magnussolution** [comment]
manda LOG do VERBOSE 25 de ambos servidores, pois eu nao consegui simular
