### ISSUE TITLE
Exportar a Tabela de Discagem.

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#24]
MB6 instalado no Debin, erro ao exportar a tabela de tarifas!
Veja o video.

**Comment by yurikurka** [comment]
segue o arquivo 
[erroexportar.zip](https://github.com/magnussolution/magnusbilling6/files/1283053/erroexportar.zip)

**Comment by magnussolution** [comment]
resolvido no install.sh 

para resolver em sua instalação adicione esta propriedade no my.cnf dentro de [mysqld]

secure-file-priv = ""

**Comment by yurikurka** [comment]
FOi adicionado e o problema continua do mesmo jeito mesmo após uma nova instalação!

**Comment by yurikurka** [comment]
[ErroMagnus.zip](https://github.com/magnussolution/magnusbilling6/files/1286199/ErroMagnus.zip)

Segue o video Demonstrando

**Comment by magnussolution** [comment]
chown -R asterisk:asterisk /usr/local/src/magnus

tete este comando para dar permissao no directorio

**Comment by magnussolution** [comment]
chmod -R 775  /usr/local/src/magnus

**Comment by magnussolution** [comment]
atualize, ja foi resolvido
