### ISSUE TITLE
Recording issue on Calls

### ISSUE THREAD

**Issue by makwhiz** [magnussolution/magnusbilling#240]
It seems I am getting a strange recording issue on all outgoing calls in latest version. It is making a file but nothing inside that file. For reference I have attached some CLI snapshot.

![cli recording](https://user-images.githubusercontent.com/44035956/46756872-e961aa80-cce1-11e8-86ec-e982d69faf0d.jpg)
![cli recording1](https://user-images.githubusercontent.com/44035956/46756884-f383a900-cce1-11e8-8b99-3d998eb2e425.jpg)
![directoy](https://user-images.githubusercontent.com/44035956/46756894-fc747a80-cce1-11e8-8b2f-d3707d2418f3.jpg)

**Comment by magnussolution** [comment]
![screenshot 2018-10-10 16 24 20](https://user-images.githubusercontent.com/17835020/46760648-f9a96380-cca8-11e8-8f39-1fb3f6a4360f.png)
I create a new instance in Google Cloud to make new teste. Work perfectly.

**Comment by magnussolution** [comment]
video with my config

**Comment by makwhiz** [comment]
yes it is making a file but nothing inside that file. like i have shared. you can see there is same CLI. no error. but file record zero. also another person report same issue.

**Comment by magnussolution** [comment]
![screenshot 2018-10-10 16 37 21](https://user-images.githubusercontent.com/17835020/46761419-c7006a80-ccaa-11e8-9f9a-5b7bf7e071d6.png)
On my test, all work perfectly
