### ISSUE TITLE
Erro no script de instalacao

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#241]
Erro no script de instalacao.

Problemas ao instalar a base dadados.
![erro-script instalacao2](https://user-images.githubusercontent.com/28572532/47190456-e84eff80-d317-11e8-8976-e04924b400dd.jpg)

![erro-script instalacao](https://user-images.githubusercontent.com/28572532/47190381-62cb4f80-d317-11e8-965d-e6ad29d1a9af.jpg)

**Comment by magnussolution** [comment]
vc usou Debian? Se sim, recomendo Centos,

**Comment by yurikurka** [comment]
Utilizei o centos mas como passou muito tempo esse problema já foi
resolvido.

Em ter, 19 de fev de 2019 17:31, magnussolution <notifications@github.com>
escreveu:
