### ISSUE TITLE
Problema com o Cache do aplicativo

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#247]
Esse prolema causa confusão após efetuar uma renovação do certificado SSL.  o (cache.appcache)

Se o seu certificado digital SSL for renovado ou feito uma nova solicitação mesmo ou em outro servidor novo ou antigo com mesmo IP,seu navegador continua apresentando o certificado como invalido mesmo estando tudo ok!
Após apagar o cache.appcache o navegador atualiza as informações do certificado e funciona normalmente! 

![cache-problemas2](https://user-images.githubusercontent.com/28572532/54471345-2dc40b80-4796-11e9-91d9-93024afd1d61.png)

**Comment by magnussolution** [comment]
este arquivo é usado para manter cache do frontend do magnusbilling, mas vc pode remover se quiser.

Ele nao tem relaçao alguma com SSL.
