### ISSUE TITLE
DID NAO BLOQUEA APOS FIM DO SALDO

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#249]
Foi observado que um usuario utilizando um 0800 a qual é tarifado, mesmo quando o mesmo esta com conta inativa ou mesmo saldo zerado o sistema permite receber ligacoes!  Versao 6.5.3

**Comment by magnussolution** [comment]
realmente com o usuario inativo permitia a chamada. Foi resolvido.
