### ISSUE TITLE
Initital setup - email field bugged

### ISSUE THREAD

**Issue by tcreek** [magnussolution/magnusbilling#250]
There are a lot of new Top Level Domains in existence right now, but the email field is not accepting them.

![2019-04-11 (2)](https://user-images.githubusercontent.com/4149717/56012669-23246580-5cb3-11e9-973c-212afa0954b3.png)

This is a stoppage (cannot use)  bug when one cannot enter the correct email address

**Comment by magnussolution** [comment]
hi. It's a EXTJS bug on VType validation, we already reported this bug to Sancha team. You can use another email.
