### ISSUE TITLE
Settings menu wrong language

### ISSUE THREAD

**Issue by tcreek** [magnussolution/magnusbilling#251]
Despite the language set to English, there are many menu items showing up in settings in Portuguese, or  Spanish

![magnus_settings](https://user-images.githubusercontent.com/4149717/56054366-420b1200-5d1c-11e9-8b5b-81b99c26e861.PNG)

**Comment by magnussolution** [comment]
hi, I work to improve the translation. Ou can contribute with the translation.

edit this file
https://github.com/magnussolution/magnusbilling6/blob/master/resources/locale/php/en/yii.php

all data betewenn /*MENU CONFIGURATION*/  tab is configutation menu.


ex:

'config_title_MixMonitor_format'               => 'MixMonitor Format',
    'config_desc_MixMonitor_format'                => 'Record audio extension. See the available extension in http://www.voip-info.org/wiki/view/MixMonitor',
