### ISSUE TITLE
Contas VOIP -> Opção Reenviar

### ISSUE THREAD

**Issue by saggerbr** [magnussolution/magnusbilling#253]
Quando encaminhado a chamada para a conta SIP Destino, conforme programado nos campos "Reenviar"e "Dial Timout",  o ID do chamador aparece como "asterisk" para o destino.

Seria ideal mostrar o ID de origem da chamada ( ponta A ).

testado na versão MB_6 ... 6.5.3

**Comment by magnussolution** [comment]
isso nao é um BUG, é uma alteraçao no sistema. Sera verificado.
