### ISSUE TITLE
Nova instalação 6.5.6 não troca a senha e não apresenta informações do servidor

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#254]
Estou fazendo uma instalação nova para fazer testes de backup e restauração do banco de dados do Magnusilling e apresentou esses problemas, não troca a senha padrão do painel web e não mostra as informações do servidor.
![erro](https://user-images.githubusercontent.com/50499925/57551939-b1d2e380-7340-11e9-80fd-0986577c3be6.jpeg)

**Comment by magnussolution** [comment]
roda o update.sh

**Comment by sipserver** [comment]
Rodei o update.sh dia 10/05 varias vezes e hoje 13/05 as 10:00 fiz uma instalação nova e continua a não trocar a senha e não aparece as informações do servidor.

**Comment by magnussolution** [comment]
atualize novamente.
