### ISSUE TITLE
O retorno das transações HTTP POST e GET não respeita a localização (tradução) escolhida.

### ISSUE THREAD

**Issue by GabrielBragaRJ** [magnussolution/magnusbilling#260]
Todo retorno de uma ação no banco de dados através dos controllers PHP retornam com as mensagens de status (sucesso ou erro) em inglês mesmo outro idioma tendo sido configurado para o sistema. Eu corrigi o problema no meu caso editando o arquivo .../mbilling/protected/config/main.php adicionando  **_'language'=>'pt_BR',_** entre as linhas:

`'preload'    => array('log'),`
`# autoload das models e componentes`

no meu caso o idioma é o português mas acredito que o certo seria este arquivo usar alguma função para buscar a language cadastrada no sistema automaticamente.

**Comment by magnussolution** [comment]
vc deve somente colocar a linguagem no menu configuraçoes. A controller principal do sistema usa um metodo do proprio Yii para o idioma

`Yii::app()->language = Yii::app()->sourceLanguage = $this->config['global']['base_language'];`

se vc esta tentando criar uma controller sua, que vc possa acessar sem estar logado no sistema, vc pode usar 

`Yii::app()->language = Yii::app()->sourceLanguage = 'pr_BR';`

**Comment by GabrielBragaRJ** [comment]
Desculpe Magnus, talvez não tenha ficado claro em meu outro post, mas mesmo setando a linguagem para português limpando o cache do navegador e reiniciando a aplicação, as mensagens de sucesso e falha (e possivelmente outras) em operações de insert e update ainda vem em inglês. A única maneira que encontrei de trazer essas mensagens traduzidas foi conforme descrevi acima.

**EDIT:** O idioma do usuário também está setado como 'Português'.

Abaixo segue um exemplo -> ('Operation was successful.'):

![screencapture-191-252-111-175-mbilling-2019-07-04-10_10_41](https://user-images.githubusercontent.com/25178153/60669232-2f4c3900-9e44-11e9-8996-a65ad79e603d.png)

![screencapture-191-252-111-175-mbilling-2019-07-04-10_11_23](https://user-images.githubusercontent.com/25178153/60669243-370bdd80-9e44-11e9-8719-a790fdedd5f8.png)
