### ISSUE TITLE
Username prefixo não aceita se for iniciado por letras ou pelo numero 0.

### ISSUE THREAD

**Issue by GabrielBragaRJ** [magnussolution/magnusbilling#261]
A opção de configuração 'USERNAME PREFIXO' não funciona se não for iniciada por um número maior que 0. 
Se eu configurar como prefixo por exemplo **"mb_"** ele não vai aparecer, assim como se colocar **"0mb_"** também não irá aparecer, apenas se colocar um número maior que 0 na frente ou simplesmente um número como prefixo. 

_Exemplos de prefixos que funcionam:_
**"2mb_"**
**"74"**

_Exemplos de prefixos que não funcionam:_
**"mb_"**
**"0mb_"**

**Comment by magnussolution** [comment]
fixed
