### ISSUE TITLE
Não é possível contratar serviços

### ISSUE THREAD

**Issue by GabrielBragaRJ** [magnussolution/magnusbilling#266]
Describe the bug
No form de 'COMPRAR NOVO SERVIÇO' no painel do cliente não aparece nenhum serviço para compra.

To Reproduce
1. Crie um novo serviço.
2. Vincule este serviço ao plano do cliente.
3. Libere acesso ao painel 'Uso de Serviços' e as permissões para criar,atualizar e excluir.
4. Entre no painel do cliente na aba 'Uso de Serviços' e aperte 'Comprar novo serviço'.
5. Dentro do form, no campo 'Serviço' aperte o botão 'filtrar'.

Expected behavior
Os serviços vinculados ao plano utilizado pelo cliente deveriam aparecer para escolha de contratação.

Actual behavior
Não aparece nenhum serviço para escolha.

Additional context
Magnus Billing versão 6.6.1

**Comment by magnussolution** [comment]
isso nao é BUG, é configuraçao de grupos, vc provavelmente nao esta dando permissoes para o menu servicos. Assista o video de grupoes e permissoes.

**Comment by GabrielBragaRJ** [comment]
Ok, achava que só era necessário dar permissão para o a aba 'Serviços -> Uso de Serviços' mas para aparecerem os serviços na hora de comprar foi necessário dar permissão também para a aba 'Serviços -> 
 Serviços'. A partir daí os serviços passaram a aparecer dentro do form de compra, porém continuo sem conseguir contratar o serviço, quando aperto 'Salvar' ele me gera uma mensagem de erro escrito 'Preencha os campos corretamente', entretanto nesse form só existem dois campos, um é o serviço que é selecionado clicando no botão 'Filtrar' e outro é o preço que é carregado automaticamente quando selecionamos o serviço, então não sei o que pode estar ocasionando esse erro.
