### ISSUE TITLE
Bug nas configurações

### ISSUE THREAD

**Issue by jefl2006** [magnussolution/magnusbilling#269]
Bom dia

Fiz o update da versão 6.5.7 para 6.6.1.

No menu configurações->configurações, se você for na ultima pagina "pag. 4" vc não consegue mais voltar.
Ai para voltar ao normal vc tem que de desconectar e conectar novamente.

**Comment by GabrielBragaRJ** [comment]
aqui só tem 3 paginas nas configurações, e isso não ocorre... estou na mesma versão 6.6.1...

**Comment by GabrielBragaRJ** [comment]
Acabo de instalar um servidor novo e o problema de fato está ocorrendo.
