### ISSUE TITLE
Contas Voip

### ISSUE THREAD

**Issue by jefl2006** [magnussolution/magnusbilling#270]
Bom dia

Fiz update da versão 6.5.7 para 6.6.1

No menu Usuarios->Contas Voip.

Quando você ja tem uma Conta Voip criada, e em codecs ela esta configurada para g729,g723,alaw,ulaw, se você ao se logar no sistema e entrar novamente nas contas voip vc ira ver que esta setado certo os codecs. So que se vc clicar em cima desta conta ela abre para alteração so que em codecs vem como g729,gsm,alaw,ulaw.
Ai se vc cancelar e voltar a clicar nela, ela abre correto com g729,g723,alaw,ulaw

**Comment by GabrielBragaRJ** [comment]
Isso também acontece aqui... só aparece na primeira vez que você abre o **form** depois de abrir a aba **Contas VoIP**, depois fica normal... se fechar a aba **Contas VoIP** e abrir novamente o problema se repete...
