### ISSUE TITLE
Invites getting rejected

### ISSUE THREAD

**Issue by rccess** [magnussolution/magnusbilling#285]
Hello all
thanks for nice a project 
i am new for magnus 

i am facing some issue issue in making calls 

invites are getting rejected in inbound and outbound call , evern trunk is properly registered

![image](https://user-images.githubusercontent.com/32220165/61590445-1929d100-abd7-11e9-9cdb-5f30125f56a5.png)

![image](https://user-images.githubusercontent.com/32220165/61590448-22b33900-abd7-11e9-9c2e-cb4d5474fa8b.png)

Please advice

**Comment by magnussolution** [comment]
send log from Asterisk with verbose 25

**Comment by rccess** [comment]
thanks for your reply

there is nothing generating in asterisk console 

![image](https://user-images.githubusercontent.com/32220165/61592354-dc1e0880-abef-11e9-9dd3-d0255283dc41.png)


![image](https://user-images.githubusercontent.com/32220165/61592357-e4764380-abef-11e9-8fc1-ce3ecd61faf1.png)

here are the Iptables rules

![image](https://user-images.githubusercontent.com/32220165/61592359-f1933280-abef-11e9-9c7f-4ad9f741aed7.png)

**Comment by rccess** [comment]
i do believe issue is related to iptables

![image](https://user-images.githubusercontent.com/32220165/61592665-05d92e80-abf4-11e9-8624-4a3b1e47bed9.png)


can you please suggest , what is going wrong here

**Comment by rccess** [comment]
based on the sip ip logs

-----------------------------------------------------------

<--- Reliably Transmitting (NAT) to 10.237.252.225:5060 --->
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 10.237.252.225:5060;branch=z9hG4bK-*1*f3cfecdfccca332585ddtaN0;received=10.237.252.225;rport=5060
From: <tel:+9194xxxx3017>;tag=ztesipFuZp9tEy*1-4-20481*cjhj.1
To: <tel:+9114xxxxx2101>;tag=as67149f9c
Call-ID: UPQ6Y87k_-Ienswbm-sMpt7pugHXmiC7Y5yhAT6NnA4jaca@zteims
CSeq: 1000 INVITE
Server: MagnusBilling
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


<------------>
Scheduling destruction of SIP dialog 'UPQ6Y87k_-Ienswbm-sMpt7pugHXmiC7Y5yhAT6NnA4jaca@zteims' in 6400 ms (Method: INVITE)

<--- SIP read from UDP:10.237.252.225:5060 --->
ACK sip:+911413812100@10.17.118.25:5060 SIP/2.0
Via: SIP/2.0/UDP 10.237.252.225:5060;rport=5060;branch=z9hG4bK-*1*f3cfecdfccca332585ddtaN0
To: <tel:+91141xxxxxxx101>;tag=as67149f9c
From: <tel:+91xxxxx17>;tag=ztesipFuZp9tEy*1-4-20481*cjhj.1
Call-ID: UPQ6Y87k_-Ienswbm-sMpt7pugHXmiC7Y5yhAT6NnA4jaca@zteims
CSeq: 1000 ACK
Max-Forwards: 70
User-Agent: ZTE-B200
Content-Length: 0

<------------->
--- (9 headers 0 lines) ---
Really destroying SIP dialog 'UPQ6Y87k_-Ienswbm-sMpt7pugHXmiC7Y5yhAT6NnA4jaca@zteims' Method: ACK
Reliably Transmitting (NAT) to 10.237.252.225:5060:
OPTIONS sip:10.237.252.225 SIP/2.0
Via: SIP/2.0/UDP 10.17.118.25:5060;branch=z9hG4bK06207806;rport
Max-Forwards: 70
From: "asterisk" <sip:+911413812100@10.17.118.25>;tag=as0b469d8e
To: <sip:10.237.252.225>
Contact: <sip:+911413812100@10.17.118.25:5060>
Call-ID: 3d03fcf92998a53f33f25f2f0da24f88@10.17.118.25:5060
CSeq: 102 OPTIONS
User-Agent: MagnusBilling
Date: Sun, 21 Jul 2019 15:06:27 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


---

<--- SIP read from UDP:10.237.252.225:5060 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.17.118.25:5060;received=10.17.118.25;rport=5060;branch=z9hG4bK06207806
To: <sip:10.237.252.225>;tag=59dd7e1370e413bb-c07c80a536ea4a8-cbsxz
From: "asterisk"<sip:+911413812100@10.17.118.25>;tag=as0b469d8e
Call-ID: 3d03fcf92998a53f33f25f2f0da24f88@10.17.118.25:5060
CSeq: 102 OPTIONS
Max-Forwards: 70
Contact: <sip:10.237.252.225:5060;comp=sigcomp>
Supported: replaces,timer
User-Agent: MagnusBilling
Allow: INVITE,CANCEL,BYE,ACK,REGISTER,OPTIONS,PRACK,INFO,REFER,SUBSCRIBE,NOTIFY,MESSAGE,UPDATE,PUBLISH
Date: Sun, 21 Jul 2019 15:06:27 GMT
Content-Length: 0

<------------->
--- (13 headers 0 lines) ---
Really destroying SIP dialog '3d03fcf92998a53f33f25f2f0da24f88@10.17.118.25:5060' Method: OPTIONS

<--- SIP read from UDP:10.237.252.225:5060 --->
OPTIONS sip:+911413812100@10.17.118.25:5060 SIP/2.0
Via: SIP/2.0/UDP 10.237.252.225:5060;branch=z9hG4bK-*1*5f86dc6829289ea1-NobtuOETZ-1-taN0
Max-Forwards: 70
To: <sip:+911zzzzz00@dxxxxxxi.rxxxxxxxims.in>
From: BgwLinkTest1706631450 <sip:bgw@10.237.252.225>;tag=15c988326c5d9343
Call-ID: 71deb9fd200307191120@10.237.252.225
CSeq: 1000 OPTIONS
Accept: application/sdp
Content-Length: 0

<------------->
--- (9 headers 0 lines) ---
Sending to 10.237.252.225:5060 (no NAT)
Looking for +911413812100 in billing (domain 10.17.118.25)

<--- Transmitting (no NAT) to 10.237.252.225:5060 --->
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 10.237.252.225:5060;branch=z9hG4bK-*1*5f86dc6829289ea1-NobtuOETZ-1-taN0;received=10.237.252.225
From: BgwLinkTest1706631450 <sip:bgw@10.237.252.225>;tag=15c988326c5d9343
To: <sip:+9114xxxxxxxx12100@dxxxxxxi.rxxxxxxceims.in>;tag=as4e33ca8a
Call-ID: 71deb9fd200307191120@10.237.252.225
CSeq: 1000 OPTIONS
Server: MagnusBilling
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Accept: application/sdp
Content-Length: 0

------------------------------------------------------------

**Comment by magnussolution** [comment]
> thanks for your reply
> 
> there is nothing generating in asterisk console
> 
> ![image](https://user-images.githubusercontent.com/32220165/61592354-dc1e0880-abef-11e9-9dd3-d0255283dc41.png)
> 
> ![image](https://user-images.githubusercontent.com/32220165/61592357-e4764380-abef-11e9-8fc1-ce3ecd61faf1.png)
> 
> here are the Iptables rules
> 
> ![image](https://user-images.githubusercontent.com/32220165/61592359-f1933280-abef-11e9-9c7f-4ad9f741aed7.png)

to show asterisk log is necessary active verbose
execute the command 

`core set verbose 25`
