### ISSUE TITLE
DID Destination - DID values not refreshing on adding a new entry

### ISSUE THREAD

**Issue by itmaniax** [magnussolution/magnusbilling#286]
**Describe the bug**
When you create a new DID and then try to create a Destination DID, the dropdown list with the DIDs does not refresh (the new DID entry is not there). You need a page refresh (F5) in order to see the newly created entry  

**To Reproduce**
1. Go to DID and create a new entry
2. Go to Destination DID and add new entry
3. When you click on the dropdown list, to select the newly created DID, the value is not there
4. Refresh the page
5. The new DID entry is in the list

**Expected behavior**
The dropdown list should update with the newly created values.

**Screenshots**
Video explaining the issue: https://www.screencast.com/t/yQJgztRXO

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 75.0

**Comment by magnussolution** [comment]
is not necessary F5, only close the Did Destination and open again. although we go to change the combo like User combo
