### ISSUE TITLE
cannot run cronjob under mbilling account

### ISSUE THREAD

**Issue by gresl** [magnussolution/magnusbilling#287]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gresl** [comment]
When we try to run a cronjob under mbilling account we are getting these errors :
$ php /var/www/html/mbilling/cron.php invoice
PHP Error[2]: fopen(/var/run/magnus/invoicePid.php): failed to open stream: Permission denied
/var/run/magnus is totally owner by root.
In order to be able to write under application account, mode should be changed to 775 and ownership  to root:mbilling.
Also /var/www/html/mbilling/protected/views/invoices had 755 instead of 775.
Once getting all this fixed/adjusted we were able to run cronjob under mbilling account.

**Comment by magnussolution** [comment]
this script was discontinued since version 5
