### ISSUE TITLE
URA EDIT 

### ISSUE THREAD

**Issue by saggerbr** [magnussolution/magnusbilling#288]
Após atualização da versão 6.6.1 par 6.6.2, não esta funcionando a edição da URA.

Quando é selecionada alguma URA para edição, a mesma não abre a janela de edição lateral com as informações da URA para edição.

Foi testado em vários Browsers ( Chrome/firefox/Safari ), limpeza de cache e nova atualização, porém o problema persiste.

![Captura de Tela 2019-07-29 às 09 09 51](https://user-images.githubusercontent.com/39776573/62047445-e4bea200-b1e0-11e9-8f48-f12a1aaebd77.png)

**Comment by magnussolution** [comment]
Atualize e teste novamente

**Comment by magnussolution** [comment]
nao esquece de fechar o issue se funcionar e deixar sua estrela no projeto

**Comment by saggerbr** [comment]
Funcionando perfeitamente! 
Obrigado!
