### ISSUE TITLE
AGI 1 - Internacional prefixes

### ISSUE THREAD

**Issue by jefl2006** [magnussolution/magnusbilling#290]
Remover 00 da configuração AGI 1 - Internacional Prefixes.

Em Configurações -> AGI 1 - Internacional prefixes.
Ao remover o 00 para a ligação poder ir para o tronco com 00 na frente não funciona.
Não posso adicionar 00 no tronco, pois as ligações do Brasil tem que ir sem 00 na frente.

**Comment by magnussolution** [comment]
nao entendi, por favor quando for relatar um suposto BUG seja o maximo descritivo possivel e com dados para poder simular o problema. Caso vc deseja somente ajuda para configurar algo, por favor, veja os videos no menu documentacao do site magnusbilling.orr
