### ISSUE TITLE
CallingCards

### ISSUE THREAD

**Issue by Madji** [magnussolution/magnusbilling#296]
**Describe the bug**
No cdr record is created if a call is made to a DID number(DID destination callingCard)

**To Reproduce**
1. Go to DID
2. Add DID destination callingCard, only allow call from registered callerID
3. Goto Settings , enable auth CallerId
4. Calling to DID, after gretings , dialed number.Talk
5. See , the balance decreases for the user, and there is nothing in cdr!

Magnus version 6.6.8
**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome, firefox

**Comment by magnussolution** [comment]
have you added Prefix on the Tariff menu? 

For example, if you did is 136000587 Add the prefix 1, USA

If you already add, please send us the Asterisk log with verbose set to 25

**Comment by Madji** [comment]
No, I used did in the e164 standard . 
tariff plans naturally contain prefixes by country. I understood. I'll check more and write.

**Comment by magnussolution** [comment]
please active verbose to 25 and send us the LOG

Remember update your magnusbilling

**Comment by Madji** [comment]
Core debug 25
Verbose 25
Call DID 
authorise from callerid.
send new number.
Number Busy.
No failed or any records on the CDR.
[debug.txt](https://github.com/magnussolution/magnusbilling6/files/3595490/debug.txt)

**Comment by Madji** [comment]
It's possible I'm just misreading how this is supposed to work. 
I am used to the fact that the call to did defined as callingcard is not charged (incoming). After user authorization (in any way), the user is given the opportunity to dial a number and call at certain rates for this user.

**Comment by magnussolution** [comment]
fixed. update and test
