### ISSUE TITLE
Numeros Bloqueados -  Torpedo de Voz

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#3]
Em teste de importação de numeros nao esta funcionado.
Apenas fica processando.

Estou usando no teste http://sip.hilario.net.br/mbilling/
usuario: root
senha: magnus

Acesso cedido por membr do grupo magnus no Whatsapp
Não tenho como verificar se houve problema na instalação

**Comment by magnussolution** [comment]
problema resolvido.

tem que colocar na 1º linha o nome da coluna, neste caso 
exemplo

`number`
`55114444444`
`55114785455`
