### ISSUE TITLE
Bloqueio ao errar senha do Usuario

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#302]
Bom dia,

Antes a parte web bloqueava pelo fail2ban, após um tempo foi efetuado um bloqueio somente pela parte web(no caso de erro de login e senha na web), não afetando a parte do usuárioSIP. Porem a segurança feita pelo fail2ban voltou, caso a pessoa erre a senha o fail2ban bloqueia acesso total.
Essa funcionalidade foi retirada?

Obrigado.

**Comment by magnussolution** [comment]
pela web sim. Fail2ban bloqueia agora o SIP e SSH

**Comment by yurikurka** [comment]
Está bloqueando sim o web não está funcionando

Em qui, 22 de ago de 2019 12:19, Adilson Magnus <notifications@github.com>
escreveu:
