### ISSUE TITLE
Tarifas - Revendedor

### ISSUE THREAD

**Issue by mazinholeal** [magnussolution/magnusbilling#306]
**Descrição do bug**
Na hora de excluir as tarifas como **revendedor**, ele some da tela, porém ao atualizar a pagina ela aparece novamente. 

**Reprodução**
1. Ir em tarifas;
2. Selecionar qualquer tarifa;
3. Selecionar Excluir;
4. Atualizar a página

**Observações**
- Foi testado as versões 6.7.2 e 6.7.3, 
- Já foi realizado teste com maquina zerada;
- Já foi realizada limpeza de cache do navegador.

**Comment by sipserver** [comment]
Testei aqui também está com esse problema fui excluir uma revenda e ao tentar excluir as tarifas não funciona. versão 6.7.2
