### ISSUE TITLE
Revendedor - Números

### ISSUE THREAD

**Issue by mazinholeal** [magnussolution/magnusbilling#307]
**Descrição do BUG**
Ao cadastrar um ou vários números (Torpedo de voz e SMS --> Números), não fica salvo os números (pelo menos visualmente).

**Como reproduzir**
1. Torpedor de voz e SMS;
2. Números;
3. Novo;
4. Preencher os campos necessários;
5. Salvar

**Observações**
1. Foi usado Chrome, Firefox, Opera;
2. Todos com cache limpos;
3. Foi testado por outros computadores;

**Comment by magnussolution** [comment]
realizamos varios testes e funcionou tudo corretamente. Por favor, atualize seu servidor e verifique novamente.
