### ISSUE TITLE
Menu Tarifas Agente não apaga tarifas 

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#310]
Ao tentar apagar varias tarifas dentro de um agente  ou todas não tem efeito, mas se apagar uma a uma ela apaga.

Versão 6.7.4

![erro não apaga tarifa agente](https://user-images.githubusercontent.com/50499925/64461799-96040200-d0d4-11e9-946a-54c91db0999f.png)

**Comment by magnussolution** [comment]
arrumado para mostrar um alert, mas agentes e cliente nao podem deletar mais de 1 registro por vez.

**Comment by sipserver** [comment]
Problema é que para apagar a revenda preciso apagar as tarifas e no root não tenho como apagar a tabela de tarifas do agente, mas se acesso pelo login do agente não consigo apagar todas as tarifas de uma vez só preciso apagar uma a uma isso fica meio complicado.
