### ISSUE TITLE
Incorrect displaying ip addresses

### ISSUE THREAD

**Issue by Madji** [magnussolution/magnusbilling#311]
**Describe the bug**
Magnus is behind NAT.
Has a local address, but in the settings exposed ip address billing external.
1. Client (0168853) external, connected through the Internet , has an ip address which can be seen in the console of asterisk (176...) 
2. the client is connected in a local network (20637), has the address local which is visible in asterisk console (192...)
3. But in the web interface billing addresses look like localhost.. That is not quite correct information. 
4. Firewall is configured correctly and correctly, there are no problems with connection or audio transmission. Regardless of how the client is connected, locally or remotely.

![1](https://user-images.githubusercontent.com/2238714/64478129-717b5900-d1ac-11e9-8cfb-ff7cb883eafa.png)
![2](https://user-images.githubusercontent.com/2238714/64478130-717b5900-d1ac-11e9-9acc-bbb965bfff54.png)

**Comment by magnussolution** [comment]
the host is not the REGISTER host, is the asterisk peer host.

and Localhost is the server that user is registered, it is used when you use Slave servers.
