### ISSUE TITLE
magnusbilling não transfere chamada atendida por agente de fila de espera

### ISSUE THREAD

**Issue by trclamar** [magnussolution/magnusbilling#312]
-> quando setamos um destino de did para uma queue (fila), o canal sip que atender não conseguirá transferir, e no console do asterisk aparece "caller hung up before dial".

 -> quando setamos um destino de did para uma chamada sip, o canal sip atende e consegue transferir normalmente;

**Comment by magnussolution** [comment]
isso nao é um BUG, pois aqui consigo usar tranquilamente, deve ser algo em seu servidor.

**Comment by trclamar** [comment]
versão 6.6.5 limpa, instalada no centos 7, algumas contas voip criadas,
algumas delas colocadas como agentes de uma queue. um did de entrada de um
provedor, normal, padrão.
nenhuma outra modificação no servidor.

vou instalar a versão mais nova limpa novamente, em uma vps com centos7
rescém criado, visto que o script de update apresentou um erro de permissão
em algum chmod na hora de executar.
se o problema persistir, vou abrir issue novamente, pois não deverá ser
considerado um problema no meu servidor.
se possível, vou gravar a instalação.

Att.
*Thiago Rheinheimer Costa*

<http://www.tryideas.com.br/>

41 4063-7293    Curitiba
44 3112-0603    Maringá
45 3112-0224    Cascavel
45 3055-7688    Toledo
45 3055-7688    Marechal Cândido Rondon

www.tryideas.com.br
www.4aw.com.br
www.mageshop.com.br


Em qui, 12 de set de 2019 às 14:52, Adilson Magnus <notifications@github.com>
escreveu:
