### ISSUE TITLE
Menu DID agente não ativa DID após a compra

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#316]
Após o agente fazer a compra do DID, o agente recebe uma mensagem que deve aguardar a liberação do DID mas no menu DID do root não tem ação nenhuma para liberar a compra.

1.  Logando como agente 
2. Click no menu comprar DID
3. CONFIRME A COMPRA
4. mensagem para aguardar ativar o DID
5. menu DID do root aparece o DID mas não tem nenhuma ação para ativar o DID.

Instalação feita hoje versão 6.7.4 segue as imagens dos problema.
![ativar DID agente](https://user-images.githubusercontent.com/50499925/64739565-d85c8300-d4c8-11e9-89a0-3c475fadc8d7.JPG)
![ativar DID root](https://user-images.githubusercontent.com/50499925/64739566-d85c8300-d4c8-11e9-9686-2812781061f0.JPG)
![comprar DID](https://user-images.githubusercontent.com/50499925/64739567-d85c8300-d4c8-11e9-85f0-2077ce66fc20.JPG)
![confirmação compra did](https://user-images.githubusercontent.com/50499925/64739568-d8f51980-d4c8-11e9-9cac-75e7327d3d1e.JPG)
![mensagem após a compra DID](https://user-images.githubusercontent.com/50499925/64739571-d8f51980-d4c8-11e9-912b-f36a576af445.jpg)
![versão 6 7 4](https://user-images.githubusercontent.com/50499925/64739572-d8f51980-d4c8-11e9-8390-0c2bc3a19c4e.JPG)

**Comment by magnussolution** [comment]
no MagnusBilling nao foi desenvolvido para Agent comprar DID. Somente cliente pode comprar DID.

**Comment by magnussolution** [comment]
alterei o codigo para informar que nao é possivel.
