### ISSUE TITLE
Menu usuário agente não salva nada após ser criado o usuário

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#317]
Após criar o usuário no agente sem o e-mail ou outra informação, se editar qualquer  campo e tentar salvar, ele não salva.

1. Logar como agente 
2. Click menu usuário 
3. novo usuário sem e-mail ou outra informação
4. Editar usuário colocar e-mail ou outra informação clicar em salvar.
5. Atualizar o menu usuário some as informações inseridas.

![não salva e-mail ](https://user-images.githubusercontent.com/50499925/64740220-0a6ee480-d4cb-11e9-933c-886c26fd0028.jpg)
![editar dados usuário agente](https://user-images.githubusercontent.com/50499925/64740666-7aca3580-d4cc-11e9-968f-d353b25b170c.JPG)

**Comment by itsshimmer** [comment]
retorna "try edit invalid id" referente a BaseController.php
