### ISSUE TITLE
Deleting Users does not delete SIP Peer

### ISSUE THREAD

**Issue by danj1980** [magnussolution/magnusbilling#318]
sip_magnus_user.conf still contains old peers for users which were deleted.

Click Users->Users
Select a User and press Delete
Accept the confirmation
The User is removed from the list
The associated SIP Account is not shown on Users->SIP Account
Check sip_magnus_user.conf and it still contains the authentication details.

**Comment by magnussolution** [comment]
the file sip_magnus_user.conf is recreating each time you edit or create on the SipAccount menu.

After deleting the user, edit any sip account, it will recreate the sip_magnus_user.conf. But not worry, if the user not exist on the database, even the user exist on the asterisk file, he cant call.
