### ISSUE TITLE
StandardCallAgi->processCall does not Answer()

### ISSUE THREAD

**Issue by danj1980** [magnussolution/magnusbilling#320]
With config answer_call = 1, calls routed via the StandardCallAgi class do not get Answer() and just hang up.

[debug.txt](https://github.com/magnussolution/magnusbilling6/files/3610601/debug.txt)

**Comment by danj1980** [comment]
Sorry, that debug.txt output may not relate to this issue. I forgot that I manually added Answer() to StandardCallAgi->processCall

The debug.txt may relate to a different issue which I am trying to identify.

However, this bug issue is still relevant and Answer() needs adding to the processCall function.

**Comment by magnussolution** [comment]
the option answer_call is only to the incoming call

**Comment by danj1980** [comment]
> 
> 
> the option answer_call is only to the incoming call

StandardCallAgi->processCall is being used for incoming call, so answer_call needs to be used?
