### ISSUE TITLE
prepaid-auth-fail announcement does not play

### ISSUE THREAD

**Issue by danj1980** [magnussolution/magnusbilling#325]
When a caller does not authenticate successfully, the prepaid-auth-fail annoucement does not play.

**Comment by magnussolution** [comment]
Magnusbilling only play audio if you have activated the option on the plan

**Comment by danj1980** [comment]
> 
> 
> Magnusbilling only play audio if you have activated the option on the plan

The plan option is only available if the user has authenticated. But if the user authentication fails, there is no user to set $this->play_audio
