### ISSUE TITLE
Incorrect ANSWEREDTIME for billing 

### ISSUE THREAD

**Issue by danj1980** [magnussolution/magnusbilling#331]
### Issue

ANSWEREDTIME is wrong for calculation of charge.

`$answeredtime            = $agi->get_variable("ANSWEREDTIME");` CalcAgi.php line 771

$answeredtime is the time for (intro + prepaid-enter-dest + dtmf entry + outbound dial)
This is a bug.
$answeredtime must ONLY be time for 'outbound trunk dial'.

[Verbose Log with Commenting](https://github.com/magnussolution/magnusbilling6/files/3632631/example.txt)

### Explanation

The functionality of ANSWEREDTIME variable changed between Asterisk v11 and Asterisk v13.
In Asterisk 11, the ANSWEREDTIME gives the length of the Outbound trunk call.
In Asterisk 13, the ANSWEREDTIME gives the length of the main call (the call running AGI mbilling.php).

I have received this confirmation via Freenode IRC #asterisk channel.

Also, reference: https://forum.asterisk2billing.org/viewtopic.php?f=34&t=10727

### Reproduce

- Dial inbound to Magnus DID to access MagnusBilling
- Using CallerID Authentication
- Listen to Intro_Prompt + prepaid-enter-dest
- Slowly dial destination (minimum 30 seconds for testing)
- Wait for Destination Answer
- Speak for 3 seconds maximum
- Hang up

Sell Cost is 30+ seconds. It should be 3 seconds.

**Comment by danj1980** [comment]
It appears that the functionality of ANSWEREDTIME variable changed.
In Asterisk 11, the ANSWEREDTIME gives the time of the Outbound trunk call.
In Asterisk 13, the ANSWEREDTIME give the time of the AGI call.

Reference: https://forum.asterisk2billing.org/viewtopic.php?f=34&t=10727

I am trying to find this change in the Asterisk documentation.

**Comment by magnussolution** [comment]
we are work to fix it on MagnusBilling 7. Thanks

**Comment by danj1980** [comment]
I am writing a fix because it is urgent.
