### ISSUE TITLE
CDR por dia/usuario -> Export CDR

### ISSUE THREAD

**Issue by saggerbr** [magnussolution/magnusbilling#333]
Erro ao exportar relatório por usuário, após filtro por usuário e data especifica.

Erro retornado:

Internal Server Error
CDbCommand falhou ao executar o comando SQL: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'idUser.username' in 'where clause'

**Comment by magnussolution** [comment]
ola, por favor, ser o mais detalhista possivel. Neste caso, vc nao informou nem o menu que vc esta testando. 

E lembre-se, sempre atualizar o servidor antes de abrir um ISSUE, pois o seu problema ja pode ter sido solucionado
