### ISSUE TITLE
Não Grava atendimento depois da URA quando vai para grupo de atendimento

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#334]
Não grava a chamada depois da URA quando a opção escolhida está configurada para um grupo de ramais.

![Capturar](https://user-images.githubusercontent.com/50499925/65644801-a9b3d180-dfcb-11e9-865b-056c7a62faf2.JPG)

Versão 6.7.4

**Comment by magnussolution** [comment]
atualizar para versao 7, e testar novamente
