### ISSUE TITLE
Falha na ativação do cliente pelo link enviado ao e-mail.

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#335]
Depois que o cliente faz o cadastro pelo formulário ele recebe no e-mail um link para ativar sua conta. Quando ele clica no link retorna o erro  da imagem abaixo.

![ativa](https://user-images.githubusercontent.com/50499925/65983389-bf097f80-e453-11e9-8f3f-da2f9378101b.JPG)

Versão 6.7.4

**Comment by sipserver** [comment]
Yuri achou o erro no link tem duas //  tem que arrumar no código 

http://ip/mbilling//  <===   index.php/signup/24?username=


![link erro](https://user-images.githubusercontent.com/50499925/65990469-05fe7180-e462-11e9-8058-ba6ca7efd440.jpg)

**Comment by magnussolution** [comment]
atualizar para versao 7, e testar novamente. Na versao 7 o processo de registro alterou um pouco, por favor assistir o video que foi publicado estes dias no youtube
