### ISSUE TITLE
Arquivos Core was generated

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#337]
Arquivos core estão sendo gerados por alguma terminção anormal no magnus billing provavelmnete pelo php;  

Core was generated by `php /var/www/html/mbilling/cron.php PhoneBooksReprocess'.
Program terminated with signal 7, Bus error.

Vejas as imagens.

![image](https://user-images.githubusercontent.com/28572532/66725424-3baf3d00-ee08-11e9-91f1-ff32a9270616.png)

![image](https://user-images.githubusercontent.com/28572532/66725441-6ef1cc00-ee08-11e9-8504-d2fcd11fd9e5.png)

**Comment by magnussolution** [comment]
execute o comando manualmente e veja se retorna algum erro

**Comment by yurikurka** [comment]
Manualmente não retorna, mas quando esta no cron termina com erro direto.

**Comment by magnussolution** [comment]
fiz varios testes e nao consegui simular o probleme.

**Comment by yurikurka** [comment]
Os arquivos continuam sendo gerados.

![image](https://user-images.githubusercontent.com/28572532/69326921-6e302f00-0c2b-11ea-8f25-9291a4e191d4.png)

**Comment by magnussolution** [comment]
problema encontra. Por algum motivo o script PhoneBooksReprocess esta duas vezes no cron de alguns servidores. Para resolver o problema é so deixar uma única vez no cron.

digite crontab -e e altere
