### ISSUE TITLE
Após atualização novas chamadas não são incluídas no CDR (Extrato de Ligações)

### ISSUE THREAD

**Issue by ericvins** [magnussolution/magnusbilling#338]
**Descrição**

Após atualização da versão 6.3.1 para a versão 6.7.4 as informações de novas chamadas completadas  deixaram de ser exibidas no Extrato de Ligações. As ligações completadas antigas, até o momento antes da atualização, continuam sendo exibidas.

**Testes realizado**

Feito a criação de um novo usuário com nova conta sip para simulação.
Foi habilitado o debug de AGI, e coletado o log mais abaixo.
Acredito que seja algo relacionado a rotina abaixo:
"> "/var/www/html/mbilling/agi.php": Insert call on CDR", onde:

<SIP/20201919-00000009>AGI Rx << VERBOSE "Insert call on CDR" 10
       > "/var/www/html/mbilling/agi.php": Insert call on CDR
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << exception 'CException' with message 'Property "Call.sessionid" is not defined.' in /var/www/html/mbilling/yii/framework/base/CComponent.php:173
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << Stack trace:
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #0 /var/www/html/mbilling/yii/framework/db/ar/CActiveRecord.php(159): CComponent->__set('sessionid', 'SIP/20201919-00...')
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #1 /var/www/html/mbilling/protected/components/AGI/Calc.php(556): CActiveRecord->__set('sessionid', 'SIP/20201919-00...')
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #2 /var/www/html/mbilling/protected/components/AGI/StandardCallAgi.php(34): Calc->updateSystem(Object(Magnus), Object(AGI))
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #3 /var/www/html/mbilling/protected/commands/MagnusCommand.php(139): StandardCallAgi->processCall(Object(Magnus), Object(AGI), Object(Calc))
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #4 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(67): MagnusCommand->run(Array)
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #5 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #6 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #7 /var/www/html/mbilling/agi.php(11): CApplication->run()
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #8 {main}
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command

**LOG COMPLETO**

  Using SIP RTP CoS mark 5
       > 0x7f34cc08fa60 -- Strict RTP learning after remote address set to: xxx.xxx.xxx.xxx:4004
    -- Executing [XXXXXXXXX@billing:1] AGI("SIP/20201919-00000009", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
<SIP/20201919-00000009>AGI Tx >> agi_request: /var/www/html/mbilling/agi.php
<SIP/20201919-00000009>AGI Tx >> agi_channel: SIP/20201919-00000009
<SIP/20201919-00000009>AGI Tx >> agi_language: br
<SIP/20201919-00000009>AGI Tx >> agi_type: SIP
<SIP/20201919-00000009>AGI Tx >> agi_uniqueid: 1571313333.15
<SIP/20201919-00000009>AGI Tx >> agi_version: 13.20.0
<SIP/20201919-00000009>AGI Tx >> agi_callerid: 20201919
<SIP/20201919-00000009>AGI Tx >> agi_calleridname: 20201919
<SIP/20201919-00000009>AGI Tx >> agi_callingpres: 0
<SIP/20201919-00000009>AGI Tx >> agi_callingani2: 0
<SIP/20201919-00000009>AGI Tx >> agi_callington: 0
<SIP/20201919-00000009>AGI Tx >> agi_callingtns: 0
<SIP/20201919-00000009>AGI Tx >> agi_dnid: XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> agi_rdnis: unknown
<SIP/20201919-00000009>AGI Tx >> agi_context: billing
<SIP/20201919-00000009>AGI Tx >> agi_extension: XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> agi_priority: 1
<SIP/20201919-00000009>AGI Tx >> agi_enhanced: 0.0
<SIP/20201919-00000009>AGI Tx >> agi_accountcode: 52522
<SIP/20201919-00000009>AGI Tx >> agi_threadid: 139867609052928
<SIP/20201919-00000009>AGI Tx >>
<SIP/20201919-00000009>AGI Rx << VERBOSE "" 5
       > "/var/www/html/mbilling/agi.php":
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Start MBilling AGI" 5
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE IDCALLBACK
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE CIDCALLBACK
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE MEMBERNAME
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE QUEUEPOSITION
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE PHONENUMBER_ID
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE SPY
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "Check If Is Did XXXXXXXXX" 10
       > "/var/www/html/mbilling/agi.php": Check If Is Did XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE SECCALL
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "CALL TO PSTN" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "AuthenticateUser 52522" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Try accountcode authentication 52522" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "AUTHENTICATION BY ACCOUNTCODE:52522" 6
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:52522
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << SET VARIABLE CHANNEL(language) "br"
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "use_dnid:1 && len_dnid:(9 || len_exten:9 ) && (try_num:0)" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "USE_DNID DESTINATION -> XXXXXXXXX" 10
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "REMOVE INTERNACIONAL PREFIX -> XXXXXXXXX" 10
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Grab :0 Replacement: 55 Phone Before: XXXXXXXXX" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Grab :* Replacement: 5511 Phone Before: XXXXXXXXX" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Grab :* Replacement: 5511 Phone Before: XXXXXXXXX" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Phone After translation: 5511XXXXXXXXX" 10
       > "/var/www/html/mbilling/agi.php": Phone After translation: 5511XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "consulta portabilidade numero 5511XXXXXXXXX" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "USERNAME=52522 DESTINATION=5511XXXXXXXXX PLAN=6 CREDIT=1.8600" 6
       > "/var/www/html/mbilling/agi.php": USERNAME=52522 DESTINATION=5511XXXXXXXXX PLAN=6 CREDIT=1.8600
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "SELECT lcrtype, pkg_plan.id AS id_plan, pkg_prefix.prefix AS dialprefix," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_plan.name, pkg_rate.id_prefix, pkg_rate.id AS id_rate, buyrate,  buyrateinitblock buyrateinitblock," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                buyrateincrement, rateinitial, initblock, billingblock, connectcharge, disconnectcharge disconnectcharge," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_rate.id_trunk AS id_trunk, pkg_trunk.trunkprefix AS rc_trunkprefix, pkg_trunk.directmedia AS rc_directmedia," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_trunk.providertech AS rc_providertech ,pkg_trunk.providerip AS rc_providerip," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_trunk.removeprefix AS rc_removeprefix, pkg_trunk.failover_trunk AS rt_failover_trunk," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_trunk.addparameter AS rt_addparameter_trunk, pkg_trunk.status, pkg_trunk.inuse, pkg_trunk.maxuse," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_trunk.allow_error,pkg_trunk.if_max_use, pkg_rate.additional_grace AS additional_grace, minimal_time_charge," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                minimal_time_buy, pkg_trunk.link_sms, pkg_trunk.user user, pkg_trunk.secret, package_offer ," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                pkg_trunk.id_provider, pkg_provider.credit_control, pkg_provider.credit" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                FROM pkg_plan" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                LEFT JOIN pkg_rate ON pkg_plan.id = pkg_rate.id_plan" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                LEFT JOIN pkg_trunk AS pkg_trunk ON pkg_trunk.id = pkg_rate.id_trunk" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                LEFT JOIN pkg_prefix ON pkg_rate.id_prefix = pkg_prefix.id" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                LEFT JOIN pkg_provider ON pkg_trunk.id_provider = pkg_provider.id" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                WHERE pkg_plan.id=6 AND pkg_rate.status = 1 AND ((prefix='551195' OR prefix='55119' OR prefix='5511' OR prefix='551' OR prefix='55' OR prefix='5' ) OR (prefix LIKE '&_%' ESCAPE '&' AND '5511XXXXXXXXX'" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                REGEXP REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CONCAT('^', prefix, '$')," 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                'X', '[0-9]'), 'Z', '[1-9]'), 'N', '[2-9]'), '.', '.+'), '_', '')))" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "                ORDER BY LENGTH( prefix ) DESC " 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "NUMBER TRUNK FOUND1" 10
       > "/var/www/html/mbilling/agi.php": NUMBER TRUNK FOUND1
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "NUMBER TARIFF FOUND -> 1" 10
       > "/var/www/html/mbilling/agi.php": NUMBER TARIFF FOUND -> 1
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Credit 1.86" 20
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "timeout ->> 792" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "TIMEOUT->792 : minutes=13 - seconds=12" 6
       > "/var/www/html/mbilling/agi.php": TIMEOUT->792 : minutes=13 - seconds=12
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Trunk have channels limit" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << SET VARIABLE GROUP() "OPERADORA1-TDM"
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE SIPTRANSFER
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "DIAL sip/OPERADORA1-TDM/44444#5511XXXXXXXXX,60,TtL(792000:61000:30000)" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << EXEC DIAL sip/OPERADORA1-TDM/44444#5511XXXXXXXXX,60,TtL(792000:61000:30000)
    -- AGI Script Executing Application: (DIAL) Options: (sip/OPERADORA1-TDM/44444#5511XXXXXXXXX,60,TtL(792000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 792000 ms (792.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    =
       > warning_sound  = timeleft
       > end_sound      =
  == Using SIP RTP CoS mark 5
    -- Called sip/OPERADORA1-TDM/44444#5511XXXXXXXXX
    -- Got SIP response 503 "Service Unavailable" back from yyy.yyy.yyy.yyy:5060
    -- SIP/OPERADORA1-TDM-0000000a is circuit-busy
  == Everyone is busy/congested at this time (1:0/1/0)
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE ANSWEREDTIME
<SIP/20201919-00000009>AGI Tx >> 200 result=1 ()
<SIP/20201919-00000009>AGI Rx << GET VARIABLE DIALSTATUS
<SIP/20201919-00000009>AGI Tx >> 200 result=1 (CONGESTION)
<SIP/20201919-00000009>AGI Rx << VERBOSE "K=0 -> ANSWEREDTIME=0-DIALSTATUS=CONGESTION" 10
       > "/var/www/html/mbilling/agi.php": K=0 -> ANSWEREDTIME=0-DIALSTATUS=CONGESTION
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE SIPTRANSFER
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "DIAL sip/OPERADORA-TDM/555555511XXXXXXXXX,60,TtL(792000:61000:30000)" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << EXEC DIAL sip/OPERADORA-TDM/555555511XXXXXXXXX,60,TtL(792000:61000:30000)
    -- AGI Script Executing Application: (DIAL) Options: (sip/OPERADORA-TDM/555555511XXXXXXXXX,60,TtL(792000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 792000 ms (792.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    =
       > warning_sound  = timeleft
       > end_sound      =
  == Using SIP RTP CoS mark 5
    -- Called sip/OPERADORA-TDM/555555511XXXXXXXXX
       > 0x7f3550013f50 -- Strict RTP learning after remote address set to: yyy.yyy.yyy.yyy:28422
    -- SIP/OPERADORA-TDM-0000000b is making progress passing it to SIP/20201919-00000009
       > 0x7f34cc08fa60 -- Strict RTP switching to RTP target address xxx.xxx.xxx.xxx:4004 as source
       > 0x7f3550013f50 -- Strict RTP switching to RTP target address yyy.yyy.yyy.yyy:28422 as source
    -- SIP/OPERADORA-TDM-0000000b is ringing
    -- SIP/OPERADORA-TDM-0000000b is making progress passing it to SIP/20201919-00000009
       > 0x7f34cc08fa60 -- Strict RTP learning complete - Locking on source address xxx.xxx.xxx.xxx:4004
       > 0x7f3550013f50 -- Strict RTP learning complete - Locking on source address yyy.yyy.yyy.yyy:28422
    -- SIP/OPERADORA-TDM-0000000b answered SIP/20201919-00000009
    -- Channel SIP/OPERADORA-TDM-0000000b joined 'simple_bridge' basic-bridge <477f4080-468f-464a-be83-2f28d2516487>
    -- Channel SIP/20201919-00000009 joined 'simple_bridge' basic-bridge <477f4080-468f-464a-be83-2f28d2516487>
    -- Channel SIP/20201919-00000009 left 'simple_bridge' basic-bridge <477f4080-468f-464a-be83-2f28d2516487>
<SIP/20201919-00000009>AGI Tx >> 200 result=-1
    -- Channel SIP/OPERADORA-TDM-0000000b left 'simple_bridge' basic-bridge <477f4080-468f-464a-be83-2f28d2516487>
<SIP/20201919-00000009>AGI Rx << GET VARIABLE ANSWEREDTIME
<SIP/20201919-00000009>AGI Tx >> 200 result=1 (4)
<SIP/20201919-00000009>AGI Rx << GET VARIABLE DIALSTATUS
<SIP/20201919-00000009>AGI Tx >> 200 result=1 (ANSWER)
<SIP/20201919-00000009>AGI Rx << VERBOSE "FAILOVER app_callingcard: Dialing '' with timeout of '792'." 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "[FAILOVER K=0]:[ANSTIME=4-DIALSTATUS=ANSWER" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "USED TARIFF=0" 10
       > "/var/www/html/mbilling/agi.php": USED TARIFF=0
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Update System" 6
       > "/var/www/html/mbilling/agi.php": Update System
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "CALCULCOST: K=0 - CALLDURATION:4 - freetimetocall_used=0" 10
       > "/var/www/html/mbilling/agi.php": CALCULCOST: K=0 - CALLDURATION:4 - freetimetocall_used=0
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "CALCULCOST: 1. COST: $cost = (30/60) * 0.14 " 10
       > "/var/www/html/mbilling/agi.php": CALCULCOST: 1. COST: $cost = (30/60) * 0.14
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "CALCULCOST: K=0 - BUYCOST:0.055 - SELLING COST:0.07" 10
       > "/var/www/html/mbilling/agi.php": CALCULCOST: K=0 - BUYCOST:0.055 - SELLING COST:0.07
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "$this->lastbuycost = 0.055" 10
       > "/var/www/html/mbilling/agi.php": $this->lastbuycost = 0.055
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "$this->lastcost = 0.07" 10
       > "/var/www/html/mbilling/agi.php": $this->lastcost = 0.07
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Sessiontime4" 10
       > "/var/www/html/mbilling/agi.php": Sessiontime4
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "CALL: used tariff K=0 - (sessiontime=4 :: dialstatus=ANSWER)" 10
       > "/var/www/html/mbilling/agi.php": CALL: used tariff K=0 - (sessiontime=4 :: dialstatus=ANSWER)
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "1 0.07+0 = 0.07" 25
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE IDPREFIX
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "Update credit username 52522, 0.07" 6
       > "/var/www/html/mbilling/agi.php": Update credit username 52522, 0.07
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE IDCALLBACK
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "Insert call on CDR" 10
       > "/var/www/html/mbilling/agi.php": Insert call on CDR
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << exception 'CException' with message 'Property "Call.sessionid" is not defined.' in /var/www/html/mbilling/yii/framework/base/CComponent.php:173
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << Stack trace:
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #0 /var/www/html/mbilling/yii/framework/db/ar/CActiveRecord.php(159): CComponent->__set('sessionid', 'SIP/20201919-00...')
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #1 /var/www/html/mbilling/protected/components/AGI/Calc.php(556): CActiveRecord->__set('sessionid', 'SIP/20201919-00...')
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #2 /var/www/html/mbilling/protected/components/AGI/StandardCallAgi.php(34): Calc->updateSystem(Object(Magnus), Object(AGI))
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #3 /var/www/html/mbilling/protected/commands/MagnusCommand.php(139): StandardCallAgi->processCall(Object(Magnus), Object(AGI), Object(Calc))
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #4 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(67): MagnusCommand->run(Array)
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #5 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run(Array)
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #6 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #7 /var/www/html/mbilling/agi.php(11): CApplication->run()
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
<SIP/20201919-00000009>AGI Rx << #8 {main}
<SIP/20201919-00000009>AGI Tx >> 510 Invalid or unknown command
    -- <SIP/20201919-00000009>AGI Script /var/www/html/mbilling/agi.php completed, returning 4
  == Spawn extension (billing, XXXXXXXXX, 1) exited non-zero on 'SIP/20201919-00000009'
    -- Executing [h@billing:1] AGI("SIP/20201919-00000009", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
<SIP/20201919-00000009>AGI Tx >> agi_request: /var/www/html/mbilling/agi.php
<SIP/20201919-00000009>AGI Tx >> agi_channel: SIP/20201919-00000009
<SIP/20201919-00000009>AGI Tx >> agi_language: br
<SIP/20201919-00000009>AGI Tx >> agi_type: SIP
<SIP/20201919-00000009>AGI Tx >> agi_uniqueid: 1571313333.15
<SIP/20201919-00000009>AGI Tx >> agi_version: 13.20.0
<SIP/20201919-00000009>AGI Tx >> agi_callerid: 20201919
<SIP/20201919-00000009>AGI Tx >> agi_calleridname: 20201919
<SIP/20201919-00000009>AGI Tx >> agi_callingpres: 0
<SIP/20201919-00000009>AGI Tx >> agi_callingani2: 0
<SIP/20201919-00000009>AGI Tx >> agi_callington: 0
<SIP/20201919-00000009>AGI Tx >> agi_callingtns: 0
<SIP/20201919-00000009>AGI Tx >> agi_dnid: XXXXXXXXX
<SIP/20201919-00000009>AGI Tx >> agi_rdnis: unknown
<SIP/20201919-00000009>AGI Tx >> agi_context: billing
<SIP/20201919-00000009>AGI Tx >> agi_extension: h
<SIP/20201919-00000009>AGI Tx >> agi_priority: 1
<SIP/20201919-00000009>AGI Tx >> agi_enhanced: 0.0
<SIP/20201919-00000009>AGI Tx >> agi_accountcode: 52522
<SIP/20201919-00000009>AGI Tx >> agi_threadid: 139867609052928
<SIP/20201919-00000009>AGI Tx >>
<SIP/20201919-00000009>AGI Rx << VERBOSE "" 5
       > "/var/www/html/mbilling/agi.php":
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Start MBilling AGI" 5
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE IDCALLBACK
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE CIDCALLBACK
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE MEMBERNAME
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE QUEUEPOSITION
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE PHONENUMBER_ID
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << GET VARIABLE SPY
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "Check If Is Did h" 10
       > "/var/www/html/mbilling/agi.php": Check If Is Did h
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << GET VARIABLE SECCALL
<SIP/20201919-00000009>AGI Tx >> 200 result=0
<SIP/20201919-00000009>AGI Rx << VERBOSE "CALL TO PSTN" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "AuthenticateUser 52522" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "Try accountcode authentication 52522" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "AUTHENTICATION BY ACCOUNTCODE:52522" 6
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:52522
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << SET VARIABLE CHANNEL(language) "br"
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "use_dnid:1 && len_dnid:(1 || len_exten:1 ) && (try_num:0)" 15
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "USE_DNID DESTINATION -> h" 10
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> h
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << VERBOSE "prepaid-invalid-digits" 3
    -- "/var/www/html/mbilling/agi.php": prepaid-invalid-digits
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << ANSWER
<SIP/20201919-00000009>AGI Tx >> 511 Command Not Permitted on a dead channel or intercept routine
<SIP/20201919-00000009>AGI Rx << STREAM FILE prepaid-invalid-digits "#" 0
<SIP/20201919-00000009>AGI Tx >> 511 Command Not Permitted on a dead channel or intercept routine
<SIP/20201919-00000009>AGI Rx << VERBOSE "Hangup Call h Username 52522" 6
       > "/var/www/html/mbilling/agi.php": Hangup Call h Username 52522
<SIP/20201919-00000009>AGI Tx >> 200 result=1
<SIP/20201919-00000009>AGI Rx << HANGUP
<SIP/20201919-00000009>AGI Tx >> 511 Command Not Permitted on a dead channel or intercept routine
    -- <SIP/20201919-00000009>AGI Script /var/www/html/mbilling/agi.php completed, returning 0

0

**Print**

[https://ibb.co/QKJJ7k4](url)

**Comment by magnussolution** [comment]
alterar no extension_magnus.conf de  /var/www/html/mbilling/agi.ph para /var/www/html/mbilling/resources/asterisk/mbilling.php
