### ISSUE TITLE
recording of calls made by the user via DID

### ISSUE THREAD

**Issue by Madji** [magnussolution/magnusbilling#339]
**Describe the bug**
There is no recording of calls made by the user through DID, regardless of the recording settings enabled for this user

**To Reproduce**
1. Go to  user and enable call record
2. Assign the user DID
3. Assign DID to the CALLINGCARD
4.The user calls to this DID, is authorized with a pin code, makes an outgoing call.
5.We go and look, record in cdr is correct (1 entering on DID, 2 record proceeding through the tariff plan and a trunk), and there is no record. Not in the folder, nowhere.

**Comment by magnussolution** [comment]
hi, we add a campaign to add the Record call option on the DID menu, to avoid issue

https://www.magnussolution.com/campaign/campaign.php?lang=en&id=17
