### ISSUE TITLE
Não grava CDR quando desconectado durante chamada

### ISSUE THREAD

**Issue by saggerbr** [magnussolution/magnusbilling#340]
CDR não é registrado quando a chamada é desconectada durante a ligação.

Durante a ligação, operadora A desconecta chamada originada pela conta SIP, gerando audio "Este numero não existe". Esta mesma chamada não é gravada no CDR como chamada realizada.

Normalmente as chamadas variam acima de 2 minutos de conversacao.

**Comment by magnussolution** [comment]
por favor enviar LOG da chamada com versobe minimo de 25

att
