### ISSUE TITLE
Error Property "GroupUser.user_prefix" is not defined.

### ISSUE THREAD

**Issue by heldigard** [magnussolution/magnusbilling#347]
**Describe the bug**
When I go to the Menu: Configurations -> User Group
And select any user group to Change the Permissions Modules when press the 'Save' it shows the error: Property "GroupUser.user_prefix" is not defined.

**To Reproduce**
1. Go to 'Configurations -> User Group'
2. Click on 'User'
3. Go to 'Permissions' 
4. Uncheck any 'Module Section'
5. Click on 'Save' 
4. See error: 'Property "GroupUser.user_prefix" is not defined.'

**Expected behavior**
Changed permissions of  the Module Views for the User Group.

**Screenshots**
![ErrorMagnusBilling7_UserGroup](https://user-images.githubusercontent.com/48439676/71225579-0d862780-22a7-11ea-984b-a691a0603997.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 65.0.3467.72

**Smartphone (please complete the following information):**
 - Device: Asus Zendphone 3
 - OS: Android 8.0
 - Browser Opera
 - Version 55.1.2719.50626

**Additional context**
Server running:
- Ubuntu 18.04.3
- PHP 7.0.33-14+ubuntu18.04.1+deb.sury.org+1
- 10.1.43-MariaDB-0ubuntu0.18.04.1.

Thank for the great work, it is an excelent software.

**Comment by magnussolution** [comment]
hi, please update your magnusbilling and try again
