### ISSUE TITLE
Filter of Provider rates in magus 7 is not working

### ISSUE THREAD

**Issue by uzair329** [magnussolution/magnusbilling#348]
**Describe the bug**
Filter of Provider rates in magus 7 is not working

**To Reproduce**
1. Go to 'routes'
2. Click on 'provider rates'
3. Scroll down to 'provider column and try to filter and specific provider you will see all the pages will become same'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by magnussolution** [comment]
update your server and try again
