### ISSUE TITLE
Erro Instalação Centos 7

### ISSUE THREAD

**Issue by mazinholeal** [magnussolution/magnusbilling#349]
**Describe the bug**
Foi realizado instalação em máquina fisica, VirtualBox, AWS e UOLHOST, mas quando termina a instalação e vai tentar se logar no sistema não é possível, fica apenas carregando a pagina. A 3 dias estava normal.

![image](https://user-images.githubusercontent.com/13786760/72687054-558caa00-3af2-11ea-98ff-cee72513b9f2.png)

**To Reproduce**
cd /usr/src/
yum -y install wget
wget https://raw.githubusercontent.com/magnussolution/magnusbilling/master/script/install.sh
chmod +x install.sh
./install.sh

**Atualização**
Tentei atualizar com o script /var/www/html/mbilling/protected/commands/update.sh 
E apresentou o seguinte erro.

![image](https://user-images.githubusercontent.com/13786760/72687252-f0d24f00-3af3-11ea-96ea-7eb1704f5aaa.png)

**Comment by magnussolution** [comment]
por favor testar novamente.

**Comment by mazinholeal** [comment]
Funcionou.
