### ISSUE TITLE
MB 7 NÃO aceita Expressão Regular nas Chamadas

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#352]
O MB 7.1 não aceita expressão regular colocadas na lista de tarifas para efetuar, após colocar a exp regular certa ele não entende e manda o numero sem o 55 e DD para o tronco. No MB 6 funciona perfeitamente aliviando o banco de dados.

Provavelmente teremos problemas para tarifar DID.

Seguem os logs AGI das ligações.

[ligacao-local-celular.txt](https://github.com/magnussolution/magnusbilling/files/4137742/ligacao-local-celular.txt)

[liga-cel.txt](https://github.com/magnussolution/magnusbilling/files/4137753/liga-cel.txt)

![image](https://user-images.githubusercontent.com/28572532/73515443-143ea900-43d4-11ea-9e3a-59d72765367f.png)

![image](https://user-images.githubusercontent.com/28572532/73515473-30dae100-43d4-11ea-9dc6-030bd0d227ac.png)

**Comment by magnussolution** [comment]
foi retirado isso do MagnusBilling 7 porque so servia para confundir os usuários, mas foi retirado porque a consulta no mysql para consultar tarifas com expressão deixava muito lento. Claro que so sentia este problema quem tinha muita chamada.
