### ISSUE TITLE
No signup email

### ISSUE THREAD

**Issue by weconexsas** [magnussolution/magnusbilling#356]
Hello, 

Enable the registration button is working, in fact, the user registers, but does not send a confirmation email to the user or the administrator, on the other hand, the password field is not "Password" type, everyone can see the password if you are in a public place.

The terms and conditions are not updated when they are added in the settings, clicking on the "read terms" link sends you to google.com

We greatly appreciate your time.

Thank you.

**Comment by voiptelecom** [comment]
Yes, this is not working very well.

I have going in into the database to change a few things and modify de code too.

**Comment by magnussolution** [comment]
have you configered the SMTP on Configruation menu, and test if work ok?

**Comment by hmoghani** [comment]
I have tested the SMTP. When I try testing it, it just stays there loading forever, but it sends the email.

**Comment by magnussolution** [comment]
fixes, please update
