### ISSUE TITLE
Queue Issue

### ISSUE THREAD

**Issue by ahm3ds4l3m** [magnussolution/magnusbilling#358]
**Describe the bug**
I have few agents, and when I start receiving calls to the queue it works well for a few calls then the calls stop dropping to the agent's SIP Accounts and to start getting calls again I have to unregister then register the SIP Account again.

**To Reproduce**
1. Create queue
2. Set queue strategy to Ringall
3. Set ringinuse to NO
4. Receive incoming calls to the queue
5. Answer a few calls then hangup
6. See that calls are stuck in the waiting list for queue but don't drop to the SIP Accounts

**Expected behavior**
It should always drop calls to the available SIP Accounts.

**Screenshots**
<img width="1038" alt="Screen Shot 2020-04-03 at 18 48 45" src="https://user-images.githubusercontent.com/38384640/78382474-9c614a80-75df-11ea-8cc9-c8738a443533.png">

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
Just a NOTE, the SIP Accounts ( qualify ) set to YES.

**Comment by magnussolution** [comment]
probably your sipaccount lost the connection with your server, please check on the softphone(sip device) per a option called Register every or Register timeout, and se it to 60 seconds.
