### ISSUE TITLE
Queue HungUP

### ISSUE THREAD

**Issue by itamarso** [magnussolution/magnusbilling#359]
**Describe the bug**
Ao encaminhar ligação para uma fila, quando o agent atende a ligação é finalizada.
Segue o log do erro.

vpx*CLI>
  == Using SIP RTP CoS mark 5
       > 0x7fd260006080 -- Strict RTP learning after remote address set to: XXX.XXX.XXX.XXX:37542
    -- Executing [35997082@billing:1] AGI("SIP/Use_Covid_19-00000007", ""/var/www/html/mbilling/resources/asterisk/mbilling.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/resources/asterisk/mbilling.php
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Start MBilling AGI
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id, config_key , config_value , config_group_title  FROM pkg_configuration
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Start MBilling AGI
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Check If Is Did 35997082
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_did WHERE did = '35997082' AND activated = 1 LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Is a DID call
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_did_destination WHERE activated = 1 AND id_did = '6' ORDER BY priority
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Did have destination
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_user WHERE id = 4 LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id FROM pkg_prefix WHERE prefix = SUBSTRING('35997082',1,length(prefix))
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                                     ORDER BY LENGTH(prefix) DESC
 "/var/www/html/mbilling/resources/asterisk/mbilling.php": Not found prefix to DID 35997082
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_trunk WHERE trunkcode = 'Use_Covid_19' LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id FROM pkg_restrict_phone WHERE  direction = 2 AND id_user = 4
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         AND number = SUBSTRING('71999526414',1,length(number)) ORDER BY LENGTH(number) DESC
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": RESTRICTED NUMBERS
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": didCallCost
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Array
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": (
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id] => 10
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_user] => 4
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_ivr] => 0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_sip] => 0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_queue] => 2
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_did] => 6
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [destination] =>
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [priority] => 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [creationdate] => 2020-04-20 13:13:48
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [activated] => 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [secondusedreal] => 0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [voip_call] => 7
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": )
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": CallerID Match regular expression 1 71999526414
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": DID 35997082
    -- AGI Script Executing Application: (SET) Options: (CALLERID(name)=35997082)
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": try blocked

> "/var/www/html/mbilling/resources/asterisk/mbilling.php": voip_call 7
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Queue module
       > 0x7fd260006080 -- Strict RTP switching to RTP target address xxx.xxx.xxx.xxx:37542 as source
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT  *, pkg_queue.id AS id, pkg_queue.id_user AS id_user  FROM pkg_queue
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                             LEFT JOIN pkg_user ON pkg_queue.id_user = pkg_user.id
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                             WHERE pkg_queue.id = 2 LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": INSERT INTO pkg_queue_status (id_queue, callId, queue_name, callerId, time, channel, status)
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         VALUES (2, '1587399243.7', 'Suporte', '71999526414',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '2020-04-20 13:14:03', 'SIP/Use_Covid_19-00000007', 'ringing')
"/var/www/html/mbilling/resources/asterisk/mbilling.php": Queue
    -- AGI Script Executing Application: (Queue) Options: (Suporte,tc,,,,/var/www/html/mbilling/resources/asterisk/mbilling.php)
    -- Started music on hold, class 'default', on channel 'SIP/Use_Covid_19-00000007'
  == Using SIP RTP CoS mark 5
    -- Called SIP/7082
    -- SIP/7082-00000008 connected line has changed. Saving it until answer for SIP/Use_Covid_19-00000007
    -- SIP/7082-00000008 is ringing
       > 0x7fd260006080 -- Strict RTP learning complete - Locking on source address xxx.xxx.xxx.xxx:37542
       > 0x7fd2d4022460 -- Strict RTP learning after remote address set to: 172.16.121.10:6000
    -- SIP/7082-00000008 connected line has changed. Saving it until answer for SIP/Use_Covid_19-00000007
    -- SIP/7082-00000008 answered SIP/Use_Covid_19-00000007
    -- Stopped music on hold on SIP/Use_Covid_19-00000007
    -- Launched AGI Script /var/www/html/mbilling/resources/asterisk/mbilling.php
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: Start MBilling AGI
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT id, config_key , config_value , config_group_title  FROM pkg_configuration
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: Start MBilling AGI
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT * FROM pkg_sip WHERE name = '35997082' OR (alias = '35997082' AND accountcode = '') LIMIT 1
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: CALL TO SIP
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT * FROM pkg_user WHERE id = 4 LIMIT 1
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT removeinterprefix, play_audio, portabilidadeMobile, portabilidadeFixed, tariff_limit  FROM pkg_plan WHERE id = 1 LIMIT 1
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT * FROM pkg_sip WHERE name = 'Use_Covid_19' LIMIT 1
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: DIAL SIP/35997082,60,TtiL(3600000:61000:30000)
    -- AGI Script Executing Application: (DIAL) Options: (SIP/35997082,60,TtiL(3600000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 3600000 ms (3600.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    =
       > warning_sound  = timeleft
       > end_sound      =
    -- No devices or endpoints to dial (technology/resource)
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: [7135997082 Friend]:[ANSWEREDTIME=-DIALSTATUS=CHANUNAVAIL]
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT * FROM pkg_sip WHERE name = '35997082' LIMIT 1
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: SELECT voicemail FROM pkg_sip WHERE name = '35997082' LIMIT 1

> /var/www/html/mbilling/resources/asterisk/mbilling.php: INSERT INTO pkg_cdr_failed (uniqueid,id_user,calledstation,id_plan,id_trunk,callerid,src,
       > /var/www/html/mbilling/resources/asterisk/mbilling.php:                         starttime, terminatecauseid,sipiax,id_prefix) VALUES ('1587399243.7', '4','35997082','1',
       > /var/www/html/mbilling/resources/asterisk/mbilling.php:                         '','71999526414', 'Use_Covid_19',
       > /var/www/html/mbilling/resources/asterisk/mbilling.php:                         '2020-04-20 13:14:11', '6','1','')
       > /var/www/html/mbilling/resources/asterisk/mbilling.php: Hangup Call 35997082 Username 7135997082
    -- AGI Script Executing Application: (HANGUP) Options: (34)
    -- <SIP/Use_Covid_19-00000007>AGI Script /var/www/html/mbilling/resources/asterisk/mbilling.php completed, returning 4
    -- Channel SIP/7082-00000008 joined 'simple_bridge' basic-bridge <55d2e166-a067-4fd3-955b-ee155d52f93d>
    -- Channel SIP/Use_Covid_19-00000007 joined 'simple_bridge' basic-bridge <55d2e166-a067-4fd3-955b-ee155d52f93d>
    -- Channel SIP/Use_Covid_19-00000007 left 'simple_bridge' basic-bridge <55d2e166-a067-4fd3-955b-ee155d52f93d>
    -- Channel SIP/7082-00000008 left 'simple_bridge' basic-bridge <55d2e166-a067-4fd3-955b-ee155d52f93d>
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Array
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": (
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [0] => 1587399251
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [1] => 1587399243.7
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [2] => Suporte
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [3] => SIP/7082
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [4] => CONNECT
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [5] => 8
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [6] => 1587399243.8
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [7] => 7
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": )
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": DELETE FROM pkg_queue_status WHERE callId = 1587399243.7
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": $siptransfer =>
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": billDidCall, sell_price=0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":  answeredtime = 8 sell_price = 0 connection_sell = 0.00000
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id FROM pkg_prefix WHERE prefix = SUBSTRING('35997082',1,length(prefix))
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                                 ORDER BY LENGTH(prefix) DESC
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": INSERT INTO pkg_cdr (uniqueid,id_user,calledstation,id_plan,callerid,src,
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         starttime,sessiontime,real_sessiontime, terminatecauseid,sessionbill,
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         sipiax,buycost) VALUES ('1587399243.7', 4, '35997082', 1, '71999526414',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '7082',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '2020-04-20 13:14:03', '8',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '8', '1', '0',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '8','0')
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Hangup Call 35997082 Username 7135997082
    -- AGI Script Executing Application: (HANGUP) Options: (34)

-- <SIP/Use_Covid_19-00000007>AGI Script /var/www/html/mbilling/resources/asterisk/mbilling.php completed, returning 4
  == Spawn extension (billing, 35997082, 1) exited non-zero on 'SIP/Use_Covid_19-00000007'
    -- Executing [h@billing:1] Hangup("SIP/Use_Covid_19-00000007", "") in new stack
  == Spawn extension (billing, h, 1) exited non-zero on 'SIP/Use_Covid_19-00000007'
vpx*CLI>

**To Reproduce**
1. Create queue
2. Set queue strategy to Ringall
3. Set ringinuse to NO
4. Receive incoming calls to the queue

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ahm3ds4l3m** [comment]
`-- No devices or endpoints to dial (technology/resource)`

I see that you have a problem with the call routing
Please share more information about your issue in English.
