### ISSUE TITLE
ERRO: Quando URA encaminha para QUEUE

### ISSUE THREAD

**Issue by wezee-me** [magnussolution/magnusbilling#360]
**Describe the bug**
Quando chamada de entrada para URA, atende a chamada, executa audio e aguarda digito. Porém quando é encaminhado para alguma QUEUE a chamada é Desconectada (HUNGUP). Quando opção é para SIP ou número externo, a opção é completada normalmente.

**To Reproduce**
1. Dicando para DID de entrada
2. URA atende e executa Audio
3. Pressiona opcao onde encaminha para fila ou aguarda opcao default onde encaminha pra fila
4. Chamada é desconectada (Hungup)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Console verbose was OFF and is now 25.
  == Using SIP RTP CoS mark 5
       > 0x7fc3e8033c50 -- Strict RTP learning after remote address set to: 131.xxx.xxx.166:29578
    -- Executing [55xx3142xxxx@billing:1] AGI("SIP/VN-ITX-BR-00000000", ""/var/www/html/mbilling/resources/asterisk/mbilling.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/resources/asterisk/mbilling.php
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Start MBilling AGI
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id, config_key , config_value , config_group_title  FROM pkg_configuration
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Start MBilling AGI
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Check If Is Did 55xx3142xxxx
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_did WHERE did = '55xx3142xxxx' AND activated = 1 LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Is a DID call
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_did_destination WHERE activated = 1 AND id_did = '72' ORDER BY priority
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Did have destination
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_user WHERE id = 27 LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id FROM pkg_prefix WHERE prefix = SUBSTRING('55xx3142xxxx',1,length(prefix))
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                                     ORDER BY LENGTH(prefix) DESC
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT * FROM pkg_trunk WHERE trunkcode = 'VN-ITX-BR' LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT id FROM pkg_restrict_phone WHERE  direction = 2 AND id_user = 27
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         AND number = SUBSTRING('55xx99771xxxx',1,length(number)) ORDER BY LENGTH(number) DESC
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": RESTRICTED NUMBERS 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": didCallCost
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Array
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": (
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id] => 104
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_user] => 27
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_ivr] => 31
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_sip] => 4
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_queue] => 0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [id_did] => 72
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [destination] => 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [priority] => 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [creationdate] => 2020-04-28 14:58:53
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [activated] => 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [secondusedreal] => 2496
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [voip_call] => 2
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": )
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": CallerID Match regular expression 1 55xx99771xxxx
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": DID 55xx3142xxxx
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": try blocked
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": voip_call 2
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Ivr module
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": DID IVR - CallerID=55xx99771xxxx -> DID=55xx3142xxxx
       > 0x7fc3e8033c50 -- Strict RTP switching to RTP target address 131.xxx.xxx.166:29578 as source
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT *, pkg_ivr.id id, pkg_ivr.id_user id_user FROM pkg_ivr LEFT JOIN pkg_user ON pkg_ivr.id_user = pkg_user.id WHERE pkg_ivr.id = 31 LIMIT 1
 "/var/www/html/mbilling/resources/asterisk/mbilling.php": EXECUTE IVR 10001 - URA
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT name FROM pkg_sip WHERE id_user = 27 AND name REGEXP '^[0-9]*$' ORDER BY LENGTH(name) DESC LIMIT 1
    -- <SIP/VN-ITX-BR-00000000> Playing '/usr/local/src/magnus//sounds/idIvrDidWork_31.slin' (language 'br')
       > 0x7fc3e8033c50 -- Strict RTP learning complete - Locking on source address 131.xxx.xxx.166:29578
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": option
 "/var/www/html/mbilling/resources/asterisk/mbilling.php": DEFAULT OPTION
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": CUSTOMER PRESS queue -> 26
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Queue module
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT  *, pkg_queue.id AS id, pkg_queue.id_user AS id_user  FROM pkg_queue
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                             LEFT JOIN pkg_user ON pkg_queue.id_user = pkg_user.id
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                             WHERE pkg_queue.id = 26 LIMIT 1 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": INSERT INTO pkg_queue_status (id_queue, callId, queue_name, callerId, time, channel, status)
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         VALUES (26, '1588422852.0', ‘Fila-Telefonista', '55xx99771xxxx',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '2020-05-02 09:34:44', 'SIP/VN-ITX-BR-00000000', 'ringing')
"/var/www/html/mbilling/resources/asterisk/mbilling.php": Queue
    -- AGI Script Executing Application: (Queue) Options: (Fila-Telefonista,tc,,,,/var/www/html/mbilling/resources/asterisk/mbilling.php)
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Array
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": (
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":     [0] => 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": )
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": EXEC StopMixMonitor (1588422852.0)
    -- AGI Script Executing Application: (StopMixMonitor) Options: ()
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": DELETE FROM pkg_queue_status WHERE callId = 1588422852.0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": $siptransfer => 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": FIM do loop
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": EXEC StopMixMonitor (1588422852.0)
    -- AGI Script Executing Application: (StopMixMonitor) Options: ()
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Hangup IVR call, send to call_did_billing
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": billDidCall, sell_price=0
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":  answeredtime = 28 sell_price = 0 connection_sell = 0.00000
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": SELECT name FROM pkg_sip WHERE name  = '' LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": INSERT INTO pkg_cdr (uniqueid,id_user,calledstation,id_plan,callerid,src,
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         starttime,sessiontime,real_sessiontime, terminatecauseid,sessionbill,
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         sipiax,buycost, id_trunk, id_prefix) VALUES ('1588422852.0', 27, '55xx3142xxxx', 1, '55xx99771xxxx',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '5511997715172',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '2020-05-02 09:34:16', '28',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '28', '1', '0',
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                         '3','0', 1, 70727) 
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": UPDATE pkg_did_destination SET secondusedreal = secondusedreal + 28
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                     WHERE  id = 104 LIMIT 1;
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                 UPDATE pkg_did SET secondusedreal = secondusedreal + 28
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php":                     WHERE  id = 72 LIMIT 1
       > "/var/www/html/mbilling/resources/asterisk/mbilling.php": Hangup Call 55xx3142xxxx Username 1010001
    -- AGI Script Executing Application: (HANGUP) Options: (34)
    -- <SIP/VN-ITX-BR-00000000>AGI Script /var/www/html/mbilling/resources/asterisk/mbilling.php completed, returning 4
  == Spawn extension (billing, 55xx3142xxxx, 1) exited non-zero on 'SIP/VN-ITX-BR-00000000'
    -- Executing [h@billing:1] Hangup("SIP/VN-ITX-BR-00000000", "") in new stack
  == Spawn extension (billing, h, 1) exited non-zero on 'SIP/VN-ITX-BR-00000000'

**Comment by itamarso** [comment]
estou com esse mesmo problema, já postei no grupo e registrei aqui sem sucesso.

**Comment by wezee-me** [comment]
Estou achando que o Adilson deve ter pegado COVID e alguém está tentando dar continuidade no código! Nunca mais deu as caras aqui nos ISSUES. Versão 7 também cheia de bugs e só fazem alteração nada a ver no código.

**Comment by wezee-me** [comment]
Aparentemente só ocorre em migrações da versão 6 para 7.
Instalações novas da versão 7 não ocorre o problema.
