### ISSUE TITLE
International Prefix

### ISSUE THREAD

**Issue by aliahanchi** [magnussolution/magnusbilling#363]
Hi, there is an issue in /var/www/html/panel/resources/asterisk/magnus.php 
the code always remove 00 from international prefix even if the setting configuration is set to not remove prefix.
Therefore if call rate imported with 00, call cannot be made since no rate has been found

**Comment by ahm3ds4l3m** [comment]
I would recommend you set your tariff without 00 then the call will pass without issues.

**Comment by magnussolution** [comment]
MagnusBilling as developed to us E164 format, so, you never use 00, 0 or any other format on tariffs, only E164.

https://en.wikipedia.org/wiki/E.164
