### ISSUE TITLE
DID Connectin Charge Decimale Value Can't Be Changed.

### ISSUE THREAD

**Issue by MShoaib67** [magnussolution/magnusbilling#365]
**Describe the bug**

Unable to change the decimal values for DID connection Fee. 

**To Reproduce**
Change decimal value to anything above 4 decimal

1. Go to ''DID"
2. Click on 'New'
3. Scroll down to 'Did increment'
4. Unable to have more then 3 decimal values in connection change.

**Expected behavior**

After changing the decimal value for system this should allow to put rates up to decimal value entered. 

![image](https://user-images.githubusercontent.com/10461055/85049764-9296be80-b1ae-11ea-999b-98a79c6e2ab8.png)

**Comment by magnussolution** [comment]
hi, it's not an issue, MagnusBilling by default every use 3 decimal, less in rates, where you can set the decimal length on Configuration menu.

**Comment by MShoaib67** [comment]
> 
> 
> hi, it's not an issue, MagnusBilling by default every use 3 decimal, less in rates, where you can set the decimal length on Configuration menu.

HI, After changing the decimal length on Configuration menu that doesn't work for DID menu. . That's the issue.
