### ISSUE TITLE
after install billing not opening http://your_ip/

### ISSUE THREAD

**Issue by adibtradelink** [magnussolution/magnusbilling#366]
?php 
header('Location: ./mbilling');
?>

showing

**Comment by adibtradelink** [comment]
## 
<?php 
header('Location: ./mbilling');
?>
##

**Comment by adibtradelink** [comment]
#<?php 
header('Location: ./mbilling');
?>#

**Comment by adibtradelink** [comment]
i m trying to show u php error but not showing

?php 
header('Location: ./mbilling');
?

**Comment by MShoaib67** [comment]
@adibtradelink All you'll need to double check if its installed correctly. No issues found while going through a fresh installation. 

Kind Regards,

**Comment by adibtradelink** [comment]
i have install it on cantos 7 64
i have try to again install on fresh OS but same issue

**Comment by magnussolution** [comment]
try http://your_ip/mbilling

**Comment by adibtradelink** [comment]
dear i have find out one thing billing only opening safari browser. other browser is not opening. what the issue for is this. and how to i fixed it

**Comment by MShoaib67** [comment]
@adibtradelink Their isn't any issue with MBilling related to this. Please check with your System / browser settings. If you want MBilling to have a look into your Server / System issue. Please book a support hour by one of MBilling support person & They'll have a look.

Kind Regards.

**Comment by magnussolution** [comment]
update your magnusbilling, use the bolow command
`/var/www/html/mbilling/protected/commands/update.sh`

**Comment by adibtradelink** [comment]
yes dear now working. i got some problem can u tell me the about how to see live call process way and another is how to i remove client balance if have added by wrong balance >?

**Comment by magnussolution** [comment]
> yes dear now working. i got some problem can u tell me the about how to see live call process way and another is how to i remove client balance if have added by wrong balance >?

to get help, please using the Telegram group https://t.me/joinchat/NXwoZRPGpG6rPqp3yssLzQ
