### ISSUE TITLE
Magnus 7 update not working properly

### ISSUE THREAD

**Issue by uzair329** [magnussolution/magnusbilling#367]
**trunk Group page not opening and trunks from table of rates/tariff got vanished when we update magnusbilling 7 today **
Today when we update magnus billing 7 by running the command update.sh in cd /var/www/html/mbilling/protected/commands/
path . Trunk group tab appears but it is not opening and we have also faced that trunk from table of rates/tariff got vanished we try assign trunk again buts its not showing

![image](https://user-images.githubusercontent.com/59938185/85902208-ec396180-b81c-11ea-9fef-28bd3f709ef4.png)

**Comment by itsshimmer** [comment]
Clear all browser data and try again
