### ISSUE TITLE
Forma de discagem

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#37]
Olá, reinstalei o Magnusbilling6 ontem a noite e subi a mesma tarifa/prefixo utilizado na versao 5. a tarifa esta cadastrada da seguinte forma: 55+DDD, na versao 5 se eu digitar 55+DDD+numero completa se eu digitar 0+ddd+numero tambem completa normal ja na versão 6 só completa se eu digitar 55+DDD+Numero. Segue-se o log da ligação.
![log](https://user-images.githubusercontent.com/30841526/30338504-3fbd7090-97c2-11e7-9f8c-612b4e8b9ffa.JPG)

**Comment by magnussolution** [comment]
Esta funcionando corretamente. Provavelmente vc não colocou a regra do prefixo local no usuário.
