### ISSUE TITLE
Problema ao Demonstrar o Hardware

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#370]
Segue abaixo o problema ao demonstrar a CPU na tela Inicial do MB 7.3.1, não tenho essa CPU.

![image](https://user-images.githubusercontent.com/28572532/86502474-ec37e500-bd79-11ea-9f5a-41f804aff046.png)

**Comment by magnussolution** [comment]
Bom dia!!!!

A informaçao do CPU é a que esta em /proc/cpuinfo

att.

**Comment by yurikurka** [comment]
Efetuei um cat no /proc/cpuinfo e retornou corretamente, porem na interface grafica não retorna a mesmas informações!
Veja as fotos abaixo.

![image](https://user-images.githubusercontent.com/28572532/86860502-5a8ee700-c09b-11ea-82c2-6dd1fec3c1de.png)


![image](https://user-images.githubusercontent.com/28572532/86860525-62e72200-c09b-11ea-8ada-a681d35ba42d.png)

**Comment by yurikurka** [comment]
Memória todos os dados do hardrware são informados errados.

![image](https://user-images.githubusercontent.com/28572532/86860729-ca04d680-c09b-11ea-9655-e7dec3deb8c3.png)

**Comment by voiptelecom** [comment]
Having the same issue

**Comment by magnussolution** [comment]
bom dia, em nenhum dos servidores que eu tenho para teste acontece isso. 

Detalhe importante. Em nenhum lugar do codigo existe um modelo de processador, pode procurar no codigo pela palavra intel(R), e nao vai encontrar, isso quer dizer que este modelo de processador nao saiu do nada. Teria que analisar para ver de onde que saiu, mas como nao consegui simular, entao nao tenho como debugar.

**Comment by voiptelecom** [comment]
This is my dashboard

![Captura de Pantalla 2020-07-09 a la(s) 13 17 37](https://user-images.githubusercontent.com/62485767/87065019-dea1b580-c1e6-11ea-8a45-14268b3da378.png)

This is my htop

![Captura de Pantalla 2020-07-09 a la(s) 13 16 10](https://user-images.githubusercontent.com/62485767/87065068-eeb99500-c1e6-11ea-8071-f1bc0c776a7a.png)

And this is my /proc/cpuinfo

![Captura de Pantalla 2020-07-09 a la(s) 13 18 56](https://user-images.githubusercontent.com/62485767/87065130-055fec00-c1e7-11ea-9c1c-3e6f731bcc18.png)

Yo let me know were is the issue...

**Comment by yurikurka** [comment]
Se voce quiser posso disponibilizar minha maquina para vc verificar, é só combinar e libero acesso root para vc.

**Comment by magnussolution** [comment]
pode ser, mande o acesso.
