### ISSUE TITLE
Stripe payment gateway doesn't work. 

### ISSUE THREAD

**Issue by hmoghani** [magnussolution/magnusbilling#371]
**Describe the bug**
Stripe payment gateway doesn't work. 
I have enabled the payment method, added client ID and secret. but when the customer wants to make a payment with stripe they see this error:

**********************************
Internal Server Error
Undefined variable: error

An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you. 
***********************************

**To Reproduce**
Add the stripe payment method and try to make a payment

**Expected behavior**
it should take you to stripe payment method

**Comment by magnussolution** [comment]
hello, I not have a account from Stripe. Can you send us the client and secret to teste? info@magnussolution.com

**Comment by voiptelecom** [comment]
Got this problem

![Captura de Pantalla 2020-07-12 a la(s) 03 33 13](https://user-images.githubusercontent.com/62485767/87240517-9bb32e00-c3f0-11ea-87d5-5539eaa99446.png)

**Comment by voiptelecom** [comment]
> Got this problem
> 
> ![Captura de Pantalla 2020-07-12 a la(s) 03 33 13](https://user-images.githubusercontent.com/62485767/87240517-9bb32e00-c3f0-11ea-87d5-5539eaa99446.png)

i'm working with test keys...

**Comment by magnussolution** [comment]
MagnusBilling use API V1, because when a user paid to implement Strip, the current version was 1, now it use V3 and V1 as disable from Stripe websit. If is important for you, you can hire out team to update Stripe payment gateway. Please check on http://www.magnussolution.com
