### ISSUE TITLE
Problemas no Menu Conta VOIP

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#373]
Segue abaixo problemas no menu (Conta voip) após clicar no submenu Additional os demais não funcionam.

[Problema no menu.zip](https://github.com/magnussolution/magnusbilling7/files/4930020/Problema.no.menu.zip)

**Comment by yurikurka** [comment]
[Problema no menu.zip](https://github.com/magnussolution/magnusbilling7/files/4930017/Problema.no.menu.zip)

**Comment by magnussolution** [comment]
ola, este erro nao esta acontecendo aqui, acabei de instalar um servidor novo para verificar, e nada.

Quando vc enviar ISSUE, tem que dar dados técnicos , como LOG, no caso de ser algo na WEB, entao enviar o erro do DEVELOPERTOOTLS no navegador.

att.
