### ISSUE TITLE
Caller ID set by softphone

### ISSUE THREAD

**Issue by shahrukhfiaz** [magnussolution/magnusbilling#375]
Hello guys, I have tried everything but could not find the solution of it

I am trying to configure it this way so I can change the CallerID directly from softphone using (Eyebeam, Xlite and Zoiper) by putting desired shown number on display name of softphone settings. but its not passing. 
please guide me how can i do this?

**Comment by shahrukhfiaz** [comment]
![image](https://user-images.githubusercontent.com/59414126/88345840-58e24600-cd60-11ea-9297-6a0f80430c9a.png)

**Comment by magnussolution** [comment]
hi, you can customize you billing context and set the CALLERID(nun) = CALLERID(name)

**Comment by shahrukhfiaz** [comment]
> hi, you can customize you billing context and set the CALLERID(nun) = CALLERID(name)

where to make these changes please guide would appreciate this

**Comment by shahrukhfiaz** [comment]
hello I added CALLERID(num) = CALLERID(name) in Context field but when i tried to make a call it said not found on Eyebeam

**Comment by magnussolution** [comment]
exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})

like it

**Comment by shahrukhfiaz** [comment]
![image](https://user-images.githubusercontent.com/59414126/88566856-11a1d100-d050-11ea-9248-ab6f807221d5.png)

When i call any number on softphone it gives not found error

**Comment by magnussolution** [comment]
no, you need to write your custom context on Asterisk file, extension_magnus.conf

**Comment by shahrukhfiaz** [comment]
how it would be? 
for example account name in magnus is camfirstuk for UK dialing

![image](https://user-images.githubusercontent.com/59414126/88584787-a4039e00-d06b-11ea-8d5b-eba536c09386.png)

**Comment by shahrukhfiaz** [comment]
I have tried this but still not working

![image](https://user-images.githubusercontent.com/59414126/88585549-a7e3f000-d06c-11ea-8c11-df51e999ae6c.png)

**Comment by shahrukhfiaz** [comment]
@magnussolution please help

**Comment by itsshimmer** [comment]
Now set the context in MagnusBilling to the name of your context. Also after setting the CID, forward the call to the billing context.

**Comment by xceedconnections** [comment]
i added 
[callerid]
exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})
Asterisk file, extension_magnus.conf

how to set the context in magnus billing and forward call to the billing context.

please show an example.

**Comment by foryourhost** [comment]
i already add this 

[dincli]
exten => _[*0-9].,1,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php$
  same => n,Hangup()

exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})

exten => h,1,hangup()


exten => *111,1,VoiceMailMain(${CHANNEL(peername)}@dincli)
  same => n,Hangup()

but error is happen

Executing [12158664168@dincli:1] Set("SIP/97833-00005160", "CALLERID(nun)                                                                                        =13342342407") in new stack
[2021-06-04 18:13:37] ERROR[2008][C-0000798d]: func_callerid.c:1271 callerid_wri                                                                                        te: Unknown callerid data type 'nun'.
    -- Executing [12158664168@dincli:2] Hangup("SIP/97833-00005160", "") in new                                                                                         stack
  == Spawn extension (dincli, 12158664168, 2) exited non-zero on 'SIP/97833-0000                                                                                        5160'
    -- Executing [h@dincli:1] Hangup("SIP/97833-00005160", "") in new stack
  == Spawn extension (dincli, h, 1) exited non-zero on 'SIP/97833-00005160'

**Comment by MrSuman403** [comment]
@magnussolution fix this issue

**Comment by xceedconnections** [comment]
Make nun to num in line

X.,1,Set(CALLERID(nun)=${CALLERID(name)})

Enter this first
And then the agi billing line on 2nd.
And hangup line on 3rd.
Should be working than.

**Comment by ponka123** [comment]
did anyone findout the solution for this issue ?

**Comment by shaheedghazi** [comment]
[billing]
exten => _[*0-9].,1,Set(CALLERID(num)=${CALLERID(name)}) ; Dynamically set CALLERID(num) from CALLERID(name)
  same => n,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php")
  same => n,Hangup()

exten => _+X.,1,Goto(billing,${EXTEN:1},1)

exten => h,1,Hangup()

exten => *111,1,VoiceMailMain(${CHANNEL(peername)}@billing)
  same => n,Hangup()

[trunk_answer_handler]
exten => s,1,Set(MASTER_CHANNEL(TRUNKANSWERTIME)=${EPOCH})
  same => n,Return()
  
  edit   /etc/asterisk/extensions_magnus.conf , make sure there is no outbound callerID set in extensions, and it works
