### ISSUE TITLE
There is no audio during the campaign

### ISSUE THREAD

**Issue by voiptelecom** [magnussolution/magnusbilling#376]
When creating the campaign and uploading the audios, there are two problems:

1) Audio does not play (even if the rules are complied with, be it GSM or WAV

2) When executing the campaign when the call is made, there is no audio playback as such, there is only silence and that's it.

**Comment by shahrukhfiaz** [comment]
try to compress the audio under 1MB

**Comment by magnussolution** [comment]
audio need be in .gsm or .wav 8000 mono. 

check on the asterisk log /var/log/asterisk/message 

asterisk will show an error if audio is in an invalid format.

**Comment by magnussolution** [comment]
we change the method to play the audio

check the commit [https://github.com/magnussolution/magnusbilling7/commit/9e103407896d9566a3488d39a6e42032a1d3a812](url)

now when you click in the Play icon, it will try to open the file on a new page, if browser can't play it will download the audio.
