### ISSUE TITLE
Torpedo de voz não esta funcinando

### ISSUE THREAD

**Issue by renatosabatini** [magnussolution/magnusbilling#377]
Criei uma campanha para fazer teste e estou tendo algumas dificuldades:
1 - Subi o arquivo de áudio .gsm, ele foi armazenado no diretorio /usr/local/src/magnus/sounds/idCampaign_2.gsm, mas quando rodamos o teste vimos que acontece um erro na execução:
![image](https://user-images.githubusercontent.com/68757900/88439170-d9488b80-cde0-11ea-847b-8a705bfb4a97.png)
Para fazer um teste copiei o arquivo que estava no diretório /usr/local/src/magnus/sounds/idCampaign_2.gsm para /var/www/html/mbilling/. após isto este erro parou de acontecer, o upload deveria acontecer em qual desses dois diretório?
Este erro da imagem acima ocorre também quando tenta ouvir o áudio.

2 - A campanha não esta funcionando, habilitei verbose e debug no AGI no asterisk. não pega nada, por algum motivo a campanha não esta chamando o asterisk:
![image](https://user-images.githubusercontent.com/68757900/88438936-2ed06880-cde0-11ea-9567-c72ca617cb91.png)

**Comment by magnussolution** [comment]
desconsidete este erro, o arquivo deve estar, e ficar no diretório /usr/local/src/magnus/sounds/

se seu torpedo não funciona, não é por este motivo. Analise os logs do asterisk

**Comment by renatosabatini** [comment]
Como relatei abaixo, não esta gerando nenhum log no asterisk, habilitei verbose e AGI debug e não pega nenhuma entrada.

**Comment by magnussolution** [comment]
atualize seu magnusbilling e execute o comando que esta no cron com o parâmetro logAll e veja se as chamadas estão sendo geradas pelo script

**Comment by renatosabatini** [comment]
O meu MagnusBilling esta na versõa 7.3.0.

[root@srv-datatel-centos7 commands]# php /var/www/html/mbilling/cron.php MassiveCall logAll

Found 1 Campaign

SEARCH NUMBER IN CAMPAIGN Teste
Found 0 Numbers in Campaign
NO PHONE FOR CALL



[root@srv-datatel-centos7 commands]# php /var/www/html/mbilling/cron.php MassiveCall logAll

Found 1 Campaign

SEARCH NUMBER IN CAMPAIGN Teste
Found 1 Numbers in Campaign
PHP Error[8]: Undefined variable: modelTrunks
    in file /var/www/html/mbilling/protected/commands/MassiveCallCommand.php at line 196
#0 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(67): MassiveCallCommand->run()
#1 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run()
#2 /var/www/html/mbilling/yii/framework/base/CApplication.php(169): CConsoleApplication->processRequest()
#3 /var/www/html/mbilling/cron.php(31): CConsoleApplication->run()
[root@srv-datatel-centos7 commands]# ^C
[root@srv-datatel-centos7 commands]#

**Comment by renatosabatini** [comment]
Achei o Erro:
![image](https://user-images.githubusercontent.com/68757900/88441597-ecab2500-cde7-11ea-8bb0-a9bfe55ee1a9.png)

A Linha estava assim:  foreach ($modelTrunks as $key => $trunk) {

**Comment by magnussolution** [comment]
atualize seu servidor por favor. Sempre antes de informar um BUG, garanta que você esta atualizado, executando o comando

`/var/www/html/mbilling/protected/commands/update.sh`

**Comment by magnussolution** [comment]
pode verificar que o ultimo código ja tem isso solucionado a semanas.

https://github.com/magnussolution/magnusbilling7/blob/source/protected/commands/MassiveCallCommand.php

**Comment by renatosabatini** [comment]
Atualizei e mudou o erro 

![image](https://user-images.githubusercontent.com/68757900/88467810-7a9f1280-ceb1-11ea-9828-61f82b18c99e.png)

Nesta linha:
![image](https://user-images.githubusercontent.com/68757900/88467824-94405a00-ceb1-11ea-82b0-12c960f39787.png)

**Comment by renatosabatini** [comment]
1 - As chamadas do torpedo de voz não aparecem nas chamadas simultâneas no dashboard.

2 - Nos relatório das ligações das campanhas aparecem o tronco em vez da conta.

![image](https://user-images.githubusercontent.com/68757900/88549645-f060c680-cff6-11ea-9653-53c97a8a18cf.png)
