### ISSUE TITLE
Após rodar o update.sh não carrega mais o portal 

### ISSUE THREAD

**Issue by renatosabatini** [magnussolution/magnusbilling#380]
Após atualizar o sistema fica apenas na tela de inicialização:

![image](https://user-images.githubusercontent.com/68757900/88722866-56844100-d0fe-11ea-872e-1f9e758e424f.png)

No brouser aparece os seguintes erros:

![image](https://user-images.githubusercontent.com/68757900/88722776-35235500-d0fe-11ea-9887-1fad066c390c.png)

**Comment by magnussolution** [comment]
atualize novamente, resolvemos o problema.

Obrigado por informar, principalmente por mandar ja log, assim facilita muito a solução
