### ISSUE TITLE
Conf files reload

### ISSUE THREAD

**Issue by ezhevak** [magnussolution/magnusbilling#385]
Tell me how new Asterisk configuration files are loaded.

For the Example, I have removed or added a new SIP. Is there a need to reload Asterisk configuration files?

**Comment by tcreek** [comment]
I do believe it is using Asterisk Realtime, so a reload is not needed, or it does the reload for you.

**Comment by magnussolution** [comment]
not use realtime, but is not necessary reload manually.

MagnusBilling write the asterisk files and reload the module
