### ISSUE TITLE
Let's Encrpt Issue

### ISSUE THREAD

**Issue by tcreek** [magnussolution/magnusbilling#386]
So Let's Encrypt requires one set up a virtual host on the server. 

I did set it up and pointed the virtual host to use /var/www/html since Magnus Billing is only being ran on the server.

After running through, certbot (cerbot --apache <host name>), and it completing, I looked and saw it did make changes to the virtual host configuration on port 80 redirect to port 443 for SSL.

Upon visiting the site via https, I see the web server is still using the default self-signed certificate.

I am not seeing anything in any of those videos on setup for SSL.

Maybe it's time the project put up a wiki, or other type of docs site to get more in depth on many areas?

Is there a resolution for using Let's Encrypt?

**Comment by yurikurka** [comment]
Review your virtual site in apache configuration, certbot works great for
me.

Em qua, 5 de ago de 2020 18:40, tcreek <notifications@github.com> escreveu:

**Comment by tcreek** [comment]
Review it for what? This is not my first time setting up virtual hosts & Let's encrypt together.

I type in the domain name, and it goes to the site as it should, just incorrect certificate.

Here is my virtual host configuration (sanitized of course)

```

<VirtualHost *:80>

    DocumentRoot "/var/www/html/"
    ServerName my.domain

RewriteEngine on
RewriteCond %{SERVER_NAME} =my.domain
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>

    DocumentRoot "/var/www/html/"
    ServerName my.domain

SSLCertificateFile /etc/letsencrypt/live/my.domain/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/my.domain/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/my.domain/chain.pem
</VirtualHost>
```

**Comment by tcreek** [comment]
You want to share what you did to get it functioning?
