### ISSUE TITLE
Change install script for alternative directory

### ISSUE THREAD

**Issue by tcreek** [magnussolution/magnusbilling#387]
For in the install script, it would be nice to see a couple of changes.

1) make the install directory a variable instead of hard coded.
2) From the variable, allow users to change from the default directory of ./mbilling during the run of the script

**Comment by voiptelecom** [comment]
If you check the code, everything is aiming to that folder, the controllers, the views, everything and is working just fine.

**Comment by tcreek** [comment]
I am not saying it is not working fine, I am just saying a chance to easily change that during the beginning of the run of the script would be nice.
