### ISSUE TITLE
Let's Encrypt SSL certificate not being used after installation

### ISSUE THREAD

**Issue by tcreek** [magnussolution/magnusbilling#388]
I have tried using certbot as the following:

certbot -d domain.name
certbot --apache -d domain,name

In both instances, the certificate is still not being used after installation, and changes made by certbot. Instead, Apache server is still using the self-signed certificate created with the installation of Apache.

Any ideas what is going on with this?

**Comment by tcreek** [comment]
I resolved the issue.

This project really needs wiki or docs site to cover issues like this.

The issue is CentOS 7 is putting in a default virtual host configuration inside /etc/httpd/conf.d/ssl.conf for port 443

Since the hostname of the machine, and virtual host are the same, it is causing a conflict. Even if you do not use the "--apache" configuration, certbot will instead put the configuration in /etc/httpd/conf.d/ssl.conf, while the default vhost still remains, and conflicts. 

Starting at line 56, everything needs to be removed from <VirtualHost _default_:443> to </VirtualHost>

**Comment by voiptelecom** [comment]
Hi, 

It is easy to operate with certbot, you only need to a line after the instalation to work with letsencrypt certficates

If Debian= apt-get install -y python-certbot-apache
If Centos = yum -y install certbot python2-certbot-apache mod_ssl

If Debian = You need to modify the 000-default.conf files on /etc/apache2/sites-available/
Example:

<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName example.com

        ServerAdmin admin@example.com
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost *:80>

Then run --> systemctl restart apache2 to refresh apache.
Then run --> letsencrypt --apache and follow the instructions.

If centos = you need to go to /etc/httpd/conf.d/ and create a virtualhost
Example: nano /etc/httpd/conf.d/mydomain.conf

Create your virtual host:

<VirtualHost *:80>
    ServerName www.example.com
    ServerAlias example.com
    DocumentRoot /var/www/html
    ErrorLog /var/www/html/error.log
    CustomLog /var/www/html/requests.log combined
</VirtualHost>

Then run --> systemctl restart httpd to refresh apache
Then run --> letsencrypt --apache 

Keep in  mind that before this procedure you must give permissions to letsencrypt authority to create challenges and give you the certificates.

After all that is complete, you Magnus Billing must have the secure lock on the navigation bar.

Hope this info helps.

**Comment by tcreek** [comment]
Thanks for taking the time to respond. However, I did all the above, and there was still a problem. As mentioned in my post, I showed the problem.

**Comment by boukar10** [comment]
Those steps make my life easy.
Thank you very much for charing
