### ISSUE TITLE
Problema em variavel no E-mail(Aviso de vencimento do plano"

### ISSUE THREAD

**Issue by renatosabatini** [magnussolution/magnusbilling#389]
Bom dia 

Esta variável não esta trazendo a quantidade de dias que falta para bloquear o plano:

![image](https://user-images.githubusercontent.com/68757900/89710191-18d1b480-d957-11ea-9fa6-1582fe628c43.png)

No e-mail recebido esta linha não vem com este campo alterado veja:

![image](https://user-images.githubusercontent.com/68757900/89710280-d78dd480-d957-11ea-984f-3e0eccb8b9f5.png)

**Comment by magnussolution** [comment]
ola, use a variable $days_to_pay$, estava errado colocado em português, mas ja foi alterado. Atualizar seu MagnusBilling
