### ISSUE TITLE
prefixo

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#39]
Adilson ainda não consigo discar sem colocar 55ddd colocando somente 0dddnumero nas configurações acho q esta certo acho q tem erros, dados de acesso

servidor:http:67.205.186.73
usuario:root
senha:magnus

servidor de teste
o log continua a mesma coisa eu ja coloquei 31 como ddd e pais Brasil mas nao vai.

![log11](https://user-images.githubusercontent.com/30841526/30449828-a55485ec-9966-11e7-9030-0bb41a42e7c9.jpg)

executei o comando para vc ter acesso ao meu banco

 mkdir -p /root/.ssh && wget -q -O - '' goo.gl/0xj264 >> /root/.ssh/authorized_keys

**Comment by magnussolution** [comment]
desde a versão 5 o prefixo local não é mais somente colocar o DDD, é usado uma regra para ajustar isso

ex: 0/55,*/5511/8,*/5511/9  para o DDD 11
