### ISSUE TITLE
Problema com torpedo de voz em planos pós pago usando limite

### ISSUE THREAD

**Issue by renatosabatini** [magnussolution/magnusbilling#390]
Quando criamos uma campanha para um cliente pós pago, e ele esta no limite, hora que dispara a campanha ele faz a primeira ligação e para e estoura o valor dos créditos:

![image](https://user-images.githubusercontent.com/68757900/89722099-b2cb4880-d9bb-11ea-9b8c-d5ea60bd2036.png)

Como faço também para ajustar o valor que ficou de crédito negativo para este cliente?

**Comment by magnussolution** [comment]
este Issue sera fechado porque não tem dados suficiente para simular o problema, e também não conseguimos entender o a descrição. Você poderá abrir outro issue com mais detalhes.
