### ISSUE TITLE
Decimal precision Doesn't Work for new Rates & DID

### ISSUE THREAD

**Issue by MShoaib67** [magnussolution/magnusbilling#397]
**Describe the bug**
Decimal precision is set in App Configuration But Not Showing up in Rates nor in DID menu. 

**To Reproduce**
1. Go to 'Settings -> Configuration'
2. Click on 'Decimal precision -> Change it to 0000'

**Expected behavior**
Tariff & DID Decimal precision should have changed but it still shows 000 Decimal precision while adding up new Tariff / DID

**Comment by magnussolution** [comment]
Hi, refresh, F5, after you change the decimal precision

**Comment by MShoaib67** [comment]
Hi, it doesn't work. Please find the attached file file as Screenshot & Decimal precision setting / Rates / DID section where the Decimal is 000 but not 0000.





![Decimal Precision](https://user-images.githubusercontent.com/10461055/90307815-661fca00-def3-11ea-94ef-5dfaa8b725b2.JPG)
![DID](https://user-images.githubusercontent.com/10461055/90307816-6750f700-def3-11ea-80fb-17f7e7495254.JPG)
![Rates](https://user-images.githubusercontent.com/10461055/90307817-68822400-def3-11ea-91ed-9ea54c98c917.JPG)
