### ISSUE TITLE
Importando Numeros para Agenda

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#4]
Foi testado importar numeros para a agenda, o mesmo nao funcionou.

Em teste de importação de numeros nao esta funcionado.
Apenas fica processando.

Estou usando no teste http://sip.hilario.net.br/mbilling/
usuario: root
senha: magnus

Acesso cedido por membr do grupo magnus no Whatsapp
Não tenho como verificar se houve problema na instalação

**Comment by magnussolution** [comment]
verifique se vc tem permissão de adicionar e editar números no grupo que vc esteja logado.

e também precisa colocar na 1º coluna os nomes das colunas

exemplo

numero,nome
555555555434343,magnus

**Comment by betaniojr** [comment]
1 - A nova dinâmica de registro do tronco usando a string de registro só é atualizada manualmente, logo, ontem eu precisei mudar a senha para tentar conectar um tronco. Mudei a senha na parte superior e não atentei para a string, que não muda, exceto quando feito manualmente. Ela também impede (logicamente) que eu selecione a opção de registrar tronco sem senha.
2 - Não logrei êxito em registrar um tronco no MBilling 6. Quando fiz por IP e usuário a informação até chegou no outro servidor, mas após poucos segundos, ele aparece como não registrado, o que me impediu de receber chamadas de números DID, por exemplo.
