### ISSUE TITLE
Painel Revendedor

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#40]
Após instalar o MB hoje dia 14/09/2017 as 21:58 pelo script

cd /usr/src/
yum -y install wget
wget https://raw.githubusercontent.com/magnussolution/magnusbilling6/master/script/install.sh
chmod +x install.sh
./install.sh

verifiquei que se vc logar com login de revendedor a conta do mesmo esta aparecendo no painel dele como cliente dele mesmo e se ele deletar esta conta sem querer a revenda dele é apagada.

**Comment by magnussolution** [comment]
Alterei para mostrar mas não deixar editar nem deletar.
