### ISSUE TITLE
 Decimal precision setting / Rates / DID section where the Decimal is 000 but not 0000.

### ISSUE THREAD

**Issue by MShoaib67** [magnussolution/magnusbilling#400]
Hi, it doesn't work. Please find the attached file file as Screenshot & Decimal precision setting / Rates / DID section where the Decimal is 000 but not 0000.

![Decimal Precision](https://user-images.githubusercontent.com/10461055/90307815-661fca00-def3-11ea-94ef-5dfaa8b725b2.JPG)
![DID](https://user-images.githubusercontent.com/10461055/90307816-6750f700-def3-11ea-80fb-17f7e7495254.JPG)
![Rates](https://user-images.githubusercontent.com/10461055/90307817-68822400-def3-11ea-91ed-9ea54c98c917.JPG)

_Originally posted by @notyourthing in https://github.com/magnussolution/magnusbilling7/issues/397#issuecomment-674362702_

**Comment by magnussolution** [comment]
fixed, please update your server
