### ISSUE TITLE
Pool of A numbers (CallerID)

### ISSUE THREAD

**Issue by ezhevak** [magnussolution/magnusbilling#402]
Is it possible to use the pool of A numbers (CallerID) for calls in magnusbilling7?

**Comment by magnussolution** [comment]
https://github.com/magnussolution/magnusbilling7/blob/source/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ezhevak** [comment]
This is not a bug.
This is the question of functionality exists in Magnus Billing 7.
Is it possible to use the pool of A numbers (CallerID) for calls in magnusbilling7?

**Comment by magnussolution** [comment]
this place is to report issue. To make question you can use the Telegram group https://t.me/joinchat/NXwoZRPGpG6rPqp3yssLzQ
