### ISSUE TITLE
Bitcoin payment time?

### ISSUE THREAD

**Issue by ezhevak** [magnussolution/magnusbilling#403]
Tell me how you can change the bitcoin payment receipt time from 30 minutes to 2-3 hours?

**Comment by ezhevak** [comment]
Can i use Bitcoin Refill username (BTC address) not from Poloniex with Client Id and Client Secret from Poloniex?

**Comment by magnussolution** [comment]
https://github.com/magnussolution/magnusbilling7/blob/source/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ezhevak** [comment]
This is not a bug.
This is a question about how to change the waiting time for payment in the system?

**Comment by magnussolution** [comment]
https://t.me/joinchat/NXwoZRPGpG6rPqp3yssLzQ
