### ISSUE TITLE
Not shown Trunk Name in trunk group select

### ISSUE THREAD

**Issue by ezhevak** [magnussolution/magnusbilling#404]
**Describe the bug**
Not shown Trunk Name in trunk group select

**To Reproduce**
Go to **Routes->Trunks** and Create new trunk name **TestTrunk** then go to **Routes->TrunkGroup** and create New TrunkGroup name **TestTrunkGroup** and try to select **TestTrunk**

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [MBilling Version 7.3.8]

**Comment by magnussolution** [comment]
if you open the menu Trunk Groups, after open the menu trunk and add a new trunk, you will need clone the menu Trunk Groups and open again to load the new trunk.
