### ISSUE TITLE
balance at the beginning and at the end of the day

### ISSUE THREAD

**Issue by ezhevak** [magnussolution/magnusbilling#405]
**Reports -> Summary Day User **
It would be great to see the balance at the beginning and at the end of the day in the report **Reports -> Summary Day User **

**Comment by magnussolution** [comment]
https://github.com/magnussolution/magnusbilling7/blob/source/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by ezhevak** [comment]
it's not a bag. 
This is not a bug.
This is a suggestion to improve MagnusBilling 7

**Comment by magnussolution** [comment]
i not understand, please to be more descriptive

**Comment by MShoaib67** [comment]
@magnussolution  He is Suggesting that a 2 columns are added in Summary Day User in which Magnus can show

Day start Balance - Day end Balance. e.g

Start Balance - 10.30 (System gets the Balance that was at 00:00:00  / End Balance - 9.30 System get this at 23:59:59

**Comment by ezhevak** [comment]
Yes, absolutely right!
