### ISSUE TITLE
AGI 1 - International Prefixs

### ISSUE THREAD

**Issue by voiptelecom** [magnussolution/magnusbilling#406]
Hello, I found this problem

![Captura de Pantalla 2020-08-18 a la(s) 15 49 06](https://user-images.githubusercontent.com/62485767/90554872-dedd8b00-e16c-11ea-9a61-5034b3c2de77.png)

It takes the 00, 09, 011

But the + is not working.

Thanks.

**Comment by magnussolution** [comment]
Magnusbilling not allow use +. 

But if you need remove + you can edit the context billing and remove the + on the context

**Comment by voiptelecom** [comment]
> Magnusbilling not allow use +.
> 
> But if you need remove + you can edit the context billing and remove the + on the context

Really? 

You need to improve your UX experience, check on google and find that every cellphone in the world use +xxxxxx because the whatsapp, so, when a normal person connects to the magnus billing and can not dial with the +, everything is going to hell, so, it is not like an making boo boo problem of this,  --> https://en.wikipedia.org/wiki/List_of_international_call_prefixes

UX is all in this business, and you are very rude with the users, you should change that a believe me, you will get more support in your project.

Thanks anyway

**Comment by dimtelecom** [comment]
I think @magnussolution meant that you can remove the "+" in context. Like
exten => _+X.,1,Goto(${EXTEN:1},1)
exten => _X.,1,NoOp(Billing Start)

**Comment by voiptelecom** [comment]
> I think @magnussolution meant that you can remove the "+" in context. Like
> exten => _+X.,1,Goto(${EXTEN:1},1)
> exten => _X.,1,NoOp(Billing Start)

Hello @dimtelecom thank you so much for the answer, this is how i fix the problem, In the context billing i just add the first line you send me an this is how it look's like:

exten => _[*0-9].,1,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php")
exten => _+X.,1,Goto(${EXTEN:1},1) --> **Just_ add this one and that's it**
  same => n,Hangup()
exten => h,1,hangup()

Once again, thank you so much.
