### ISSUE TITLE
Importacao de tarifas revenda

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#41]
Ao tentar importar um tarifa nova logado no painel com LOGIN DE REVENDEDOR o sistema nao importa tarifas para planos criados no painel. Se tentar importar logado como Root importa mas não aparece as tarifas no painel do REVENDEDOR.

**Comment by magnussolution** [comment]
acabei de testar importar uma tabela simples assim

55,brasil,0.2
5511,brasil SP,0.15

como AGENTE, importou perfeitamente.
