### ISSUE TITLE
Erro no Menu Principal Hardware

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#413]
Erro na estatistica de uso atual de CPU, ele fixa em um valor e se mantem no mesmo por muito tempo, não demonstrado a real utilização da CPU.

![erro-CPU](https://user-images.githubusercontent.com/28572532/90948381-61d43f00-e414-11ea-8165-b04689333678.jpg)

**Comment by magnussolution** [comment]
deve estar solucionado na ultima versão
