### ISSUE TITLE
Não é possível alterar o idioma da interface WEB outra vez

### ISSUE THREAD

**Issue by GabrielBragaGit** [magnussolution/magnusbilling#415]
Eu utilizava a interface web do MAGNUS BILLING em português, troquei o idioma para inglês e depois de um tempo tentei trocar para o português novamente, porém tudo continua em inglês, ja limpei cache do navegador, ja instalei navegador novo e acessei a pagina porém continua em inglês, tentei também alterar para italiano, russo e espanhol mas não sai do inglês.

Versão 7.4.4, ja dei o comando de update e continua o mesmo problema.

**Comment by magnussolution** [comment]
desculpe pelo erro. Patrão.

Por favor atualize
