### ISSUE TITLE
Campo "Habilitar Gravação" não aparece. 

### ISSUE THREAD

**Issue by renatosabatini** [magnussolution/magnusbilling#423]
Campo Habilitar Gravação não esta aparecendo.

![image](https://user-images.githubusercontent.com/68757900/91852487-4c8eba00-ec37-11ea-9019-5e1444e31e80.png)

Magnus esta atualizado

![image](https://user-images.githubusercontent.com/68757900/91852534-5dd7c680-ec37-11ea-86f7-e8ce136b3e2b.png)

**Comment by magnussolution** [comment]
chamadas sainte a opção esta na conta voip.

chamadas entrantes, esta no próprio DID.
