### ISSUE TITLE
Carrier stats report

### ISSUE THREAD

**Issue by uzair329** [magnussolution/magnusbilling#425]
Team 

We are unable to find the solution of carrier performance as when it gives 480 or 503 in both cases your structure write busy and give the audio of number is busy which is very frustrating at some times for clients when they dial same number from other vendors they got proper response of 503 or 480. And at the same time we are unable to find the exact Busy and congestion from your status of failed calls . So instead of this i found a solution to verify carrier issues.

Solution :

I make a dialplan of asterisk  in which after call's hangup i check Execif hangup cause is equals to 34 or 38 than punch the date time , Caller Id , Destination Number and Trunk in file . But this is not perfect way . Perfect way is this should be punch in Database of magnus billing . And we can see this in reports . You can punch hangup cause as well with dial status so we can filter hangup causes of trunks which is easy from asterisk . Asterisk give each call hangup cause. But remove this number is busy on congestion please 

To resolve my carrier issues i have to download the file than filter out each and every sheet on daily basis which is long work if its on GUI i dont need to winscp my sever and download the file on notepad

**Comment by magnussolution** [comment]
go to plan menu, and disable the option play audio.

**Comment by uzair329** [comment]
But what about reporting?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
