### ISSUE TITLE
Opción buscar en cuentas voip no funciona

### ISSUE THREAD

**Issue by andrese582** [magnussolution/magnusbilling#426]
Al dar clic o enter sobre la opción buscar en el submenu "**Cuentas Voip**" no se hace la búsqueda
![bug001](https://user-images.githubusercontent.com/69047775/92049232-71765080-ed4f-11ea-9c9a-c43f7b354970.png)

 - OS: 

**Smartphone

**Comment by magnussolution** [comment]
update your MagnusBilling, clear the cache, and try again.

Filter per SIP user.
