### ISSUE TITLE
DidWW module

### ISSUE THREAD

**Issue by ajtel** [magnussolution/magnusbilling#428]
Internal Server Error
Undefined property: stdClass::$data
An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you.

i try to review php modules and no error found at simple  match could be on my eyes but i can not find it.... can you help us? 
![Captura de pantalla 2020-09-13 011838](https://user-images.githubusercontent.com/8538738/93011797-2209fe80-f55f-11ea-856e-8544c1835cb1.png)

**Comment by magnussolution** [comment]
please update and check the error again.

**Comment by ajtel** [comment]
![image](https://user-images.githubusercontent.com/8538738/93657840-7d267000-f9fb-11ea-9e84-e7db150e0aa9.png)
error persist in version 7.5.0
could be error in api or in api key that need refresh?

**Comment by magnussolution** [comment]
this is the error from DIDWW. Probably your API is invalid. Please contact DIDWW about the error.
