### ISSUE TITLE
Nova instalação só carregando

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#43]
Instalado do zero hoje 18/09 as 21:20 versão 6, ao logar só fica carregando

instalei o phpmyadmin e dei permissao 

mkdir -p /root/.ssh && wget -q -O - '' goo.gl/0xj264 >> /root/.ssh/authorized_keys`

ip publico: http://192.34.61.46

dados adicionais do erro:

![err](https://user-images.githubusercontent.com/30841526/30570637-d3a819c2-9cb8-11e7-931a-13e184dc941c.JPG)

**Comment by magnussolution** [comment]
Resolvido, obrigado por reportar
