### ISSUE TITLE
Nao salva tronco

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#44]
Acabei de atualizar, foi corrigido problema de ficar só carregando pagina mas não está salvando o tronco.

(index):131 [Deprecation] Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
checkForAppCacheUpdate @ (index):131
checkAllUpdates @ (index):131
onAllAssetsReady @ (index):130
notify @ (index):108
processLoadedEntries @ (index):108
notifyRequests @ (index):116
(anonymous) @ (index):114
d.isIE10m.c.onload @ (index):112
app.js?_dc=20170807175216:29 637
app.js?_dc=20170807175216:1 POST http://192.34.61.46/mbilling/index.php/trunk/save?_dc=1505825748188 500 (Internal Server Error)

**Comment by magnussolution** [comment]
seu magnusbilling nao esta corretamente instalado e atualizado. Teste
