### ISSUE TITLE
Nao importa tarifa revenda

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#45]
Ainda não está importando tarifas na versao 6.0.4.

*Você cria um usuário agente, loga com este usuário, vai em TARIFAS/TARIFAS não aparece nada, ai quando você vai em TARIFAS/PLANOS e manda criar um plano qualquer e depois volta em TARIFAS/TARIFAS, aparece a tarifa que vc acabou de criar só que com o valores do revendedor e se você mandar criar outro plano ele vai só duplicando o nome do primeiro plano que você criou e nunca aparece os outros planos criados.

**Comment by magnussolution** [comment]
acabei de testar novamente. Esta exatamente como na versão 5.
