### ISSUE TITLE
Separar os intervalos da URA também nos dias da semana (segunda, terça, quarta, quinta e sexta).

### ISSUE THREAD

**Issue by GabrielBragaGit** [magnussolution/magnusbilling#451]
Seria interessante se os intervalos da URA também pudessem configurar individualmente os dias da semana de (segunda, terça, quarta, quinta e sexta). Hoje somente é possível aplicar um filtro igual para os dias de segunda a sexta.

**Comment by magnussolution** [comment]
não temos planos para fazer esta alteração.
