### ISSUE TITLE
calling card issue

### ISSUE THREAD

**Issue by llamabara** [magnussolution/magnusbilling#46]
i've configured a number did to use with destination calling card and it not go on. so i try to use destination call sip and call for PSTN. It works well.

i include the logs.

-- <SIP/DIDWW-0000006f>AGI Script /var/www/html/mbilling/agi.php completed, returning 4
  == Spawn extension (billing, 522225551723, 1) exited non-zero on 'SIP/DIDWW-0000006f'
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
centos-2gb-sfo2-01*CLI> core set verbose 0
Console verbose was 10 and is now OFF.
centos-2gb-sfo2-01*CLI> core set verbose 10
Console verbose was OFF and is now 10.
  
  == Using SIP RTP CoS mark 5
    -- Executing [522225551723@billing:1] AGI("SIP/DIDWW-00000071", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
 "/var/www/html/mbilling/agi.php": Is a DID call
 "/var/www/html/mbilling/agi.php": Array
 "/var/www/html/mbilling/agi.php": (
 "/var/www/html/mbilling/agi.php":     [id] => 5
 "/var/www/html/mbilling/agi.php":     [id_user] => 5
 "/var/www/html/mbilling/agi.php":     [id_ivr] => 0
 "/var/www/html/mbilling/agi.php":     [id_sip] => 0
 "/var/www/html/mbilling/agi.php":     [id_queue] => 0
 "/var/www/html/mbilling/agi.php":     [id_did] => 2
 "/var/www/html/mbilling/agi.php":     [destination] => 5219661085790
 "/var/www/html/mbilling/agi.php":     [priority] => 1
 "/var/www/html/mbilling/agi.php":     [creationdate] => 2017-09-17 22:04:02
 "/var/www/html/mbilling/agi.php":     [activated] => 1
 "/var/www/html/mbilling/agi.php":     [secondusedreal] => 226
 "/var/www/html/mbilling/agi.php":     [voip_call] => 0
 "/var/www/html/mbilling/agi.php": )
 "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": encontrou a expression1 no callerid529661042486
       > "/var/www/html/mbilling/agi.php":  answeredtime =  sell_price = 0 connection_sell = 0.00000
       > "/var/www/html/mbilling/agi.php": DID 522225551723
 "/var/www/html/mbilling/agi.php": try blocked
       > "/var/www/html/mbilling/agi.php": voip_call 0
       > "/var/www/html/mbilling/agi.php": Mode = did
       > "/var/www/html/mbilling/agi.php": DID CALL - CallerID=529661042486 -> DID=522225551723
       > "/var/www/html/mbilling/agi.php": Array
       > "/var/www/html/mbilling/agi.php": (
       > "/var/www/html/mbilling/agi.php":     [id] => 5
       > "/var/www/html/mbilling/agi.php":     [id_user] => 5
       > "/var/www/html/mbilling/agi.php":     [id_ivr] => 0
       > "/var/www/html/mbilling/agi.php":     [id_sip] => 0
       > "/var/www/html/mbilling/agi.php":     [id_queue] => 0
       > "/var/www/html/mbilling/agi.php":     [id_did] => 2
       > "/var/www/html/mbilling/agi.php":     [destination] => 5219661085790
       > "/var/www/html/mbilling/agi.php":     [priority] => 1
       > "/var/www/html/mbilling/agi.php":     [creationdate] => 2017-09-17 22:04:02
       > "/var/www/html/mbilling/agi.php":     [activated] => 1
       > "/var/www/html/mbilling/agi.php":     [secondusedreal] => 226
       > "/var/www/html/mbilling/agi.php":     [voip_call] => 0
       > "/var/www/html/mbilling/agi.php": )
       > "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": [Magnus] DID call friend: FOLLOWME=1 (username:FARMEDECO
       > "/var/www/html/mbilling/agi.php":                     | destination type:0| id_plan:1)
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:FARMEDECO
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 5219661085790
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 5219661085790
       > "/var/www/html/mbilling/agi.php": Phone After translation: 5219661085790
       > "/var/www/html/mbilling/agi.php": USERNAME=FARMEDECO DESTINATION=5219661085790 PLAN=1 CREDIT=99.7628
       > "/var/www/html/mbilling/agi.php": NUMBER TRUNK FOUND1
       > "/var/www/html/mbilling/agi.php": NUMBER TARIFF FOUND -> 1
       > "/var/www/html/mbilling/agi.php": TIMEOUT->95012 : minutes=1583 - seconds=32
    -- AGI Script Executing Application: (DIAL) Options: (sip/silver/5219661085790,60,L(3600000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 3600000 ms (3600.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    = 
       > warning_sound  = timeleft
       > end_sound      = 
  == Using SIP RTP CoS mark 5
    -- Called sip/silver/5219661085790
    -- SIP/silver-00000072 is ringing
    -- SIP/silver-00000072 is making progress passing it to SIP/DIDWW-00000071
       > 0x7f0918008570 -- Probation passed - setting RTP source address to 208.78.160.115:13538
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
 "/var/www/html/mbilling/agi.php": answeredtime =
       > "/var/www/html/mbilling/agi.php": Hangup Call 5219661085790 Username FARMEDECO
    -- <SIP/DIDWW-00000071>AGI Script /var/www/html/mbilling/agi.php completed, returning 4
  == Spawn extension (billing, 522225551723, 1) exited non-zero on 'SIP/DIDWW-00000071'
  == Using SIP RTP CoS mark 5
    -- Executing [522225551723@billing:1] AGI("SIP/DIDWW-00000073", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
 "/var/www/html/mbilling/agi.php": Is a DID call
 "/var/www/html/mbilling/agi.php": Array
 "/var/www/html/mbilling/agi.php": (
 "/var/www/html/mbilling/agi.php":     [id] => 5
 "/var/www/html/mbilling/agi.php":     [id_user] => 5
 "/var/www/html/mbilling/agi.php":     [id_ivr] => 0
 "/var/www/html/mbilling/agi.php":     [id_sip] => 0
 "/var/www/html/mbilling/agi.php":     [id_queue] => 0
 "/var/www/html/mbilling/agi.php":     [id_did] => 2
 "/var/www/html/mbilling/agi.php":     [destination] => 5219661085790
 "/var/www/html/mbilling/agi.php":     [priority] => 1
 "/var/www/html/mbilling/agi.php":     [creationdate] => 2017-09-17 22:04:02
 "/var/www/html/mbilling/agi.php":     [activated] => 1
 "/var/www/html/mbilling/agi.php":     [secondusedreal] => 226
 "/var/www/html/mbilling/agi.php":     [voip_call] => 3
 "/var/www/html/mbilling/agi.php": )
 "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": encontrou a expression1 no callerid529661042486
       > "/var/www/html/mbilling/agi.php":  answeredtime =  sell_price = 0 connection_sell = 0.00000
       > "/var/www/html/mbilling/agi.php": DID 522225551723
 "/var/www/html/mbilling/agi.php": try blocked
       > "/var/www/html/mbilling/agi.php": voip_call 3
       > 0x7f0914016f20 -- Probation passed - setting RTP source address to 46.19.209.79:35070
    -- <SIP/DIDWW-00000073>AGI Script /var/www/html/mbilling/agi.php completed, returning 0
    -- Auto fallthrough, channel 'SIP/DIDWW-00000073' status is 'UNKNOWN'

centos-2gb-sfo2-01*CLI> core set verbose 0
Console verbose was 10 and is now OFF.
centos-2gb-sfo2-01*CLI> 

IMAGE TO DID.
![destination-did](https://user-images.githubusercontent.com/32110802/30659320-0c083888-9e03-11e7-9da8-9e58b81962dc.jpeg)

**Comment by magnussolution** [comment]
Issue ya solucionada, actualize el sistema y pruebe

saludos

**Comment by llamabara** [comment]
i actuallized the mbilling with netx lines:

as mbilling 5 i try update, and the server show me this message: You alread have MagnusBilling installed!!!!

Execute this command to update your MagnusBilling
/var/www/html/mbilling/protected/commands/update.sh

so i executed this command to update. and after it, i rebooted my server and try make a call to use calling card service, and the calls not go through the calling card service, only i get hang up.

**Comment by magnussolution** [comment]
try again
/var/www/html/mbilling/protected/commands/update.sh

we send a new commit to fix this issue

**Comment by llamabara** [comment]
the issue still be present.

this is update mbilling
![update-mbilling](https://user-images.githubusercontent.com/32110802/30677300-96d2120c-9e50-11e7-8675-457c5ce373b6.jpeg)

this is a log from asterisk 14

[log-callingcard.txt](https://github.com/magnussolution/magnusbilling6/files/1319871/log-callingcard.txt)

**Comment by magnussolution** [comment]
update again, and try again. We found new code issue and fix that.
Thanks your reporter

**Comment by llamabara** [comment]
the problem was resolved. Thank you team Magnusbilling
