### ISSUE TITLE
Problemas no menu Chamadas Online.

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#465]
Mesmo em ligação o Menu chamadas online não demonstra nada.
Repare que coloquei o em vermelho o menu de atualização que nem está aparecendo bem...
Coloquei em vermelho os problemas.

![image](https://user-images.githubusercontent.com/28572532/96216176-0a56d900-0f56-11eb-82e5-80842a64868e.png)

**Comment by yurikurka** [comment]
Constatei que esse problema ocorre durante update, fiz uma instalação nova e o mesmo problema não ocorre.

**Comment by magnussolution** [comment]
apos update, execute o comando

`pkill -f callchart`
