### ISSUE TITLE
Problema no sistema de pagamento GerenciaNet

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#468]
Após o cliente fazer a compra de crédito para recarga o sistema gerencianet gera o boleto mas não aparece a informação no Magnus Menu Financeiro Recarga como o exemplo abaixo : 

![image](https://user-images.githubusercontent.com/50499925/96768728-8e74ea80-13b4-11eb-9857-8a1f8150b9cb.png)

Versão 7.5.4 atualizada dia 19-10-2020

**Comment by yurikurka** [comment]
Você tem https com certificado válido nesse teste?

Em qua, 21 de out de 2020 15:48, sipserver <notifications@github.com>
escreveu:

**Comment by magnussolution** [comment]
verifique no log protected/runtime/application.log para ver se teve retorno do pagamento vindo do gerencianet

**Comment by sipserver** [comment]
Segue os dados dentro do arquivo de log referente a ultima compra que não está registrando dentro de recarga mas somente amanha vou saber se vai entrar o pagamento pois o cliente pagou hj o boleto.

![image](https://user-images.githubusercontent.com/50499925/96919433-2096f480-1482-11eb-88d6-4125267f0c9e.png)

**Comment by sipserver** [comment]
Agora fiz a consulta na recarga e apareceu a compra do cliente , antes era em tempo real houve alguma mudança onde roda alguma rotina que aparece só depois ?

![image](https://user-images.githubusercontent.com/50499925/96942376-5b615280-14ab-11eb-91d6-e6e6722594a5.png)
