### ISSUE TITLE
Importação DIDs

### ISSUE THREAD

**Issue by jefl2006** [magnussolution/magnusbilling#469]
Importação de DIDs não funciona. Da o erro conforme print abaixo
Menu -> DIDs -> DIDs = Importar CSV.
O .csv criado tentei numero somente, tentei numero, 0.0000, 0 e deu o mesmo erro.
![Importacao-DIDs](https://user-images.githubusercontent.com/52493678/96911935-f04a5880-1477-11eb-969f-268916208aa5.jpg)

**Comment by magnussolution** [comment]
vc deve colocar na primeira coluna do CSV o nome da coluna que estas tentando importar. As colunas são listada no próprio erro que da.
