### ISSUE TITLE
Tabela de Prefixos

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#47]
Foi observado que ao carregar  a tabela de venda/custo! Se nao for adicionado o 55 antes do 55.

Exemplo:

5531
para funcionar terá de colocar 555531

Testado na versao 6.0.4

**Comment by magnussolution** [comment]
ola, por favor ser claro quando for reportar um BUG.

LER https://www.magnusbilling.com/br/forum/mbilling/portugues/como-reportar-um-bug-2272.html
