### ISSUE TITLE
Número restrito para vários usuários ao mesmo tempo

### ISSUE THREAD

**Issue by marcost15** [magnussolution/magnusbilling#470]
Seria bom se o magnus pudesse adicionar números restritos a todos os usuários de uma vez, já que atualmente cada número deve ser inserido repetidamente de acordo com o número de usuários que cada um possui.

![magnus restrincion](https://user-images.githubusercontent.com/7028402/97218850-9ca17d00-179f-11eb-85a6-749d0433d754.jpg)

**Comment by magnussolution** [comment]
não tem esta opção
