### ISSUE TITLE
Erro ao espiar chamada

### ISSUE THREAD

**Issue by viniciusbarretobr** [magnussolution/magnusbilling#474]
Após selecionar a chamada desejada, selecionar a conta SIP e clicar em enviar, nada acontece. Ao voltar para a página principal "espiar chamada, a página fica apenas carregando em "looping".

**Obs:** A chamada está sendo feita entre dois ramais (de ramal para ramal)

Abaixo a tela do Loading e a após o erro que aparece no console:

![image](https://user-images.githubusercontent.com/15203803/97592224-2db26700-19df-11eb-84c4-51a6f9e8a045.png)

**Console:**
![image](https://user-images.githubusercontent.com/15203803/97592309-43279100-19df-11eb-8583-7b38fa3539b3.png)

**Comment by viniciusbarretobr** [comment]
A chamada está sendo feita entre dois ramais (de ramal para ramal)

**Comment by magnussolution** [comment]
chown -R asterisk:asterisk /var/www/html/mbilling/tmp
