### ISSUE TITLE
Call limit on Account Level not used

### ISSUE THREAD

**Issue by IPcomms2020** [magnussolution/magnusbilling#475]
**Describe the bug**
When testing inbound Calls to an account with call limit set to 2.   It does not limit the amount of calls for the account. 
If I change the SIP user setting Call-limit   to 2 for example it will limit the calls for the sip user.  However the error code back is a busy.  Would be nice to have this working on the account level so the user can have multiple sip users, but the call capacity is controlled at the account level.

Donald 
IPComms

**Comment by magnussolution** [comment]
the account level limit is only to outbound call.
