### ISSUE TITLE
callshop issue

### ISSUE THREAD

**Issue by llamabara** [magnussolution/magnusbilling#48]
i configured an account for callshop, the calls is go on through callshop. But in time the calls is finished and click on in use, any details is showed in the screen.

In this image you can see the issue: 
![callshop-details-calls](https://user-images.githubusercontent.com/32110802/30708342-20d0c642-9ec4-11e7-90f9-18e1a5f5cb4a.jpeg)

And then, when i try to change the selling rate in callshop tariff, the change not works. In the next image you can see the issue. 
![callshop-issue-tariff](https://user-images.githubusercontent.com/32110802/30708385-5add2ce0-9ec4-11e7-90aa-7098df37c1ba.jpeg)

I hope that you can help to resolve this issue.

Thank you team Magnusbilling

**Comment by magnussolution** [comment]
call shop issues fixes. Remember, the call shop menu only work correctly in client panel. Not have admin functions.

**Comment by llamabara** [comment]
Ok, it's right that, only in client panel works fine.

Thank you
