### ISSUE TITLE
PAGINA WEB DEMORANDO A CARREGAR

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#49]
Boa noite! Segue um video para melhor entendimento! no erro de carregamento!

[VID-20170921-WA0132.mp4.gz](https://github.com/magnussolution/magnusbilling6/files/1323184/VID-20170921-WA0132.mp4.gz)

**Comment by magnussolution** [comment]
sabra o developerTools ou Firebug e veja o erro que da.

**Comment by RodrigoRDC17** [comment]
<!DOCTYPE html>
<html id="ext-element-4" class="x-viewport" manifest="cache.appcache">
<head>
<body id="ext-element-1" class="x-body x-gecko x-desktop x-scroller x-border-layout-ct x-border-box x-container x-container-default" style="overflow: hidden;" data-componentid="main-1009" role="application">
<div id="panel-1010" class="x-panel x-border-item x-box-item x-panel-default" role="region" aria-hidden="false" aria-disabled="false" style="margin: 0px; width: 1920px; right: auto; left: 0px; top: 0px; height: 57px;">
<div id="panel-1030" class="x-panel x-border-item x-box-item x-panel-default" style="width: 200px; margin: 0px; right: auto; left: 0px; top: 57px; height: 639px;" role="region" aria-hidden="false" aria-disabled="false" aria-expanded="true" aria-labelledby="panel-1030-headingEl">
<div id="panel-1030-splitter" class="x-splitter x-border-item x-box-item x-splitter-default x-splitter-vertical x-unselectable" style="width: 8px; height: 639px; margin: 0px; right: auto; left: 200px; top: 57px;" role="separator" aria-hidden="false" aria-disabled="false" aria-orientation="vertical" data-exttouchaction="14" tabindex="0" data-componentid="panel-1030-splitter">
<div id="tabpanel-1031" class="x-panel x-border-item x-box-item x-panel-default" role="region" aria-hidden="false" aria-disabled="false" style="margin: 0px; width: 1712px; right: auto; left: 208px; top: 57px; height: 639px;">
<div id="tabpanel-1031-bodyWrap" class="x-panel-bodyWrap" data-ref="bodyWrap" role="presentation">
<div id="tabbar-1032" class="x-tab-bar x-docked x-tab-bar-default x-horizontal x-tab-bar-horizontal x-tab-bar-default-horizontal x-top x-tab-bar-top x-tab-bar-default-top x-docked-top x-tab-bar-docked-top x-tab-bar-default-docked-top x-noborder-trl" role="tablist" aria-hidden="false" aria-disabled="false" style="width: 1712px; right: auto; left: 0px; top: 0px;">
<div id="tabpanel-1031-body" class="x-panel-body x-panel-body-default x-panel-body-default x-noborder-trbl" data-ref="body" role="presentation" style="width: 1712px; left: 0px; top: 36px; height: 603px;">
<div id="dashboardmodule-1033" class="x-panel x-tabpanel-child x-panel-default x-hidden-offsets" role="tabpanel" aria-hidden="true" aria-disabled="false" aria-labelledby="tab-1149" aria-expanded="false" style="margin: 0px; width: 1712px; height: 878px;">
<div id="campaignmodule-1393" class="x-container x-tabpanel-child x-container-default x-border-layout-ct" style="border-width: 1px; margin: 0px; width: 1712px; height: 603px;" role="tabpanel" aria-hidden="false" aria-disabled="false" aria-labelledby="tab-1512" aria-expanded="true">
<div id="campaignlist-1394" class="x-panel x-border-item x-box-item x-panel-default x-grid" role="grid" aria-hidden="false" aria-disabled="false" aria-readonly="true" aria-multiselectable="true" aria-labelledby="campaignlist-1394_header-title-textEl" style="margin: 0px; height: 603px; right: auto; left: 0px; top: 0px; width: 1136px;">
<div id="campaignform-1440-splitter" class="x-splitter x-border-item x-box-item x-splitter-default x-splitter-vertical x-unselectable" style="border-width: 0px; width: 8px; height: 603px; margin: 0px; right: auto; left: 1136px; top: 0px;" role="separator" aria-hidden="false" aria-disabled="false" aria-orientation="vertical" data-exttouchaction="14" tabindex="0" data-componentid="campaignform-1440-splitter">
<div id="campaignform-1440-placeholder" class="x-panel-header x-header x-region-collapsed-placeholder x-region-collapsed-right-placeholder collapsed x-border-item x-box-item x-unselectable x-panel-header-default x-collapsed x-panel-header-collapsed x-panel-header-default-collapsed x-collapsed-left x-panel-header-collapsed-left x-panel-header-default-collapsed-left x-vertical x-panel-header-vertical x-panel-header-default-vertical x-left x-panel-header-left x-panel-header-default-left x-box-layout-ct x-hidden-offsets" role="toolbar" aria-hidden="true" aria-disabled="false" style="margin: 0px; height: 878px; right: auto; left: 1675px; top: 0px;" aria-expanded="true">
<div id="campaignform-1440" class="x-panel x-border-item x-box-item x-panel-default" style="width: 568px; right: auto; left: 1144px; top: 0px; margin: 0px; height: 603px;" role="presentation" aria-expanded="true" aria-busy="true" aria-describedby="loadmask-1591">
<div id="campaignform-1440_header" class="x-panel-header x-header x-header-noborder x-docked x-unselectable x-panel-header-default x-horizontal x-panel-header-horizontal x-panel-header-default-horizontal x-top x-panel-header-top x-panel-header-default-top x-docked-top x-panel-header-docked-top x-panel-header-default-docked-top x-box-layout-ct x-noborder-trl" role="toolbar" aria-hidden="false" aria-disabled="false" style="right: auto; left: 0px; top: 0px; width: 568px;">
<div id="campaignform-1440-bodyWrap" class="x-panel-bodyWrap" data-ref="bodyWrap" role="presentation">
<div id="loadmask-1591" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" tabindex="0" data-componentid="loadmask-1591" style="" aria-valuetext="Aguarde...">
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
<script type="text/javaScript" src="resources/help/help.js">
<script type="text/javaScript" src="resources/locale/pt_BR.js">
<script type="text/javascript">
<script type="text/javascript">
<script id="microloader" data-app="66fb43d2-c53a-4317-ab77-8188ac019a5b" type="text/javascript">
<div id="SL_balloon_obj" style="display: block;">
<div id="ext-quicktips-tip" class="x-tip x-layer x-tip-default x-border-box" role="tooltip" aria-hidden="true" aria-disabled="false" aria-labelledby="ext-quicktips-tip_header-title-textEl" style="display: none;">
<div id="loadmask-1215" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1215" style="display: none;">
<div id="loadmask-1216" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1216" style="display: none;">
<div id="loadmask-1217" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1217" style="display: none;">
<div id="ext-element-24" style="overflow: hidden; position: relative; float: left; width: 0px; height: 0px;">
<div id="window-1387" class="x-panel x-layer x-panel-default x-border-box x-resizable x-panel-resizable x-panel-default-resizable x-unselectable x-hidden-offsets" style="left: 1212px; top: 193px; width: 659px; height: 701px; z-index: 19000; right: auto;" role="dialog" aria-hidden="true" aria-disabled="false" tabindex="-1" data-componentid="window-1387">
<div id="tooltip-1076" class="x-tip x-layer x-tip-default x-border-box" style="width: 200px; z-index: 19000; height: 29px; right: auto; left: 989px; top: 607px; display: none;" role="tooltip" aria-hidden="true" aria-disabled="false">
<div id="window-1549" class="x-panel x-layer x-panel-default x-border-box x-resizable x-panel-resizable x-panel-default-resizable x-unselectable x-hidden-offsets" style="left: 1212px; top: 193px; width: 659px; height: 701px; z-index: 19000; right: auto;" role="dialog" aria-hidden="true" aria-disabled="false" tabindex="-1" data-componentid="window-1549">
<div id="typecampaigndestinationcombo-1458-picker" class="x-boundlist x-boundlist-floating x-layer x-boundlist-default x-border-box" style="width: 341px; z-index: 19000; right: auto; left: 1563px; top: 566px; height: auto; display: none;" tabindex="-1" data-componentid="typecampaigndestinationcombo-1458-picker">
<div id="ext-element-57" class="x-css-shadow" role="presentation" style="box-shadow: 0px 0px 6px rgb(136, 136, 136); z-index: 19000; right: auto; left: 1313px; top: 598px; width: 547px; height: 296px; display: none;"></div>
<div id="window-1584" class="x-panel x-layer x-panel-default x-border-box x-resizable x-panel-resizable x-panel-default-resizable x-unselectable x-hidden-offsets" style="left: 1313px; top: 594px; width: 547px; height: 300px; z-index: 19000; right: auto;" role="dialog" aria-hidden="true" aria-disabled="false" tabindex="-1" data-componentid="window-1584">
<div id="ext-element-61" class="x-css-shadow" role="presentation" style="box-shadow: 0px 0px 6px rgb(136, 136, 136); z-index: 19000; right: auto; left: 1368px; top: 673px; width: 536px; height: 21px; display: none;"></div>
<div id="phonebooktag-1471-picker" class="x-boundlist x-boundlist-floating x-layer x-boundlist-default x-border-box" style="width: 536px; z-index: 19000; right: auto; left: 1368px; top: 669px; height: auto; display: none;" tabindex="-1" data-componentid="phonebooktag-1471-picker">
<div id="loadmask-1590" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1590" style="display: none;">
<iframe id="ext-element-96" class="x-hidden-display" name="ext-element-96" src="about:blank" tabindex="-1">
</body>
</html>

**Comment by RodrigoRDC17** [comment]
<!DOCTYPE html>
<html id="ext-element-4" class="x-viewport" manifest="cache.appcache">
<head>
<body id="ext-element-1" class="x-body x-gecko x-desktop x-scroller x-border-layout-ct x-border-box x-container x-container-default" style="overflow: hidden;" data-componentid="main-1009" role="application">
<div id="panel-1010" class="x-panel x-border-item x-box-item x-panel-default" role="region" aria-hidden="false" aria-disabled="false" style="margin: 0px; width: 1920px; right: auto; left: 0px; top: 0px; height: 57px;">
<div id="panel-1030" class="x-panel x-border-item x-box-item x-panel-default" style="width: 200px; margin: 0px; right: auto; left: 0px; top: 57px; height: 639px;" role="region" aria-hidden="false" aria-disabled="false" aria-expanded="true" aria-labelledby="panel-1030-headingEl">
<div id="panel-1030-splitter" class="x-splitter x-border-item x-box-item x-splitter-default x-splitter-vertical x-unselectable" style="width: 8px; height: 639px; margin: 0px; right: auto; left: 200px; top: 57px;" role="separator" aria-hidden="false" aria-disabled="false" aria-orientation="vertical" data-exttouchaction="14" tabindex="0" data-componentid="panel-1030-splitter">
<div id="tabpanel-1031" class="x-panel x-border-item x-box-item x-panel-default" role="region" aria-hidden="false" aria-disabled="false" style="margin: 0px; width: 1712px; right: auto; left: 208px; top: 57px; height: 639px;">
<div id="tabpanel-1031-bodyWrap" class="x-panel-bodyWrap" data-ref="bodyWrap" role="presentation">
<div id="tabbar-1032" class="x-tab-bar x-docked x-tab-bar-default x-horizontal x-tab-bar-horizontal x-tab-bar-default-horizontal x-top x-tab-bar-top x-tab-bar-default-top x-docked-top x-tab-bar-docked-top x-tab-bar-default-docked-top x-noborder-trl" role="tablist" aria-hidden="false" aria-disabled="false" style="width: 1712px; right: auto; left: 0px; top: 0px;">
<div id="tabpanel-1031-body" class="x-panel-body x-panel-body-default x-panel-body-default x-noborder-trbl" data-ref="body" role="presentation" style="width: 1712px; left: 0px; top: 36px; height: 603px;">
<div id="dashboardmodule-1033" class="x-panel x-tabpanel-child x-panel-default x-hidden-offsets" role="tabpanel" aria-hidden="true" aria-disabled="false" aria-labelledby="tab-1149" aria-expanded="false" style="margin: 0px; width: 1712px; height: 878px;">
<div id="campaignmodule-1393" class="x-container x-tabpanel-child x-container-default x-border-layout-ct" style="border-width: 1px; margin: 0px; width: 1712px; height: 603px;" role="tabpanel" aria-hidden="false" aria-disabled="false" aria-labelledby="tab-1512" aria-expanded="true">
<div id="campaignlist-1394" class="x-panel x-border-item x-box-item x-panel-default x-grid" role="grid" aria-hidden="false" aria-disabled="false" aria-readonly="true" aria-multiselectable="true" aria-labelledby="campaignlist-1394_header-title-textEl" style="margin: 0px; height: 603px; right: auto; left: 0px; top: 0px; width: 1136px;">
<div id="campaignform-1440-splitter" class="x-splitter x-border-item x-box-item x-splitter-default x-splitter-vertical x-unselectable" style="border-width: 0px; width: 8px; height: 603px; margin: 0px; right: auto; left: 1136px; top: 0px;" role="separator" aria-hidden="false" aria-disabled="false" aria-orientation="vertical" data-exttouchaction="14" tabindex="0" data-componentid="campaignform-1440-splitter">
<div id="campaignform-1440-placeholder" class="x-panel-header x-header x-region-collapsed-placeholder x-region-collapsed-right-placeholder collapsed x-border-item x-box-item x-unselectable x-panel-header-default x-collapsed x-panel-header-collapsed x-panel-header-default-collapsed x-collapsed-left x-panel-header-collapsed-left x-panel-header-default-collapsed-left x-vertical x-panel-header-vertical x-panel-header-default-vertical x-left x-panel-header-left x-panel-header-default-left x-box-layout-ct x-hidden-offsets" role="toolbar" aria-hidden="true" aria-disabled="false" style="margin: 0px; height: 878px; right: auto; left: 1675px; top: 0px;" aria-expanded="true">
<div id="campaignform-1440" class="x-panel x-border-item x-box-item x-panel-default" style="width: 568px; right: auto; left: 1144px; top: 0px; margin: 0px; height: 603px;" role="presentation" aria-expanded="true" aria-busy="true" aria-describedby="loadmask-1591">
<div id="campaignform-1440_header" class="x-panel-header x-header x-header-noborder x-docked x-unselectable x-panel-header-default x-horizontal x-panel-header-horizontal x-panel-header-default-horizontal x-top x-panel-header-top x-panel-header-default-top x-docked-top x-panel-header-docked-top x-panel-header-default-docked-top x-box-layout-ct x-noborder-trl" role="toolbar" aria-hidden="false" aria-disabled="false" style="right: auto; left: 0px; top: 0px; width: 568px;">
<div id="campaignform-1440-bodyWrap" class="x-panel-bodyWrap" data-ref="bodyWrap" role="presentation">
<div id="loadmask-1591" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" tabindex="0" data-componentid="loadmask-1591" style="" aria-valuetext="Aguarde...">
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
<script type="text/javaScript" src="resources/help/help.js">
<script type="text/javaScript" src="resources/locale/pt_BR.js">
<script type="text/javascript">
<script type="text/javascript">
<script id="microloader" data-app="66fb43d2-c53a-4317-ab77-8188ac019a5b" type="text/javascript">
<div id="SL_balloon_obj" style="display: block;">
<div id="ext-quicktips-tip" class="x-tip x-layer x-tip-default x-border-box" role="tooltip" aria-hidden="true" aria-disabled="false" aria-labelledby="ext-quicktips-tip_header-title-textEl" style="display: none;">
<div id="loadmask-1215" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1215" style="display: none;">
<div id="loadmask-1216" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1216" style="display: none;">
<div id="loadmask-1217" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1217" style="display: none;">
<div id="ext-element-24" style="overflow: hidden; position: relative; float: left; width: 0px; height: 0px;">
<div id="window-1387" class="x-panel x-layer x-panel-default x-border-box x-resizable x-panel-resizable x-panel-default-resizable x-unselectable x-hidden-offsets" style="left: 1212px; top: 193px; width: 659px; height: 701px; z-index: 19000; right: auto;" role="dialog" aria-hidden="true" aria-disabled="false" tabindex="-1" data-componentid="window-1387">
<div id="tooltip-1076" class="x-tip x-layer x-tip-default x-border-box" style="width: 200px; z-index: 19000; height: 29px; right: auto; left: 989px; top: 607px; display: none;" role="tooltip" aria-hidden="true" aria-disabled="false">
<div id="window-1549" class="x-panel x-layer x-panel-default x-border-box x-resizable x-panel-resizable x-panel-default-resizable x-unselectable x-hidden-offsets" style="left: 1212px; top: 193px; width: 659px; height: 701px; z-index: 19000; right: auto;" role="dialog" aria-hidden="true" aria-disabled="false" tabindex="-1" data-componentid="window-1549">
<div id="typecampaigndestinationcombo-1458-picker" class="x-boundlist x-boundlist-floating x-layer x-boundlist-default x-border-box" style="width: 341px; z-index: 19000; right: auto; left: 1563px; top: 566px; height: auto; display: none;" tabindex="-1" data-componentid="typecampaigndestinationcombo-1458-picker">
<div id="ext-element-57" class="x-css-shadow" role="presentation" style="box-shadow: 0px 0px 6px rgb(136, 136, 136); z-index: 19000; right: auto; left: 1313px; top: 598px; width: 547px; height: 296px; display: none;"></div>
<div id="window-1584" class="x-panel x-layer x-panel-default x-border-box x-resizable x-panel-resizable x-panel-default-resizable x-unselectable x-hidden-offsets" style="left: 1313px; top: 594px; width: 547px; height: 300px; z-index: 19000; right: auto;" role="dialog" aria-hidden="true" aria-disabled="false" tabindex="-1" data-componentid="window-1584">
<div id="ext-element-61" class="x-css-shadow" role="presentation" style="box-shadow: 0px 0px 6px rgb(136, 136, 136); z-index: 19000; right: auto; left: 1368px; top: 673px; width: 536px; height: 21px; display: none;"></div>
<div id="phonebooktag-1471-picker" class="x-boundlist x-boundlist-floating x-layer x-boundlist-default x-border-box" style="width: 536px; z-index: 19000; right: auto; left: 1368px; top: 669px; height: auto; display: none;" tabindex="-1" data-componentid="phonebooktag-1471-picker">
<div id="loadmask-1590" class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="true" aria-disabled="false" tabindex="0" data-componentid="loadmask-1590" style="display: none;">
<iframe id="ext-element-96" class="x-hidden-display" name="ext-element-96" src="about:blank" tabindex="-1">
</body>
</html>

**Comment by RodrigoRDC17** [comment]
<div class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" id="loadmask-1591" tabindex="0" data-componentid="loadmask-1591" style="" aria-valuetext="Aguarde..."><div id="loadmask-1591-msgWrapEl" data-ref="msgWrapEl" class="x-mask-msg" role="presentation" style="right: auto; left: 245px; top: 274px;"><div id="loadmask-1591-msgEl" data-ref="msgEl" class="x-mask-loading x-mask-msg-inner " role="presentation"><div id="loadmask-1591-msgTextEl" data-ref="msgTextEl" class="x-mask-msg-text" role="presentation">Aguarde...</div></div></div></div>

**Comment by RodrigoRDC17** [comment]
<div class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" id="loadmask-1591" tabindex="0" data-componentid="loadmask-1591" style="" aria-valuetext="Aguarde..."><div id="loadmask-1591-msgWrapEl" data-ref="msgWrapEl" class="x-mask-msg" role="presentation" style="right: auto; left: 245px; top: 274px;"><div id="loadmask-1591-msgEl" data-ref="msgEl" class="x-mask-loading x-mask-msg-inner " role="presentation"><div id="loadmask-1591-msgTextEl" data-ref="msgTextEl" class="x-mask-msg-text" role="presentation">Aguarde...</div></div></div></div>

**Comment by RodrigoRDC17** [comment]
<div class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" id="loadmask-1591" tabindex="0" data-componentid="loadmask-1591" style="" aria-valuetext="Aguarde..."><div id="loadmask-1591-msgWrapEl" data-ref="msgWrapEl" class="x-mask-msg" role="presentation" style="right: auto; left: 245px; top: 274px;"><div id="loadmask-1591-msgEl" data-ref="msgEl" class="x-mask-loading x-mask-msg-inner " role="presentation"><div id="loadmask-1591-msgTextEl" data-ref="msgTextEl" class="x-mask-msg-text" role="presentation">Aguarde...</div></div></div></div>

**Comment by magnussolution** [comment]
Atualize seu MagnusBilling 6 e teste novamente. 

Obrigado por ajudar o projeto MagnusBilling ficar cada vez melhor

**Comment by RodrigoRDC17** [comment]
Obrigado Magnus!

Acabei de testar e o erro continua, observaçao fiz somente o update nao reinstalei!

<div class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" id="loadmask-1429" tabindex="0" data-componentid="loadmask-1429" style="" aria-valuetext="Aguarde..."><div id="loadmask-1429-msgWrapEl" data-ref="msgWrapEl" class="x-mask-msg" role="presentation" style="right: auto; left: 245px; top: 274px;"><div id="loadmask-1429-msgEl" data-ref="msgEl" class="x-mask-loading x-mask-msg-inner " role="presentation"><div id="loadmask-1429-msgTextEl" data-ref="msgTextEl" class="x-mask-msg-text" role="presentation">Aguarde...</div></div></div></div>

**Comment by RodrigoRDC17** [comment]
<div class="x-component x-border-box x-mask x-component-default" role="progressbar" aria-hidden="false" aria-disabled="false" id="loadmask-1429" tabindex="0" data-componentid="loadmask-1429" style="" aria-valuetext="Aguarde..."><div id="loadmask-1429-msgWrapEl" data-ref="msgWrapEl" class="x-mask-msg" role="presentation" style="right: auto; left: 245px; top: 274px;"><div id="loadmask-1429-msgEl" data-ref="msgEl" class="x-mask-loading x-mask-msg-inner " role="presentation"><div id="loadmask-1429-msgTextEl" data-ref="msgTextEl" class="x-mask-msg-text" role="presentation">Aguarde...</div></div></div></div>
