### ISSUE TITLE
Filtro "por usuário" na tela "Membros de Fila" não funciona

### ISSUE THREAD

**Issue by viniciusbarretobr** [magnussolution/magnusbilling#490]
Quando a tela "Membros de Fila" e tento filtrar a coluna para exibir os membros de fila de apenas um usuário em específico, o filtro não é aplicado.

**Comment by magnussolution** [comment]
Boa tarde, acabei de arrumar o filtro, desculpe a demora.

De nada.

Att. Adilson Magnus
