### ISSUE TITLE
DID INCOMING ERROR

### ISSUE THREAD

**Issue by ajtel** [magnussolution/magnusbilling#492]
When we receive a DID call from any customer, in Live calls it assing to any user not to real user, some customers compling what f... is this i did not receive that call... 
can you fix it?

**Comment by magnussolution** [comment]
hi, log please.

**Comment by ajtel** [comment]
![image](https://user-images.githubusercontent.com/8538738/104109094-f50cf480-528f-11eb-8232-2fc412be20f5.png)
![image](https://user-images.githubusercontent.com/8538738/104109100-0b1ab500-5290-11eb-8d24-ed46bd12d928.png)
![image](https://user-images.githubusercontent.com/8538738/104109131-4fa65080-5290-11eb-8656-27ad4505e5fa.png)

**Comment by magnussolution** [comment]
i not understand the issue. Can you send the asterisk log verbose 25
