### ISSUE TITLE
Restricted number not working

### ISSUE THREAD

**Issue by ajtel** [magnussolution/magnusbilling#493]
When you add a number in list... it seem to send no answer to incoming caller and play somea audio or reject call it does not happend.
also outboud blocks does not works.
![image](https://user-images.githubusercontent.com/8538738/104104383-540d4200-526d-11eb-82cb-8edcf759b2b1.png)

**Comment by magnussolution** [comment]
Asterisk LOG please.

**Comment by ajtel** [comment]
i attach here
[messages.txt](https://github.com/magnussolution/magnusbilling7/files/5791846/messages.txt)
[asterisk-rv.txt](https://github.com/magnussolution/magnusbilling7/files/5791847/asterisk-rv.txt)

**Comment by ajtel** [comment]
any news? can i help?

**Comment by magnussolution** [comment]
in the log that you sent you need add the number 5559890788 on the menu restrict phone number, type incoming to user AJTELMEXICO

**Comment by ajtel** [comment]
i do but not block... can you review what i can do for that?

**Comment by magnussolution** [comment]
update your magnusbilling and try again
