### ISSUE TITLE
uploading of rates

### ISSUE THREAD

**Issue by uzair329** [magnussolution/magnusbilling#496]
Team

I have three different magnus switch on three different VPS in all three i am facing same issue of uploading the provider rates and rates in tariff. It either stuck for hours or it takes 2 3 hours to upload only 1.5 mb file . I even make 3 4 parts of one vendor rate sheet but it still taking so  much time . I think their is some issue in DB processing in magnus

**Comment by ajtel** [comment]
what PHP version?  do you review is CSV File?

**Comment by uzair329** [comment]
PHP 7.1.33 (cli) (built: Mar 17 2020 09:14:41) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

yes we upload in CSV format

**Comment by uzair329** [comment]
when we run optimize database command it wont work it reject all tables

**Comment by magnussolution** [comment]
i just make a test here, and 1.5M import in 15 seconds.

**Comment by uzair329** [comment]
Is this because of net or file load? How many prefixes you load??
________________________________
