### ISSUE TITLE
Caller ID set by softphone #375

### ISSUE THREAD

**Issue by xceedconnections** [magnussolution/magnusbilling#497]
i added
[callerid]
exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})
IN extension_magnus.conf

how to set the context in magnus billing and forward call to the billing context.

please show an example.

for more info visit https://github.com/magnussolution/magnusbilling7/issues/375 to solve it

**Comment by xceedconnections** [comment]
@itsshimmer @magnussolution

**Comment by magnussolution** [comment]
add this line on the context billing exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})

**Comment by xceedconnections** [comment]
LIKE THIS IN extension_magnus.conf ????


> 
> 
> add this line on the context billing exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})

![magnus](https://user-images.githubusercontent.com/77621326/108371879-072f6a80-7220-11eb-9ced-8b907832dd62.png)

**Comment by uzair329** [comment]
OR you can write this command in different context and than use Goto option like this we do for one client and set his context to callerid
[callerid]
exten => _X.,1,Set(cli2=${SIP_HEADER(Remote-Party-ID)})
exten => _X.,n,Set(cli=${CUT(cli2,\",2)})
exten => _X.,n,Noop(${cli})
exten => _X.,n,Set(CALLERID(num)=XXXXXXXXX)
exten => _X.,n,Goto(billing,${EXTEN},1)
exten => _X.,n,Hangup

**Comment by uzair329** [comment]
add these lines in extensions.conf

**Comment by xceedconnections** [comment]
@uzair329 tried this.
its not working. can you please provide me your contact number at my email so i can contact you
xceedconnections@gmail.com

**Comment by uzair329** [comment]
Please share what you did? And what is your main objective?
________________________________

**Comment by xceedconnections** [comment]
I added

[callerid]
exten => _X.,1,Set(cli2=${SIP_HEADER(Remote-Party-ID)})
exten => _X.,n,Set(cli=${CUT(cli2,",2)})
exten => _X.,n,Noop(${cli})
exten => _X.,n,Set(CALLERID(num)=XXXXXXXXX)
exten => _X.,n,Goto(billing,${EXTEN},1)
exten => _X.,n,Hangup

in extensions.conf.

also in user context I set billing to callerID. 

and then tried dialing calls are not going through. 


what I want is 

my customers can change callerID from eyebeam. 
right now they are changing callerID from magnus billing portal.

**Comment by xceedconnections** [comment]
@uzair329 
i want my users to change the callerid using xlite/ eyebeam.
what ever number they mention in eyebeam display, shoudl be used as their callerid.

**Comment by uzair329** [comment]
First check in which variable you are receiving callerid from eyebeam when client is setting and in which format you are getting. You can check this by running sip debug
________________________________

**Comment by foryourhost** [comment]
i already add this

[dincli]
exten => _[*0-9].,1,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php$
same => n,Hangup()

exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})

exten => h,1,hangup()

exten => *111,1,VoiceMailMain(${CHANNEL(peername)}@dincli)
same => n,Hangup()

but error is happen

Executing [12158664168@dincli:1] Set("SIP/97833-00005160", "CALLERID(nun) =13342342407") in new stack
[2021-06-04 18:13:37] ERROR[2008][C-0000798d]: func_callerid.c:1271 callerid_wri te: Unknown callerid data type 'nun'.
-- Executing [12158664168@dincli:2] Hangup("SIP/97833-00005160", "") in new stack
== Spawn extension (dincli, 12158664168, 2) exited non-zero on 'SIP/97833-0000 5160'
-- Executing [h@dincli:1] Hangup("SIP/97833-00005160", "") in new stack
== Spawn extension (dincli, h, 1) exited non-zero on 'SIP/97833-00005160'

**Comment by Madji** [comment]
Error this 
exten => _X.,1,Set(CALLERID(nun)=${CALLERID(name)})

Right
exten => _X.,1,Set(CALLERID(num)=${CALLERID(name)})

**Comment by foryourhost** [comment]
thanks for your replay but we replace that but call is not going to 

<------------>
    -- Executing [12158664168@dincli:1] Set("SIP/97833-00005165", "CALLERID(num)=13342342407") in new stack
    -- Executing [12158664168@dincli:2] Hangup("SIP/97833-00005165", "") in new stack
  == Spawn extension (dincli, 12158664168, 2) exited non-zero on 'SIP/97833-00005165'
    -- Executing [h@dincli:1] Hangup("SIP/97833-00005165", "") in new stack
  == Spawn extension (dincli, h, 1) exited non-zero on 'SIP/97833-00005165'
Scheduling destruction of SIP dialog 'd34f08776e6fdc06NzJmMGVmYzQwZDA3MGZjNTMxMzA3N2U3ZGNiZjRjMDE.' in 30720 ms (Method: INVITE)

<--- Reliably Transmitting (NAT) to 157.40.251.71:7636 --->
SIP/2.0 603 Declined
Via: SIP/2.0/UDP 157.40.251.71:7636;branch=z9hG4bK-d87543-2b35a1784a3d1074-1--d87543-;received=157.40.251.71;rport=7636
From: "13342342407"<sip:97833@XX.188.186.XXX>;tag=617bf73e
To: "12158664168"<sip:12158664168@XX.188.186.XXX>;tag=as441136bb
Call-ID: d34f08776e6fdc06NzJmMGVmYzQwZDA3MGZjNTMxMzA3N2U3ZGNiZjRjMDE.
CSeq: 2 INVITE
Server: MagnusBilling
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


<------------>

**Comment by rribeiro** [comment]
Solution?
Need a exten id on exten-exten calls...

**Comment by iswami1994** [comment]
just copy and pest below 

### **root@debian-8gb-fsn1-1:/etc/asterisk# nano extensions_magnus.conf**


[billing]
exten => _[*0-9].,1,Set(CALLERID(num)=${CALLERID(name)})
 same => n,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php")
 same => n,Hangup()

exten => _+X.,1,Goto(billing,${EXTEN:1},1)

exten => h,1,Hangup()

exten => *111,1,VoiceMailMain(${CHANNEL(peername)}@billing)
 same => n,Hangup()

[trunk_answer_handler]
exten => s,1,Set(MASTER_CHANNEL(TRUNKANSWERTIME)=${EPOCH})
  same => n,Return()

**Comment by Vineet-23** [comment]
> just copy and pest below
> 
> ### **root@debian-8gb-fsn1-1:/etc/asterisk# nano extensions_magnus.conf**
> [billing] exten => _[*0-9].,1,Set(CALLERID(num)=${CALLERID(name)}) same => n,AGI("/var/www/html/mbilling/resources/asterisk/mbilling.php") same => n,Hangup()
> 
> exten => _+X.,1,Goto(billing,${EXTEN:1},1)
> 
> exten => h,1,Hangup()
> 
> exten => *111,1,VoiceMailMain(${CHANNEL(peername)}@billing) same => n,Hangup()
> 
> [trunk_answer_handler] exten => s,1,Set(MASTER_CHANNEL(TRUNKANSWERTIME)=${EPOCH}) same => n,Return()

I tried but it didn't worked. FYI my provider support support P-Asserted-Identity (PAID) and Remote-Party-ID (RPID) 
Kindly help
