### ISSUE TITLE
AMD and Random caller ID

### ISSUE THREAD

**Issue by shahrukhfiaz** [magnussolution/magnusbilling#499]
i want to enable AMD and add random caller ID line in dialplan

**Comment by xceedconnections** [comment]
@shahrukhfiaz
brother. did you get solution for caller I'd set by soft client eyebeam??

**Comment by xceedconnections** [comment]
please let me know if you got solution for it. it will be a big help..

**Comment by shahrukhfiaz** [comment]
no I didn't. They don't guide here.
