### ISSUE TITLE
O NUMERO NAO PODE SER ENCONTRADO

### ISSUE THREAD

**Issue by spfdias** [magnussolution/magnusbilling#501]
Bom dia, criei um tronco entre o Magnus e o Issabel onde meus provedores estao no Issabel, criei um usuario e conta sip e registrei um softphone, mas quando tento fazer ligacao ele informa que o numero nao pode ser encontrado, e nao tenho nada de log em console asterisk -rvvvvvvv
o que fazer para que as chamadas tarifem porem saiam pelo trunk do issabel ?

**Comment by itsshimmer** [comment]
crie tarifas para que as chamdas possam sair

**Comment by spfdias** [comment]
> crie tarifas para que as chamdas possam sair

Criei:
Nome - gold
destino - brasil
grupo - turnk issabel
preco venda - 0
bloco minimo - 30
bloco tarifacao - 6
tempo para tarifar - 3
tempo adicional -
incluir pac gratis - nao
status - ativo

La no meu usuario tem :
grupo - client
plano -gold
regra prefixo  - */55/10,*/55/11
ativo - ativo

o que esta de errado ?

**Comment by magnussolution** [comment]
Este lugar é para reportar BUGs e não para solicitar ajuda/suporte.

Para solicitar ajuda por favor use o grupo no Telegram https://t.me/joinchat/C0lEoxzG8Uu5jr9d

**Comment by spfdias** [comment]
Parabens por sua ignorancia idiota.
