### ISSUE TITLE
Configuração de horário Individual dos dias na URA

### ISSUE THREAD

**Issue by NerdServicesBrazil** [magnussolution/magnusbilling#502]
Bom dia Sr Adilson Magnus. Como sugestão seria interessante que nas configurações da URA fosse possível configurar o horário de cada dia da semana individualmente, pois existem estabelecimentos que trabalham de terça a Domingo por exemplo e não é possível configurar o horário individual da segunda. 

Grande abraço e Parabéns pelo trabalho.

**Comment by magnussolution** [comment]
isso ja existe.
