### ISSUE TITLE
Import phone number to phonebook

### ISSUE THREAD

**Issue by voiptelecom** [magnussolution/magnusbilling#508]
i'm trying to import numbers to a phonebook and have this error

![Captura de Pantalla 2021-03-23 a la(s) 12 31 54](https://user-images.githubusercontent.com/62485767/112173203-1f562900-8bd4-11eb-8763-7585673d679f.png)

**Comment by PlatinVoip** [comment]
Just tested, it is working, make sure you use the same as provided in example:

number, name, city
297238273728, Joe, Washington DC
289378273263, Donald, Miami
928326327636, George, Crawford
928372732678, Bill, New York
782366352673, Ronald, New York
827329382939, Jimmy, New York

**Comment by fabriciosprj** [comment]
erro ao importar

![Capturar](https://github.com/magnussolution/magnusbilling7/assets/130469931/42656918-e6f6-4812-90fe-4fad7a58f0ba)
 
number
21912345678
