### ISSUE TITLE
Problema compra de crédito

### ISSUE THREAD

**Issue by sipserver** [magnussolution/magnusbilling#511]
Após a revenda fazer o preenchimento do valor de compra e no meu caso escolher o método de pagamento GerenciaNet  e clicar em próximo, aparece esse erro .

Internal Server Error
Undefined variable: modelSip
An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you.

Versão do magnus 7.6.5
![erro compra crédito](https://user-images.githubusercontent.com/50499925/115147551-d5752d00-a031-11eb-9e27-77127b59d175.PNG)

**Comment by sipserver** [comment]
Fiz a atualização para a versão 7.6.7 e o problema continua.
![versão](https://user-images.githubusercontent.com/50499925/115148026-225a0300-a034-11eb-85b7-9a6eae4f7d88.PNG)

**Comment by magnussolution** [comment]
fixed
