### ISSUE TITLE
CDbConnection failed to open the DB connection.

### ISSUE THREAD

**Issue by aymen3009** [magnussolution/magnusbilling#512]
when i open @IP/mbilling/index.php
i got this error
Internal Server Error
CDbConnection failed to open the DB connection.
An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

it used to be a stoage problem so when i delete some logs everything back to normal  but not anymore

**Comment by MShoaib67** [comment]
Have you tried a reboot after deleting up the files from the server ?

**Comment by magnussolution** [comment]
you have a mysql issue. Try restart mysql, and check if you have free space on HD
