### ISSUE TITLE
DID not billed

### ISSUE THREAD

**Issue by ajtel** [magnussolution/magnusbilling#516]
FROM 7.6.6 TO 7.6.8
did is not billed to customer

**To Reproduce**
1. Go to 'DID
2. Click on CREATE A NEW DID'
3. Scroll down to 'ADD A NEW DID..'
4. Click on CREATE A DID DESTINATION
5. it supouse it bill the did to customer now it do not happend, also with old did.

**Comment by voiptelecom** [comment]
I have the same problem from 7.6.7 to 7.6.8 and I lost like 300 USD.

Do you need any help with this module?

Also, can we go to asterisk 18.3.0?

Reagards,

**Comment by magnussolution** [comment]
hi, had you configured the billing tab on DID? I simulate here and bill correct according my regular expression

**Comment by magnussolution** [comment]
> I have the same problem from 7.6.7 to 7.6.8 and I lost like 300 USD.
> 
> Do you need any help with this module?
> 
> Also, can we go to asterisk 18.3.0?
> 
> Reagards,

no, you can't update asterisk

**Comment by ajtel** [comment]
ONe question Mr. Adilson.... why not upgrade asterisk any error you found in newer version?? or some data fields that not match regual expresions? 

DID:  i fill my DB is damaged any idea to repari to avoid reconstruct all.?

**Comment by RodrigoRDC17** [comment]
Realmente o sistema na versao 7.6.8 nao esta tarifando o cliente, na hora de ativaçao voce pode configurar a taxa de ativaçao e cobrança mensal e nao ocorre o lançamento!

Desde a atualizaçao nao fez uma cobrança se quer!

Ativei uma did para teste e ativa normalmente porem nao cobra a ativaçao mesmo setado o valor!

**Comment by ajtel** [comment]
please Adilson can you help fixing this is not my only side..

**Comment by voiptelecom** [comment]
> > I have the same problem from 7.6.7 to 7.6.8 and I lost like 300 USD.
> > 
> > Do you need any help with this module?
> > 
> > Also, can we go to asterisk 18.3.0?
> > 
> > Reagards,
> 
> no, you can't update asterisk

I did update asterisk to 18.3.0 and implement TLS/SRTP, the only functionality that I don't see working is "codec" on call online, because after the asterisk 14 or 15 they change it to "format". Is working better and fix a lot of security issues that comes from version 13.35.

**Comment by RodrigoRDC17** [comment]
so para completar a informaçao a bilhetagem esta funcionando ( usando as regras de expressao correta), porem a cobrança dos servicos nao, tais como ativaçao, mensal isso nao esta funcionando!

**Comment by magnussolution** [comment]
fixed
