### ISSUE TITLE
DID não tarifando na Ativação e Cobrança Mensal.

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#517]
Na Ultima versão 7.6.8 não está tarifando o cliente mensalmente durante a ativação também não está tarifando não ocorrendo o lançamento.
a instalação foi feita do zero.

Só para completar a informação de bilhetagem está funcionando (usando as regras de expressão regular correta). São duas coisas diferente.

**Comment by magnussolution** [comment]
solucionado, atualize
