### ISSUE TITLE
Problema para habilitar serviço no plano

### ISSUE THREAD

**Issue by renatosabatini** [magnussolution/magnusbilling#518]
Versão instalada 7.6.8

Problema: Quando habilitamos o serviço no plano o mesmo não fixa. Veja os prints:

![image](https://user-images.githubusercontent.com/68757900/119560803-c6914100-bd7a-11eb-989e-69f000c7231d.png)

debug:
![image](https://user-images.githubusercontent.com/68757900/119560908-e6c10000-bd7a-11eb-8053-e2aace2c458a.png)

Após atualizarmos a pagina o serviço não aparece mais.
![image](https://user-images.githubusercontent.com/68757900/119561236-4f0fe180-bd7b-11eb-8af5-57c48b877aec.png)

- Já limpamos o cache 
- Usamos 3 navegadores diferentes 
nada resolveu.

desde já muito obrigado 

Att. 

Renato

**Comment by magnussolution** [comment]
ola, crie o plano, e depois edite o mesmo para selecionar os serviços

**Comment by renatosabatini** [comment]
> ola, crie o plano, e depois edite o mesmo para selecionar os serviços

Os prints é exatamente de uma edição do plano. Os testes foram feitos, criando novo plano, editando o plano e fazendo edição em massa, em nenhum dos casos deu certo.
