### ISSUE TITLE
Problemas nos Temas (metade em ingles outra metade em Portugues)

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#519]
Como demonstrado na foto abaixo alguns temas ficam metade em ingles e metade em português conforme a foto abaixo 

![image](https://user-images.githubusercontent.com/28572532/119597895-4984bc80-bdb8-11eb-85b0-c50d21c71160.png)

**Comment by magnussolution** [comment]
não foi possível simular. Nos testes realizado funcionou tudo corretamente.
