### ISSUE TITLE
Problemas na Pagina de Uso dos DIDS

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#520]
**_Conforme fotos abaixo o sistema não esta demonstrando os Usos dos DIDS e nem efetuando a cobrança,,,,,_**

![image](https://user-images.githubusercontent.com/28572532/119598133-be57f680-bdb8-11eb-85f9-8ce28bb15c47.png)

**Comment by magnussolution** [comment]
não foi possível simular, por favor ser detalhista e enviar passos para simular o problema.
