### ISSUE TITLE
Problema ao renomear Menu de Clientes

### ISSUE THREAD

**Issue by limagal** [magnussolution/magnusbilling#522]
Ao renomear o submenu "Usuários" para "Clientes" e "Contas SIP" para "Ramais", e no momento de adicionar novo usuário, na aba Geral, no campo "Grupo" não apareciam as opções de Client, Agent, Administrator para escolher, ficava tudo em branco. Tive que voltar para os o nome do menu que vem originalmente no sistema para voltar a aparecer.

**Comment by magnussolution** [comment]
Ola, seu relato não pode ser simulado, por tanto sera fechado. O nome dos menus são somente tradução, não tenho relação com outras funções.

![Screen Shot 2021-09-14 at 13 22 13](https://user-images.githubusercontent.com/17835020/133296062-09bc06f4-a908-4c44-abd0-1258619d35dc.png)
