### ISSUE TITLE
Erro de direcionamento do pagseguro

### ISSUE THREAD

**Issue by oduqueneto** [magnussolution/magnusbilling#524]
Ao escolher no formulário, "o nome da cidade" esta o nome completo(porém o pagseguro só aceita abreviação do estado, logo erro acontece ao comprar.

Este erro já foi informado a Adilson onde o mesmo já informou que fez alteração onde tentamos validar a atualização mais não conseguimos.

[Atenciosamente,](![erro_mag](https://user-images.githubusercontent.com/85645481/121418217-1c501680-c941-11eb-9435-1ff3ac37f9cf.JPG))

Oduque neto

**Comment by magnussolution** [comment]
![Screen Shot 2021-06-16 at 09 13 51](https://user-images.githubusercontent.com/17835020/122216976-59f1f980-ce83-11eb-8848-abc66178866f.png)
![Screen Shot 2021-06-16 at 09 14 03](https://user-images.githubusercontent.com/17835020/122216988-5c545380-ce83-11eb-94d3-2ecca67b5c7c.png)
![Screen Shot 2021-06-16 at 09 14 24](https://user-images.githubusercontent.com/17835020/122216996-5e1e1700-ce83-11eb-994e-86c5d12d7d18.png)

**Comment by magnussolution** [comment]
ja foi solucionado, atualize e teste
