### ISSUE TITLE
force callerID from trunk

### ISSUE THREAD

**Issue by xceedconnections** [magnussolution/magnusbilling#527]
Hello,
is there is any option to force a special callerid from the trunk.
no matter client put whatever number as their callerid, trunk should pass the callerid mentioned by the admin.

i mean , all calls that as passing through the trunk , must be using callerid mentioned in the trunk.

**Comment by MShoaib67** [comment]
That is already available. 

Use CallerID Filed to enforce CallerID for trunk or SIP Users.

**Comment by xceedconnections** [comment]
in sip we have the option available, but client can change the callerid from his account.
how to force callerid from the trunk.
client put whatever number he wants but customer should see callerid force by the trunk.

**Comment by uzair329** [comment]
For this You can right custom diaplan context for client than forward call to billing context.
1st you need to write new context and fix callerid in it
2nd change context from GUI sip users --> Additional ---> Context

Context Example

[fixcallerid]
exten => _X.,1,Set(CALLERID(num)=XXXXXXX)
exten => _X.,n,Goto(billing,${EXTEN},1)
exten => _X.,n(Hangup),Hangup

change the context in additional of that client fixcallerid

Change XXXX with you callerid you want

**Comment by xceedconnections** [comment]
I know this,
cant we force callerID from the trunk??
I mean directly from gui. instead of making changes to all the sip users
context and editing magnus extensions.conf file..

**Comment by YosefAdPro** [comment]
I think it would be more correct if there was an option to mark that a user can only take a callerID from numbers associated with him as a DID.

**Comment by magnussolution** [comment]
> in sip we have the option available, but client can change the callerid from his account.
> how to force callerid from the trunk.
> client put whatever number he wants but customer should see callerid force by the trunk.

on the trunk set the FROMUSER. It will be every used as callerid

**Comment by xceedconnections** [comment]
@magnussolution 
I entered callerid number to from user field. But still its not showing callerid number .

**Comment by magnussolution** [comment]
monitor the call with SNGREP and check the "From:" tag on the INVITE sent to your trunk. If you set the Fromuser on the trunk, is this value that will sent to you trunk.

Ask to your trunk if the caller id not work.

**Comment by GalacticAust** [comment]
This may have been solved but i did a test and you can override the CID on the trunk 

Set CID in the FromUser and ensure you have sendrpid to NO
