### ISSUE TITLE
Error exporting the rates (tariffs) to CSV

### ISSUE THREAD

**Issue by dcitelecom** [magnussolution/magnusbilling#534]
I am running mbilling version 7.7.4 on Debian 10

**Describe the bug**
I can't export the rates (tariffs) to CSV. 

**To Reproduce**
1. Go to 'Tariffs'
2. Click on 'Export CSV'
3. Page opens with URL
http://mb.xxxxtel.com/mbilling/index.php/rate/csv/?columns=[{%22header%22:%22Prefix%22,%22dataIndex%22:%22idPrefixprefix%22},{%22header%22:%22Destination%22,%22dataIndex%22:%22idPrefixdestination%22},{%22header%22:%22Sell%20price%22,%22dataIndex%22:%22rateinitial%22},{%22header%22:%22Initial%20block%22,%22dataIndex%22:%22initblock%22},{%22header%22:%22Billing%20block%22,%22dataIndex%22:%22billingblock%22},{%22header%22:%22Trunk%20groups%22,%22dataIndex%22:%22id_trunk_group%22},{%22header%22:%22Plan%22,%22dataIndex%22:%22id_plan%22}]&filter=[]&sort=[]&group=
4. and I get the error " This page isn’t working right now mb.xxxtel.com can't currently handle this request.
HTTP ERROR 500"

**Desktop (please complete the following information):**
 - Windows 10
 - Microsoft Edge (Chrome)
 - newest version

**Additional context**
Ideally I would like to filter for my rate plan and export the records to CSV so we can list the rates on our website

**Comment by magnussolution** [comment]
try do it

```
rm -rf /var/www/html/mbilling/tmp
mkdir /var/www/html/mbilling/tmp
chown -R asterisk:asterisk /var/www/html/mbilling/tmp
```

**Comment by yurikurka** [comment]
First, clear the cookies and cache in your browser.

Em seg, 13 de set de 2021 19:17, haseebraza93 ***@***.***>
escreveu:

**Comment by dcitelecom** [comment]
> try do it
> 
> ```
> rm -rf /var/www/html/mbilling/tmp
> mkdir /var/www/html/mbilling/tmp
> chown -R asterisk:asterisk /var/www/html/mbilling/tmp
> ```

Thank you for the suggestion but the issue does not change. I get the same error message as before. Have you tried to export the rates on your system? Here is the error URL again (I noticed some errors above)

http://mb.xxx.com/mbilling/index.php/rate/csv/?columns=[{"header":"Prefix","dataIndex":"idPrefixprefix"},{"header":"Destination","dataIndex":"idPrefixdestination"},{"header":"Sell%20price","dataIndex":"rateinitial"},{"header":"Initial%20block","dataIndex":"initblock"},{"header":"Billing%20block","dataIndex":"billingblock"},{"header":"Trunk%20groups","dataIndex":"id_trunk_group"},{"header":"Plan","dataIndex":"id_plan"}]&filter=[]&sort=[]&group=

This page isn’t working right now mb.xxxtel.com can't currently handle this request. HTTP ERROR 500"

**Comment by dcitelecom** [comment]
You can close this issue. In the end, it was a corrupted rated table that caused all the problems.
