### ISSUE TITLE
Erro no Registro do CDR

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#54]
O CDR indica hora errada apos efetuar uma ligação!
O time zone do servidor e o horario do banco de dados estao corretos

Favor verificar.

[Hora Banco Errado.zip](https://github.com/magnussolution/magnusbilling6/files/1327079/Hora.Banco.Errado.zip)

**Comment by magnussolution** [comment]
Questoes de hora nao é problema no Magnusbilling. O magnusbilling usa a Hora do php e do proprio LINUX.

Verifique o localtime do linux e o "date.timezone" do php. Tambem verifique o time do hardware.

**Comment by yurikurka** [comment]
------------ FAVOR LER OS COMENTARIOS ABAIXO---------------------------

As versões do PHP são iguais NO 5 E NO 6
O TIME ZONE DA MAQUINA ESTÁ CORRETO
NA VERSÃO 5 COM MESMA VERSÃO DO PHP FUNCIONA
NA VERSÃO 6 COM MESMA VERSÃO DO PHP ----NÃO----FUNCIONA
HORA DO BANCO DE DADOS ESTÁ CORRETO

ALGUM PROBLEMA NA VERSÃO 6 EXISTE.

FAVOR VERIFICAR E LER OS COMENTÁRIOS ACIMA;**

Abri outro ChaMADO

**Comment by magnussolution** [comment]
MagnusBilling sempre que manda salvar no banco de dados, usa as funções:

PHP 
date() ou time()
mysql
NOW()

ou seja, se a data não esta correta, é a hora do servidor que não esta ok. Se vc discorda, por favor nos ajude a encontrar o motivo e compartilhe a solução.

Testei em um servidor de teste e funcionou perfeitamente.

**Comment by magnussolution** [comment]
realizei mudanças no código para evitar o problema de timezone, pegando a função mais adequada.

Atualize e realize seus testes
