### ISSUE TITLE
Transfer cannot be possible from IVR calls to ALIAS

### ISSUE THREAD

**Issue by BR-Pedro** [magnussolution/magnusbilling#540]
When I receive a call from IVR, it no been possible transfer to a ALIAS number, just an UserID.
UserID "WW100", Alias "100".. the msg is "is not possible to find".
Internal transfers to Alias is OK.. only externa coming from IVR, no.

**Comment by magnussolution** [comment]
hi, active verbose to 25, make a call and send the log

**Comment by BR-Pedro** [comment]
Solved!!!

Thanks Adilson... great job.
Great assistance.
