### ISSUE TITLE
Problema nos TEMAS

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#55]
Em determinados momentos o tema escolhido e perdido na Interface web isso ocorreu duas vezes no Chrome!

**Comment by magnussolution** [comment]
desculpe, mas nao entendo o problema. 

antes de abrir um issue, leia as recomendações de como reportar um bug.

https://github.com/magnussolution/magnusbilling6/issues/56

**Comment by yurikurka** [comment]
Como vc quer que eu reporte um BUG que aconteceu duas vez e não esperava por isso? Nem no navegador voce consegue pegar uma coisa que ja passou e foi momentania!

**Comment by magnussolution** [comment]
pergunto a mesma coisa, como vc quer que eu adivinhe algo que aconteceu no seu navegador que vc não tem nem ideia do como reproduzir?
