### ISSUE TITLE
Add few options in Report

### ISSUE THREAD

**Issue by xceedconnections** [magnussolution/magnusbilling#550]
in CDR reports
please make search better to search by user, callerid, destination number , by trunk

please Add advance search feature, it helps diagnosing disturbs routes

**Comment by magnussolution** [comment]
Hello. Please read the wiki!!!!

https://wiki.magnusbilling.org/en/source/get_started/interface.html#filter-system

Best regards

**Comment by xceedconnections** [comment]
Fixed
