### ISSUE TITLE
DID RELEASE AND DID DELETE

### ISSUE THREAD

**Issue by xceedconnections** [magnussolution/magnusbilling#555]
hello sir
I am using latest version of magnusbilling
I think there should be few more options to be added to make it more powerfull

1. Should all a button to release all did rather than 1 by 1. It takes a lot of time.
2.  Selecting all dids and then delete option not working, 1 by 1 deleting did is working fine.
3. After changes in CPS on dashboard, its not resetting everyday. also giving wrong details 

Please fix and add these features,

**Comment by ajtel** [comment]
same here... 7.8.0.2 did not release

**Comment by magnussolution** [comment]
it was created some weeks ago, update your magnusbilling

**Comment by xceedconnections** [comment]
Fixed
