### ISSUE TITLE
Testes na opção revenda

### ISSUE THREAD

**Issue by lcimas** [magnussolution/magnusbilling#6]
Testei uma conta como **AGENT** e detectei os seguintes problemas:

Quando crio uma conta para um cliente e salvo o plano não salva e fica com um numero no lugar do nome do plano e após alguns segundos a mesma conta é deletada automaticamente.

Quando gero usuário automático não consigo selecionar um plano.

quando crio uma conta voip ela desaparece sendo possível visualizar apenas como administrador

Sistema instalado em uma vps com centos 7 64bits
http://144.217.221.221
usuário: root
senha: magnus

**Comment by hilariovoip** [comment]
Acessei seu servidor e vi que está usando a versao 6.0.0 tenta atualizar para a ultima versao 6.0.3 e veja se arrumou.

**Comment by magnussolution** [comment]
Voce nao selecionou o plano para os clientes do agente.

Como administrador, edite seu agente e selecione um plano. Logo volte para o painel de agente e tente novamente.
