### ISSUE TITLE
Erro no Campo PREFIXO dentro do Agent [Revenda]

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#62]
Bom dia! Segue em anexo o video para exemplificar o erro que ocorre na parte de tarifas do Agent!

Os prefixos não são visualizados, mesmo depois de criados se ocorrer uma atualização de pagina!

Veja o video para melhor entendimento por favor!
[Erro PREFIXO AGENT.zip](https://github.com/magnussolution/magnusbilling6/files/1332868/Erro.PREFIXO.AGENT.zip)

**Comment by magnussolution** [comment]
bom dia. Agente nao tem que criar PREFIXO. vc deve retirar esta permissão do agente. Na instalação a permissão de prefixos é somente para ler, mas não mostrar no menu. 

Quando um agente cria um plano, o Magnusbilling cola a tabela de compra dele, assim ele não precisa ficar trabalhando com tarifas, somente alterar o preço que ele quer vender.

**Comment by RodrigoRDC17** [comment]
Obrigado pelo retorno! Bom trabalho!
