### ISSUE TITLE
Chamadas ONLINE nao informa o codec utilizado!

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#63]
Não sei se o modelo da versão, mas observei que na versâo 6 nâo mostra o codec utilizado na chamada Online!

Claro que vi que implantou o recurso de saber detalhes da chamada!

**Comment by magnussolution** [comment]
ola, isso foi informado no Webinar que foi modificado, vc precisa clicar sobre a chamada para poder ver mais detalhes sobre ela, como CODEC

**Comment by RodrigoRDC17** [comment]
Obrigado Adilson, mas seria interessante deixe ainda mostrando pois imagine com trafego voce fazendo transcoder e acabando sua maquina rsrsr

**Comment by magnussolution** [comment]
foi explicado no Webinar o porque de ter retirado. Voce estava no webinar?
