### ISSUE TITLE
Provisionamento da ATA LINKSYS

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#65]
Fiz teste no provisionamento e apesar de capturar registro nao conecta pois tem um erro desconhecido;

nao tem firewall ativado e nenhuma porta bloqueada!

Voce poderia fazer o teste e me reportar por favor, pois nos meus testes nao funcionou e seguir o video de configuraçao a qual nao tem segredo!

**Comment by magnussolution** [comment]
voce consegue deixar um ATA online e nos enviar o acesso para poder fazer testes?

**Comment by RodrigoRDC17** [comment]
sim consigo meu amigo!

**Comment by RodrigoRDC17** [comment]
O provisionamento estou fazendo numa vm, se precisar colocar no seu servidor de testes te passo o serial e mac

**Comment by RodrigoRDC17** [comment]
Olá magnus qual informaçao precisa? Nao funciona o provisionamento a principio achei que era algo do fail2ban porem mesmo destivando tudo ainda nao funciona! Se precisar fazer um teste caso voce nao tenha um equipamento Linksys posso informar a voce o serial e mac para tentar fazer no seu servidor!
