### ISSUE TITLE
DID NAO TARIFANDO

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#66]
Boa noite! Fizemos varios testes pra constatar que a DID nao está tarifando mesmo com a configuraçao correta! Foram adicionados os prefixos de fixo e movel e colocado cadencia!

**Comment by magnussolution** [comment]
informe como vc esta configurando, manda um print da tela do DID e do DESTINATION

**Comment by RodrigoRDC17** [comment]
[DID NAO TARIFA.zip](https://github.com/magnussolution/magnusbilling6/files/1337152/DID.NAO.TARIFA.zip)

**Comment by yurikurka** [comment]
Continua nao tarifando mesmo apos o update!

**Comment by RodrigoRDC17** [comment]
Bom dia Adilson, apos a atualizacao foi normalizado!
