### ISSUE TITLE
How to setup per minute DID for Incoming minutes.

### ISSUE THREAD

**Issue by TZBDT** [magnussolution/magnusbilling#666]
I have just installed Magnus billing and was working on DIDs. I was able to successfully setup a month to month DID with with unlimited minutes plan. But When I try to configure a DID with per minute incoming charge like a toll free number. I am not able to configure it. 

I have assigned a billing rate for DID plan and if no amount is added call doesn't come. But when I add balance to the client account call comes in but no balance is deducted for incoming minutes.

I have no idea on how this could be enabled. Attaching my DID Billing tab configuration.

Can someone help?

![image](https://github.com/magnussolution/magnusbilling7/assets/160650476/0c782b30-9910-47dd-afe6-5af1a352f16b)

**Comment by uzair329** [comment]
you didnt mention buying rate here you need to add buy rate if vendor is charging you as well further billing increment block are mention at first page write 60 


![image](https://github.com/magnussolution/magnusbilling7/assets/59938185/df16fbed-17a7-4174-954f-c7c56c458d56)
