### ISSUE TITLE
Trunk Error Option not working after Reset

### ISSUE THREAD

**Issue by xceedconnections** [magnussolution/magnusbilling#668]
I am using Magnusbilling Version 9.8.4.3
After i reset the Trunk errors, its not fetching new trunk error now, It stopped working..

Command i had to fix the trunk code is also not working on new verions

[root@centos-8gb-hel1-2 ~]# php /var/www/html/mbilling/cron.php TrunkSIPCodes
PHP Error[8]: Undefined variable: lines
    in file /var/www/html/mbilling/protected/commands/TrunkSIPCodesCommand.php at line 43
#0 /var/www/html/mbilling/yii/framework/console/CConsoleCommandRunner.php(71): TrunkSIPCodesCommand->run()
#1 /var/www/html/mbilling/yii/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#2 /var/www/html/mbilling/yii/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#3 /var/www/html/mbilling/cron.php(31): CConsoleApplication->run()

Please fix this in the next Update!

**Comment by magnussolution** [comment]
I checked just now, and not see this error. Have you updated your MagnusBilling?

**Comment by xceedconnections** [comment]
thanks sir, updating mbilling worked!

**Comment by xceedconnections** [comment]
fixed
