### ISSUE TITLE
Logado Eternamente no portal da Plataforma WEB

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#67]
**Não sei se e problema de cookie ou alguma outra coisa!**

**Voce efetua um login e mesmo depois de ter desligado o servidor do MB6, vc digita o endereço apose tres dias e vc continua logado no sistema!**

**Se não efetuar logout continua logado eternamente!**

**Comment by magnussolution** [comment]
qual navegador?

**Comment by yurikurka** [comment]
Google Chrome

**Comment by magnussolution** [comment]
testei 3 instalações, tanto local, como em datacenter, e so fecho o navegador e ja pede senha novamente.

So nao testei em Windows. Mas acredito que não muda nada

**Comment by yurikurka** [comment]
Enquanto voce não limpa os cookies ele continua logado! So limpando o cache não resolve!

**Comment by magnussolution** [comment]
aqui nao da isso, me manda seu ip e cria um usuário de teste para mim testar em seu servidor

**Comment by yurikurka** [comment]
Vou mandar no seu Whastsup, segue o video para voce ver também.
[logado.zip](https://github.com/magnussolution/magnusbilling6/files/1338493/logado.zip)

**Comment by magnussolution** [comment]
nao foi possível simular o problema em outros computadores. Provavelmente problema local
