### ISSUE TITLE
fail2ban sock

### ISSUE THREAD

**Issue by koravko** [magnussolution/magnusbilling#69]
[root@mbilling ~]# fail2ban-server start
 There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.
 Async configuration of server failed
 problem is on CentOS 7

FIX: in install script make to create this folder befor start fail2ban server

**Comment by koravko** [comment]
missing en.png and fr.png (flags) in mbilling6 
/var/www/html/mbilling/resources/images/flags/

**Comment by magnussolution** [comment]
1 issue to each problem.

**Comment by magnussolution** [comment]
thanks sir by your report and solution.
