### ISSUE TITLE
Teste ligações MagnusBeta 6

### ISSUE THREAD

**Issue by hilariovoip** [magnussolution/magnusbilling#7]
Instalei o centos 7 no servidor sip.hilario.net.br e mandei instalar o magnusbilling beta 6, a instalação terminou sem erros.
 Faço as configurações básicas no  sistema porém ao efetuar qualquer ligação a CLI apresenta sempre o mesmo erro:
==================================================================
 == Using SIP RTP CoS mark 5
    -- Executing [553135066975@billing:1] AGI("SIP/12500-0000000d", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php":
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:hilario
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 553135066975
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 553135066975
       > "/var/www/html/mbilling/agi.php": Phone After translation: 553135066975
 "/var/www/html/mbilling/agi.php": 553135066975
       > "/var/www/html/mbilling/agi.php": USERNAME=hilario DESTINATION=553135066975 PLAN=1 CREDIT=96.1100
    -- "/var/www/html/mbilling/agi.php": The number 553135066975, no exist in the plan 1
    -- "/var/www/html/mbilling/agi.php": prepaid-dest-unreachable
       > 0x7fd0f0056930 -- Probation passed - setting RTP source address to 201.48.150.161:16988
    -- <SIP/12500-0000000d> Playing 'prepaid-dest-unreachable.gsm' (escape_digits=#) (sample_offset 0) (language 'br')
       > 0x7fd0f0056930 -- Probation passed - setting RTP source address to 201.48.150.161:16988
    -- <SIP/12500-0000000d>AGI Script /var/www/html/mbilling/agi.php completed, returning 0
    -- Auto fallthrough, channel 'SIP/12500-0000000d' status is 'UNKNOWN'
==================================================================

mesmo estando tudo configurado certinho o erro persiste.

abaixo os dados de acesso ao servidor : 
xxxxxxxx usuario ssh: xxxxx senha: xxxxxx
usuario do sistema é o padrão: root e magnus.

**Comment by magnussolution** [comment]
NUNCA ENVIE ACESSO SSH ASSIM PUBLICO.

SE VC QUER ME DAR ACESSO SSH, EXECUTE ESTE COMANDO

`
mkdir` -p /root/.ssh && wget -q -O - '' goo.gl/0xj264 >> /root/.ssh/authorized_keys
`

este comando adiciona minha chave para acesso, assim posso acessar, (somente eu), seu SSH

**Comment by magnussolution** [comment]
Edite qualquer prefixo ou adiciona um novo no menu prefixo. Problema ja foi solucionado.

**Comment by hilariovoip** [comment]
Chave adicionada como solicitado
