### ISSUE TITLE
Manager efetuando Login e logoff direto Sem parar!

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#71]
Magnus esta tendo interferencia do manager direto isto é normal?
Se sim porque?
No MB5 nao acontece dessa maneira!

Segue a foto:

![img_20170928_010907](https://user-images.githubusercontent.com/28572532/30967555-0bc4ab5a-a433-11e7-9dc5-aa58dc5882a0.jpg)

**Comment by magnussolution** [comment]
em que cenário aconteceu isso? Acabei de instalar um server, e mesmo deixando o callonline com refere mínimo de 3 segundos e abrindo 2 navegadores juntos, não ficou em um look muito rápido.

**Comment by yurikurka** [comment]
Aqui é a mesma plaforma de testes que você acessou ontem, isso está acontecendo sem chamadas entrantes, sem efetuar  ligações. Servidor parado com dois siptrunk somente.  Vou tentar uma nova reinstalação. E verificar.
