### ISSUE TITLE
Incease upload size from 3M to 6M

### ISSUE THREAD

**Issue by koravko** [magnussolution/magnusbilling#72]
increase default upload size by default to be 6M have a biggest ratelist like betamax wich are 5M +

**Comment by magnussolution** [comment]
i recommend you split your rate list. Big files can take many time to process and make your proaction server slow.

**Comment by magnussolution** [comment]
each user can change it according your self necessity

**Comment by koravko** [comment]
in amed to callshop and resllers why not insert to DB direct Prefix and Destination only to skip 2 steps befor starting use Mbilling ?
