### ISSUE TITLE
i cann't change username

### ISSUE THREAD

**Issue by llamabara** [magnussolution/magnusbilling#73]
i cann't create a user into a reseller or agent

in this image, you can see it.
<img width="1280" alt="screen shot 2017-09-29 at 2 25 53 am 2" src="https://user-images.githubusercontent.com/32110802/31005343-e4624e9c-a4bd-11e7-85b8-924915207422.png">

**Comment by magnussolution** [comment]
Please read this link https://github.com/magnussolution/magnusbilling6/issues/57
