### ISSUE TITLE
ERRO AO TENTAR ALTERAR TAMANHO DO CAMPO USERNAME

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#74]
![erro-na-configuracao-tamanh](https://user-images.githubusercontent.com/18689067/31028162-5f24dafe-a523-11e7-95bb-3a6a19615de1.png)

Segue print!

**Comment by magnussolution** [comment]
deve ter dado um pau ai no javascript pois vc tem um campo selecionado e no form esta outro. da um F5 e testa novamente

**Comment by RodrigoRDC17** [comment]
ok! Vou atualizar! Obrigado! Realmente deve ter sido isso mesmo!
