### ISSUE TITLE
USUARIO SENDO CRIADO SEM O DDD

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#75]
![criando-usuario-sem-ddd](https://user-images.githubusercontent.com/18689067/31028184-7c58533a-a523-11e7-82dd-7849a8fa4ea0.png)

segue print!

**Comment by magnussolution** [comment]
veja no menu configurações a opção "country" não deve estar BRL.

Isso esta explicado no 1º video do MagnusBilling desde a versão 3.
