### ISSUE TITLE
CRIANDO NOVO RAMAL NAO APARECE USUARIO E SENHA

### ISSUE THREAD

**Issue by RodrigoRDC17** [magnussolution/magnusbilling#76]
![novo-ramal-sem-usuario-e-se](https://user-images.githubusercontent.com/18689067/31029246-66e1d888-a527-11e7-816e-eac5895fa112.png)

Segue print

**Comment by magnussolution** [comment]
nao entendi

**Comment by RodrigoRDC17** [comment]
Quando clica em Conta VOIP => NOVO 

Ele nao preenche os dados de usuario e senha - deixa em branco

**Comment by magnussolution** [comment]
sempre foi assim.
