### ISSUE TITLE
Manager Maluco  logged on  e  logged off 

### ISSUE THREAD

**Issue by yurikurka** [magnussolution/magnusbilling#77]
efetuei a instalação do zero e o manager nao para de fazer logged on e logged off sem parar!

Veja o video

[Manager.zip](https://github.com/magnussolution/magnusbilling6/files/1345274/Manager.zip)

**Comment by magnussolution** [comment]
realmente nao sei o que dizer, instalei em cloud da digitaocean, e tudo normal, 1 coe≈ao cada 12 segundo é normal, por causa do gráfico das chamadas online.

https://cl.ly/2z0n2t3X062k

**Comment by yurikurka** [comment]
Estranho, hoje vou testar em um servidor esxi da vmware, faça o teste local na sua máquina. Posto comentários ainda hoje.

**Comment by RodrigoRDC17** [comment]
Realmente Adilson isso ocorre em servidores dedicados e maquina virtual tambem! Logged on e off constantemente! Testado agora!

**Comment by yurikurka** [comment]
Verifiquei que na pagina principal chamadas online quando esta em dez segundos ele esta ficando doido assim aumentando esse valor para 20 segundos ele fica mais rasoavel, o interessante que no 5 ele não se comporta dessa mesma maneira!

**Comment by voztovoice** [comment]
Hello,
add this line:

displayconnects = no

to this block:

[magnus]
secret = magnussolution
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.0
read = system,call,log,verbose,agent,user,config,dtmf,reporting,cdr,dialplan
write = system,call,agent,user,config,command,reporting,originate

then save and restart asterisk

systemctl restart Asterisk (v6) o service asterisk restart (v5)

Regards

**Comment by magnussolution** [comment]
ola. realmente nao consigo simular o que vc relata. Segue video com 1 server recém instalado para um cliente

https://cl.ly/1H0a2O3F1O3S

Vou fechar o ticket
