### ISSUE TITLE
Callback feature not listed under the Users Menu

### ISSUE THREAD

**Issue by Leaqueb** [magnussolution/magnusbilling#79]
There is a callback feature listed under the new Services Menu, but callback is not listed under the Users Menu
![image](https://user-images.githubusercontent.com/30846815/31046033-e66082ce-a5f1-11e7-95d4-fff23de47828.png)

![image](https://user-images.githubusercontent.com/30846815/31046052-34547396-a5f2-11e7-8416-8bb379cafe7b.png)

**Comment by magnussolution** [comment]
Menu services is a new features in MAgnusBilling to Sell services, but not have documentation yet.
We make a Webinar in Portuguese to present new MagnusBilling 6 features.

We need help to make English documentation
