### ISSUE TITLE
Upgrade da v5 para v6.

### ISSUE THREAD

**Issue by rfminelli** [magnussolution/magnusbilling#84]
**Realizei todo o procedimento especificado na url:**
``
https://www.magnusbilling.com/br/forum/5/how-upgrade-your-magnusbilling-v5-to-v6-2279.html
``

Após efetuar todo o processo e dar o reboot na maquina identifiquei um problema o MBilling aparecia o Box solicitando User e Pass, mas não efetuava o logon no sistema ficando na tela MBilling Iniciando.
**Usando o Firebug verifiquei que estava retornando o seguinte erro:**

GET http://170.82.16.220/mbilling/index.php/authentication/check?_dc=1507246329681 | 500 Internal Server Error |   | 65ms

**Aba Html**
Internal Server Error
A tabela "pkg_group_user_group" da classe de active record "GroupUserGroup", não pôde ser encontrada no banco de dados.

An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you. 

**Foi ai que percebi que o ultimo comando realizado:**
``
php /var/www/html/mbilling/cron.php updatemysql
``
Retorna 6.0.4

Quando fui verificar o banco de dados vi que o mesmo não foi atualizado e falta várias tabelas.

**Linux Version**
``
cat /etc/redhat-release
``
CentOS Linux release 7.4.1708 (Core)

**Comment by magnussolution** [comment]
ola, nao tenho como fazer testes, estou sem servidor.

Instale um Magnusbilling 5, e me mande acesso SSH por email. Eu testarei a atualizacao.

Lembrando que no Webinar que foi feito sobre MagnusBilling 6, foi mostrado um teste de atualizacao e foi ok. Tambem ja atualizei de alguns clientes e tambem nao tive problema.

**Comment by rfminelli** [comment]
Disponibilizo na segunda o proprio servidor que fiz o teste.
Efetuei Snapshot.
