### ISSUE TITLE
install script debian 8 does not generate mysql user or password

### ISSUE THREAD

**Issue by astan24** [magnussolution/magnusbilling#85]
Installed on clean minimal Debian 8 64 bit on KVM.
Line 306 -308 set user and password for MySQL for Centos Distribution but does not do it for Debian

log from install
----------- Installing the new Database ----------

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by magnussolution** [comment]
hi, Debian mysqld password is set on line 104 and 106

```
echo mysql-server mysql-server/root_password password ${password} | debconf-set-selections
    echo mysql-server mysql-server/root_password_again password ${password} | debconf-set-selections 
```
