### ISSUE TITLE
CDR not show calls

### ISSUE THREAD

**Issue by llamabara** [magnussolution/magnusbilling#86]
**# The calls made with an user who belogs to reseller account, isn't showed into CDR and not billed**

  == Using SIP RTP CoS mark 5
    -- Executing [5219661042486@billing:1] AGI("SIP/COPAINALA-00000004", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:COPAINALA
       > "/var/www/html/mbilling/agi.php": Reseller id_Plan 3, user id_plan 3
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 5219661042486
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 5219661042486
       > "/var/www/html/mbilling/agi.php": Phone After translation: 5219661042486
 "/var/www/html/mbilling/agi.php": 5219661042486
       > "/var/www/html/mbilling/agi.php": USERNAME=COPAINALA DESTINATION=5219661042486 PLAN=3 CREDIT=5000.0000
       > "/var/www/html/mbilling/agi.php": NUMBER TRUNK FOUND1
       > "/var/www/html/mbilling/agi.php": NUMBER TARIFF FOUND -> 1
       > "/var/www/html/mbilling/agi.php": TIMEOUT->120000 : minutes=2000 - seconds=0
    -- AGI Script Executing Application: (DIAL) Options: (sip/silver/5219661042486,60,L(120000000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 120000000 ms (120000.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    = 
       > warning_sound  = timeleft
       > end_sound      = 
  == Using SIP RTP CoS mark 5
    -- Called sip/silver/5219661042486
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
    -- SIP/silver-00000005 is making progress passing it to SIP/COPAINALA-00000004
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
       > 0x7fb58c0060b0 -- Probation passed - setting RTP source address to 189.129.80.210:58560
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
       > 0x7fb58c012b50 -- Probation passed - setting RTP source address to 62.93.147.153:21450
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
       > "/var/www/html/mbilling/agi.php": Update System
       > "/var/www/html/mbilling/agi.php": Sessiontime0
       > "/var/www/html/mbilling/agi.php": CALL: used tariff K= - (sessiontime=0 :: dialstatus=CANCEL)
 "/var/www/html/mbilling/agi.php": Insert failed call
    -- <SIP/COPAINALA-00000004>AGI Script /var/www/html/mbilling/agi.php completed, returning 4
  == Spawn extension (billing, 5219661042486, 1) exited non-zero on 'SIP/COPAINALA-00000004'
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Using SIP RTP CoS mark 5
    -- Executing [5219661042486@billing:1] AGI("SIP/COPAINALA-00000006", ""/var/www/html/mbilling/agi.php"") in new stack
    -- Launched AGI Script /var/www/html/mbilling/agi.php
       > "/var/www/html/mbilling/agi.php": 
       > "/var/www/html/mbilling/agi.php": Start MBilling AGI
       > "/var/www/html/mbilling/agi.php": AUTHENTICATION BY ACCOUNTCODE:COPAINALA
       > "/var/www/html/mbilling/agi.php": Reseller id_Plan 3, user id_plan 3
       > "/var/www/html/mbilling/agi.php": USE_DNID DESTINATION -> 5219661042486
       > "/var/www/html/mbilling/agi.php": REMOVE INTERNACIONAL PREFIX -> 5219661042486
       > "/var/www/html/mbilling/agi.php": Phone After translation: 5219661042486
 "/var/www/html/mbilling/agi.php": 5219661042486
       > "/var/www/html/mbilling/agi.php": USERNAME=COPAINALA DESTINATION=5219661042486 PLAN=3 CREDIT=5000.0000
       > "/var/www/html/mbilling/agi.php": NUMBER TRUNK FOUND1
       > "/var/www/html/mbilling/agi.php": NUMBER TARIFF FOUND -> 1
       > "/var/www/html/mbilling/agi.php": TIMEOUT->120000 : minutes=2000 - seconds=0
    -- AGI Script Executing Application: (DIAL) Options: (sip/silver/5219661042486,60,L(120000000:61000:30000))
       > Limit Data for this call:
       > timelimit      = 120000000 ms (120000.000 s)
       > play_warning   = 61000 ms (61.000 s)
       > play_to_caller = yes
       > play_to_callee = no
       > warning_freq   = 30000 ms (30.000 s)
       > start_sound    = 
       > warning_sound  = timeleft
       > end_sound      = 
  == Using SIP RTP CoS mark 5
    -- Called sip/silver/5219661042486
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
    -- SIP/silver-00000007 is making progress passing it to SIP/COPAINALA-00000006
       > 0x7fb5c400d850 -- Probation passed - setting RTP source address to 62.93.147.153:23960
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
       > 0x7fb58c0060b0 -- Probation passed - setting RTP source address to 189.129.80.210:58560
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
    -- SIP/silver-00000007 is ringing
    -- SIP/silver-00000007 is making progress passing it to SIP/COPAINALA-00000006
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
    -- SIP/silver-00000007 answered SIP/COPAINALA-00000006
    -- Channel SIP/silver-00000007 joined 'simple_bridge' basic-bridge <a7f844d9-fe16-47cf-876b-2e0c8244ac6a>
    -- Channel SIP/COPAINALA-00000006 joined 'simple_bridge' basic-bridge <a7f844d9-fe16-47cf-876b-2e0c8244ac6a>
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
  == Manager 'magnus' logged on from 127.0.0.1
  == Manager 'magnus' logged off from 127.0.0.1
    -- Channel SIP/COPAINALA-00000006 left 'simple_bridge' basic-bridge <a7f844d9-fe16-47cf-876b-2e0c8244ac6a>
    -- Channel SIP/silver-00000007 left 'simple_bridge' basic-bridge <a7f844d9-fe16-47cf-876b-2e0c8244ac6a>
       > "/var/www/html/mbilling/agi.php": USED TARIFF=0
       > "/var/www/html/mbilling/agi.php": Update System
       > "/var/www/html/mbilling/agi.php": CALCULCOST: K=0 - CALLDURATION:18 - freetimetocall_used=0
       > "/var/www/html/mbilling/agi.php": CALCULCOST: 1. COST: $cost = (60/60) * 2.5 
       > "/var/www/html/mbilling/agi.php": CALCULCOST: K=0 - BUYCOST:2.5 - SELLING COST:2.5
       > "/var/www/html/mbilling/agi.php": $this->lastbuycost = 2.5
       > "/var/www/html/mbilling/agi.php": $this->lastcost = 2.5
       > "/var/www/html/mbilling/agi.php": Sessiontime18
       > "/var/www/html/mbilling/agi.php": CALL: used tariff K=0 - (sessiontime=18 :: dialstatus=ANSWER)
    -- <SIP/COPAINALA-00000006>AGI Script /var/www/html/mbilling/agi.php completed, returning 4
  == Spawn extension (billing, 5219661042486, 1) exited non-zero on 'SIP/COPAINALA-00000006'

**Comment by RodrigoRDC17** [comment]
Adilson o erro de nao aparecer o CDR é devido a colocaçao desta linha no manager.conf

displayconnects = no

mude para yes ou retire o CDR volta!

Porem a questao do login and loginout continua!

Vi que esta linha foi colocada para ocultar este erro!

Espero ter ajudado!

**Comment by RodrigoRDC17** [comment]
Good afternoon! Anyone who has trouble viewing the CDR. Just change the manager.conf file

in the line where it is

displayconnects = no

change to yes or delete and restart asterisk and have your CDR running!

I hope I have helped!

**Comment by magnussolution** [comment]
displayconnects = yes ; -> should the command-line display the connections to the Asterisk;

this option not have relation with CDR
http://www.asteriskdocs.org/en/3rd_Edition/asterisk-book-html-chunk/AMI-configuration.html
