### ISSUE TITLE
mysql not running after new install

### ISSUE THREAD

**Issue by astan24** [magnussolution/magnusbilling#87]
tried several time to do a clean install on debian 8 minimal KVM.
MySQL is not running after the install 
Am not seeing any errors during the install process other than at the end when the database is trying to be populated due to it not running

root@magnus1:/var/log# systemctl status mysql -l
â mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql)
   Active: failed (Result: exit-code) since Tue 2017-10-17 20:25:07 EDT; 42min ago
  Process: 445 ExecStart=/etc/init.d/mysql start (code=exited, status=1/FAILURE)

Oct 17 20:25:07 magnus1 mysql[445]: Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
Oct 17 20:25:07 magnus1 systemd[1]: mysql.service: control process exited, code=exited status=1
Oct 17 20:25:07 magnus1 systemd[1]: Failed to start LSB: Start and stop the mysql database server daemon.
Oct 17 20:25:07 magnus1 systemd[1]: Unit mysql.service entered failed state.

**Comment by magnussolution** [comment]
try 

apt-get install -y mysql-server php5-mysql

**Comment by astan24** [comment]
root@magnus1:~# apt-get install -y mysql-server php5-mysql
Reading package lists... Done
Building dependency tree
Reading state information... Done
php5-mysql is already the newest version.
mysql-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@magnus1:~# systemctl status mysql -l
â mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql)
   Active: failed (Result: exit-code) since Tue 2017-10-17 20:25:07 EDT; 1 day 1h ago
  Process: 445 ExecStart=/etc/init.d/mysql start (code=exited, status=1/FAILURE)

Oct 17 20:25:07 magnus1 mysql[445]: Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
Oct 17 20:25:07 magnus1 systemd[1]: mysql.service: control process exited, code=exited status=1
Oct 17 20:25:07 magnus1 systemd[1]: Failed to start LSB: Start and stop the mysql database server daemon.
Oct 17 20:25:07 magnus1 systemd[1]: Unit mysql.service entered failed state.
root@magnus1:~#

**Comment by magnussolution** [comment]
I'm so sorry, but i never use Debian and I not know this issue. Find in Debian or Mysql forums.

If you found the solution, post here. 

Best Regards
