### ISSUE TITLE
Atualização de numero em Agenda

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#88]
http://199.241.187.158/mbilling/
usuario: root
senha: admin

Foi criado uma agenda e inserido numeros na agenda.
Quando vou em numero tentar filtrar por agenda nao funciona.
Assim como atualização em lote e reprocessar os numeros => Fica apenas processando 
![image](https://user-images.githubusercontent.com/30813258/31726530-01f6470e-b406-11e7-8dd9-3df5c314ae50.png)

**Comment by magnussolution** [comment]
Resolvi o problema 1 hora e 30 min de trabalho.

**Comment by hiperphone** [comment]
Para atualizar para testar após você ajustar o reportado no  github

 

continua sendo para billing tipo descktop com marca própria ?

 

/var/www/html/mbilling/protected/commands/update2.sh

 

Atenciosamente

 

Rubem Junior
Hiperphone

Business Phone: +55 (11) 3522 4670

Business Phone: +55 (11) 3509 2219

Business Phone: +55 (61) 3246 0230 

Business Phone: +55 0800 880 1020

Mobile Phone: +55 (77) 9 9968 4670 - Vivo
Mobile Phone: +55 (77) 9 9191 4670 - TIM

e-mail:  <mailto:suporte@hiperphone.com.br> comercial@hiperphone.com.br

website: www.hiperphone.com.br


Hipervoip : 10

Skype: rubem.hiperphone

 

 <http://200.184.77.144/programas/webcallback/wcbnosite.php?web_origem=rubem11> 

 

De: magnussolution [mailto:notifications@github.com] 
Enviada em: quarta-feira, 18 de outubro de 2017 18:29
Para: magnussolution/magnusbilling6 <magnusbilling6@noreply.github.com>
Cc: hiperphone <comercial@hiperphone.com.br>; Author <author@noreply.github.com>
Assunto: Re: [magnussolution/magnusbilling6] Atualização de numero em Agenda (#88)

 

Resolvi o problema 1 hora e 30 min de trabalho.

**Comment by magnussolution** [comment]
/var/www/html/mbilling/protected/commands/update.sh

**Comment by hiperphone** [comment]
Apresentou esta mensagem que atualizei com o comando que você envio

 

/var/www/html/mbilling/protected/commands/update.sh: line 22: /var/www/html/mbilling/protected/commands/update2.sh: Permission denied

 

Atenciosamente

 

Rubem Junior
Hiperphone

Business Phone: +55 (11) 3522 4670

Business Phone: +55 (11) 3509 2219

Business Phone: +55 (61) 3246 0230 

Business Phone: +55 0800 880 1020

Mobile Phone: +55 (77) 9 9968 4670 - Vivo
Mobile Phone: +55 (77) 9 9191 4670 - TIM

e-mail:  <mailto:suporte@hiperphone.com.br> comercial@hiperphone.com.br

website: www.hiperphone.com.br


Hipervoip : 10

Skype: rubem.hiperphone

 

 <http://200.184.77.144/programas/webcallback/wcbnosite.php?web_origem=rubem11> 

 

De: magnussolution [mailto:notifications@github.com] 
Enviada em: quarta-feira, 18 de outubro de 2017 18:34
Para: magnussolution/magnusbilling6 <magnusbilling6@noreply.github.com>
Cc: hiperphone <comercial@hiperphone.com.br>; Author <author@noreply.github.com>
Assunto: Re: [magnussolution/magnusbilling6] Atualização de numero em Agenda (#88)

 

/var/www/html/mbilling/protected/commands/update.sh
