### ISSUE TITLE
Alterar senha de usuario ADM

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#89]
http://199.241.187.158/mbilling/
usuario: root
senha: admin

Criei um usuario como ADM não esta disponivel campo para alterar a senha. Assim como no usuario root nao é possivel alterar a senha de acesso.

![image](https://user-images.githubusercontent.com/30813258/31726756-8a8af68c-b406-11e7-991f-532bd33faca2.png)

**Comment by magnussolution** [comment]
menu direito do mouse. Alterar senha.
