### ISSUE TITLE
Numero Bloqueados - Na ABA Torpedo de voz

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#91]
http://199.241.187.158/mbilling/
usuario: root
senha: admin

Inserir 2 vezes a mesma relação de numeros para testar a exclusão de numeros duplicados.
O mesmo nao esta funcionando, fica apenas processando. 

![image](https://user-images.githubusercontent.com/30813258/31731018-7e48b7c2-b412-11e7-859b-6fd76d39fcce.png)

**Comment by magnussolution** [comment]
30 minutos de trabalho para resolver

**Comment by hiperphone** [comment]
Magnus com o comando que você enviou apresentou a mensagem abaixo.

Como ajustar isso para prosseguir com os testes ? Vou testar todo o sistema ate domingo.
Ate mesmo o que não usamos. 

 

 

Apresentou esta mensagem que atualizei com o comando que você envio

 

/var/www/html/mbilling/protected/commands/update.sh: line 22: /var/www/html/mbilling/protected/commands/update2.sh: Permission denied

 

 



 

Atenciosamente

 

Rubem Junior
Hiperphone

Business Phone: +55 (11) 3522 4670

Business Phone: +55 (11) 3509 2219

Business Phone: +55 (61) 3246 0230 

Business Phone: +55 0800 880 1020

Mobile Phone: +55 (77) 9 9968 4670 - Vivo
Mobile Phone: +55 (77) 9 9191 4670 - TIM

e-mail:  <mailto:suporte@hiperphone.com.br> comercial@hiperphone.com.br

website: www.hiperphone.com.br


Hipervoip : 10

Skype: rubem.hiperphone

 

 <http://200.184.77.144/programas/webcallback/wcbnosite.php?web_origem=rubem11> 

 

De: magnussolution [mailto:notifications@github.com] 
Enviada em: quarta-feira, 18 de outubro de 2017 20:17
Para: magnussolution/magnusbilling6 <magnusbilling6@noreply.github.com>
Cc: hiperphone <comercial@hiperphone.com.br>; Author <author@noreply.github.com>
Assunto: Re: [magnussolution/magnusbilling6] Numero Bloqueados - Na ABA Torpedo de voz (#91)

 

30 minutos de trabalho para resolver

**Comment by magnussolution** [comment]
chmod +x /var/www/html/mbilling/protected/commands/update2.sh
