### ISSUE TITLE
Campanhas de Torpedo de Voz

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#92]
http://199.241.187.158/mbilling/
usuario: root
senha: admin

Criei alguns agendas no billing MB6..
Onde a agenda Rubem foi adicionado os numeros manualmente e Teste02 importei arquivo ,cvs

A campanha funcionou perfeitamente com a Agenda que inserir os numeros manualmente, ja a que importei de arquivo .csv a campanha nao dispara.

Utilizando ambas as agendas cliquei no Botao Teste de Campanha e o mesmo nao informou erro.

![image](https://user-images.githubusercontent.com/30813258/31736555-e2f03eaa-b423-11e7-8393-b7dc6ac4fce4.png)

**Comment by magnussolution** [comment]
sem detalhes nao tenho como ficar analisando seu servidor para encontrar problemas. Este espaço é para colocar BUG com detalhes. Leia https://github.com/magnussolution/magnusbilling6/issues/56
