### ISSUE TITLE
Exportar arquivo CSV

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#93]
http://199.241.187.158/mbilling/
usuario: root
senha: admin

Tentei exportar extrato de chamada em arquivo CSV , mas apresenta problema
O Arquivo gerado nao consigo enviar por aqui... Tirei print da imagem gerando.

![image](https://user-images.githubusercontent.com/30813258/31736949-ddd5dd52-b424-11e7-8e3f-30306f728da2.png)

**Comment by magnussolution** [comment]
esta exportando perfeitamente. Leia https://github.com/magnussolution/magnusbilling6/issues/56

Nao coloque nados de acesso ao seu servidor aqui. Atenção com a segurança. Este espaço é publico
