### ISSUE TITLE
Numero - ABA Torpedo de Voz

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#94]
bom dia!

Apos atualização, agora consigo alterar o status dos numero.

Quando tento deletar todos os numero apresenta mensagem de erro conforme imagens
![image](https://user-images.githubusercontent.com/30813258/31769598-19190ec8-b4b3-11e7-9e2f-1d134dd2220d.png)

Deletar os numeros selecionados esta funcionando.

**Comment by hiperphone** [comment]
A segunda imagem foi errado

A imagem do delete
![image](https://user-images.githubusercontent.com/30813258/31769598-19190ec8-b4b3-11e7-9e2f-1d134dd2220d.png)

**Comment by hiperphone** [comment]
Filtro por status / por numero  tambem nao esta funcionando.

![image](https://user-images.githubusercontent.com/30813258/31770351-4002a0f0-b4b6-11e7-9e0b-4b7b3c9b70a6.png)

**Comment by magnussolution** [comment]
por favor, um problema por chamado. Nao misture as coisa por favor. Mais uma vez, leia o POST https://github.com/magnussolution/magnusbilling6/issues/56

removi um dos problemas relatados. Podera abrir outro ISSUE se quiser

**Comment by magnussolution** [comment]
Resolvido, 30 minutos de trabalho
