### ISSUE TITLE
Gravações de Ligações

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#96]
Foi criado um assinante com permissão para ligações.
Testei realizar uma ligação mas a mesma nao foi gravada. A pasta tambem não foi criada.

![image](https://user-images.githubusercontent.com/30813258/31775338-1375cad8-b4c7-11e7-8d64-f4059ceb825d.png)
![image](https://user-images.githubusercontent.com/30813258/31775349-1e1380ac-b4c7-11e7-8aa0-d64cff7f5704.png)
![image](https://user-images.githubusercontent.com/30813258/31775360-26be59ac-b4c7-11e7-917f-4fb74cecc028.png)

**Comment by magnussolution** [comment]
na versão 6 a gravação é por ramal, não no versão.
