### ISSUE TITLE
Envio de SMS - Sem funcionar

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#98]
Configurei a mesma conta que tenho no outro servidor para enviar SMS.
Fiz varias tentativas sem sucesso.. Nao saberia como reportar o erro.
caso precise para testar te envio uma URL para envio de SMS e/ou te passo o acesso ao servidor.

![image](https://user-images.githubusercontent.com/30813258/31788539-c70897c6-b4ed-11e7-900d-d2853c390e8f.png)

Existe o prefixo criado para o envio e esta tambem no Plano.

![image](https://user-images.githubusercontent.com/30813258/31788589-f0e4781c-b4ed-11e7-839c-0c49aa0304df.png)

**Comment by magnussolution** [comment]
resolvido 2 horas de trabalho
