### ISSUE TITLE
Criar conta assinante Via URL

### ISSUE THREAD

**Issue by hiperphone** [magnussolution/magnusbilling#99]
Testei ativar cliente via url como no MB5
http://199.241.187.158/hiperphone/index.php/signup/add

Nos Planos do MB6 tem a opção USAR PARA REGISTRO mas nao existe  a opção Credito inicial para novo usuario.

Mesmo Assim ativei a opção USAR PARA REGISTRO sem a opção Credito inicial para novo usuario   e retorna o seguinte erro.

Internal Server Error

CAssetManager.basePath "/var/www/html/mbilling/assets" é inválido. Por favor, tanha certeza que o diretório existe e que o servidor Web possa escrever nele.

An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you.

2017-10-19 17:27:02

**Comment by magnussolution** [comment]
chown -R asterisk:asterisk /var/www/html/mbilling/assets
